### ISSUE TITLE
Missing option to translate (i18n)

### ISSUE THREAD

**Issue by jordano159** [fiduswriter/Simple-DataTables#101]
I've searched the documentation and haven't found a way to translate to interface to other languages.
Is there a way to do this?
Thanks.

**Comment by nekitoblack** [comment]
It took me a time to find it too (and also found your Issue); for future searches I drop the link here~

https://github.com/fiduswriter/Simple-DataTables/wiki/labels

```js
new simpleDatatables.DataTable("#myTable", {
    labels: {
        placeholder: "Sesarch...",
        perPage: "{select} entries per page",
        noRows: "No entries to found",
        info: "Showing {start} to {end} of {rows} entries",
    },
    // ...
});
```
