### ISSUE TITLE
Column options request: Custom sort function

### ISSUE THREAD

**Issue by toddmedema** [fiduswriter/simple-datatables#104]
I have a column of IP addresses, which have to be handled as strings because they aren't valid numbers. Unfortunately, string sorting doesn't get the order right:

192.168.1.195
192.168.1.2
192.168.1.20

Since the columns are already so customizable, would it be possible to support providing a custom sort function?

**Comment by dernst-art** [comment]
would love to see this feature also!

**Comment by janisdd** [comment]
I just ran into a similar problem today and after looking at the sources I got it somewhat working…

There is a special html attribute `data-content`  (on the table cells) which is checked. If this attribute is found on the cell, its value is used for sorting (else the `innerText` is used).

If you generate the table you can use it like this:

```html
<table>
  <tr>
    <td data-content="192.168.001.195">192.168.1.195</td>
  <tr>
  <tr>
    <td data-content="192.168.001.002">192.168.1.2</td>
  <tr>
</table>
```

You just have to transform your ips to something that is properly sorted… e.g. pad all parts with zeros or something `192.168.1.195` -> `192.168.001.195`

Hope it helps.

**Comment by johanneswilm** [comment]
Hey @toddmedema @janisdd @dernst-art 

This can be done with version 6 as it allows you to define a custom order property for each cell. I hope that helps.
