### ISSUE TITLE
Formelements looses there value

### ISSUE THREAD

**Issue by steffen-webschuppen** [fiduswriter/simple-datatables#107]
I have a Table of people and different form fields to change specific values according ti the person.
The inputs looses their value as soon, as I sort the table.
I tried to reinit the Table, after every change, but this doesn't help.

I use the lib in a vanilla js environment with plane html+CSS3.

**Comment by johanneswilm** [comment]
Could you create a minimal example?

**Comment by steffen-webschuppen** [comment]
the table looks like this:
```
<form method="post" action="user">
            <table>
                <caption>Users</caption>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>is admin</th>
                        <th>note</th>
                        <th>actions</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Jens</td>
                        <td><input type="checkbox" name="is_admin_123"></td>
                        <td><input type="text" name="note_123"></td>
                        <td>
                            <input type="submit" value="edit" name="edit_123">
                            <input type="submit" value="delete" name="delete_123">
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
```

If I sort by name, I loose all Information, I already edited.

**Comment by johanneswilm** [comment]
Hey @steffen-webschuppen , 
yes that is to be expected. Take a look at the table editing plugin in version 6. Something like that could possibly work. Having a form inside the main table will probably never quite work.
