### ISSUE TITLE
elements loose their onchange prop

### ISSUE THREAD

**Issue by steffen-webschuppen** [fiduswriter/simple-datatables#108]
i add a onchange event to some inputs in my table. As son as i activate datatable, i loose those bound methods.

**Comment by johanneswilm** [comment]
@steffen-webschuppen There is not really a way around that as redrawing the dom will do that. Can you not use mutation observers or similar?

**Comment by steffen-webschuppen** [comment]
Hm, Maybe, we I could squeeze it somewhere around datatable.js:592

but I'm not sure, if one can handover all the props.
It would need to loop over all the child of the cell and untangle those on render 🤔

**Comment by johanneswilm** [comment]
Hey, as of version 6, you will need to put all event listeners on `table.dom`.
