### ISSUE TITLE
compatibility browsers due we will use in serious proyectos or toy hobbies?

### ISSUE THREAD

**Issue by mckaygerhard** [fiduswriter/Simple-DataTables#11]
i recently see that this are a update of the original vanilla-datatables... 

due the ES20XX compilant, what are the browsers support matrix? just "up to date fashion fever" ? 

iif there's no minimal olders browsers support i'm afraid that this are a "hobbie-made-for" proyect... we developers need in bussiness does not limits the clients!

**Comment by johanneswilm** [comment]
@mckaygerhard You sound an awful lot like @alpha-and-omega who came with similar attacks on modern JavaScript without knowing any of the facts.

If you would take the time to investigate how ES2015+ projects in general work, and this specifically, you would have found out that these projects use bundlers to translate the code back to a format usable also by old browsers that are still around. Should you in some way be trapped in a time machine and need to target IE9 or something like that cannot read the current format, what you would do is you would import this project in your project and add an extra bundling layer in your bundling system to get it down to where it can be read.

I spent a night and a day or so trying to help @alpha-and-omega last time only to have him walk of and not take my help. I'm not going to be making the same mistake this time. If you have some serious criticism or suggestion, I'm all ears. But remember you get all my work for free, your not obliged to take any of it, and I do require you to have at least some basic knowledge of what you are criticizing. Si prefieres escribir en español, eso mtambién es una opción.

I will close this issue now as you just seem to be rambling.

**Comment by mckaygerhard** [comment]
how interesting! i will sumarize that about "time machine": 

i have a 16G RAM, 8-cores Intel DELL R15 inspiron with discrete GPU's so enought to said "no in time machine".. and you will ask to you "well enought powerfully, why asking about older software support".. 

today are too many resources for programming.. that developers said: "well i have ram, lest use it, lest spend it"... later that relies in "more ram, more hardware".. like puff-daddy said some time: "more money more problems" and so and so..

i noted that in all my machines the google-chrome 27 works so far better rather than recently up to date version.. same for firefox.. later for all software, including javascript relate projects..

in resumen: seems today all the **developers use the "i made free" excuse to justify dependency-related changes and not perform more difficult changes..** and dont worry seems original author take more logic around that! more "sense" logic
