### ISSUE TITLE
Unable to click sort Columns after reorder 

### ISSUE THREAD

**Issue by bonez0607** [fiduswriter/Simple-DataTables#110]
Is there a particular function that needs to run after reordering columns using something like `dataTable.columns().order([4,3,2,1])`? The option to click the header to sort the column doesn't seem to work after reordering. 

I was able to replicate the issue [on codepen](https://codepen.io/jbanegas/pen/zYNyvRJ?editors=0010) forking one of the demos.

Any assistance is appreciated, thanks!

**Comment by bonez0607** [comment]
Was able to solve. It appears calling sort immediately after order resolves the issue `dataTable.columns().sort(0, "asc")`

**Comment by shaunroselt** [comment]
@bonez0607 

How exactly do the columns reordering work? Where does the code go?

I tried your code, but I get:

`Uncaught TypeError: dataTable.columns is not a function`.


Immediately after creating the dataTable, I am trying your code as can be seen here:
``` javascript
let dataTable = new simpleDatatables.DataTable(`#Table${TableParent.id}`, {
    searchable: true,
    sortable: true,
    perPage: 15,
    perPageSelect: [5,10,15,20,25,50,100,250,500,1000]
}); 

dataTable.columns().order([4,3,2,1]);
```



I am using v7.2

**Comment by shaunroselt** [comment]
Ah. I found out why `dataTable.columns().order([4,3,2,1])` wasn't working for me.

It's because as of v4, `columns` is a property and not a method.

So you need to use it as follows: `dataTable.columns.order([4,3,2,1])` without the `()`.


You can read more about it here: https://fiduswriter.github.io/simple-datatables/documentation/columns-API

**Comment by johanneswilm** [comment]
yes, please take a look at the documentation, upgrade document and demos
before filing issues.
