### ISSUE TITLE
Prepare json data in proper format

### ISSUE THREAD

**Issue by happytm** [fiduswriter/Simple-DataTables#111]
Thank you for your lightweight data tables. I wanted to use your tables for ESP32 micro controller. I am producing sensor data file in following format on same device locally and wanted to create a simple table using fetch API showing these data.

Content of sensor data file:

{"location":"Livingroom","rssi":"-72","mode":"0","ip":"6","channel":"7","sleeptime":"1","uptime":"138","temp":"65","humidity":"52"},
{"location":"Livingroom","rssi":"-72","mode":"0","ip":"6","channel":"7","sleeptime":"1","uptime":"138","temp":"64","humidity":"53"},
{"location":"Livingroom","rssi":"-72","mode":"0","ip":"6","channel":"7","sleeptime":"1","uptime":"138","temp":"65","humidity":"52"},
{"location":"Livingroom","rssi":"-72","mode":"0","ip":"6","channel":"7","sleeptime":"1","uptime":"138","temp":"66","humidity":"51"},

Is it possible to make this data format compatible ? If so please show me how ?

Thanks.

**Comment by Fr34k9** [comment]
```
[["location":"Livingroom","rssi":"-72","mode":"0","ip":"6","channel":"7","sleeptime":"1","uptime":"138","temp":"65","humidity":"52"],
["location":"Livingroom","rssi":"-72","mode":"0","ip":"6","channel":"7","sleeptime":"1","uptime":"138","temp":"64","humidity":"53"],
["location":"Livingroom","rssi":"-72","mode":"0","ip":"6","channel":"7","sleeptime":"1","uptime":"138","temp":"65","humidity":"52"],
["location":"Livingroom","rssi":"-72","mode":"0","ip":"6","channel":"7","sleeptime":"1","uptime":"138","temp":"66","humidity":"51"]]
```
Check out https://github.com/fiduswriter/Simple-DataTables/wiki/data

**Comment by happytm** [comment]
Thanks.
