### ISSUE TITLE
Date ordering does not take time into account

### ISSUE THREAD

**Issue by DawidJanczak** [fiduswriter/Simple-DataTables#112]
Hello,

We're running into an issue where a datetime string is being sorted just fine by date (ascending), but then within that particular date the times are out of sort. I believe this is because of https://github.com/fiduswriter/Simple-DataTables/blob/master/src/date.js#L34 - that `format('YYYYMMDD')` at the end makes time information lost. Just for reference the format we're using is `"DD/MM/YYYY HH:mm:ss"` Please let me know if you need any further info.

**Comment by Khazl** [comment]
You're right, that's the reason. I had the same issue with `Y-m-d H:i:s` format. So I moved to simple string sorting (cuz that's possible with this format).

You could create a PR to fix this.
