### ISSUE TITLE
Insert does not accept Array integers

### ISSUE THREAD

**Issue by tony-nz** [fiduswriter/simple-datatables#116]
If the data set is like the following: 

`let users = [
    {
        "user_id": "Cell 1",
        "firstname_legal": "Cell 1",
        "surname_legal": "Cell 1",
    },
    {
        "user_id": 221,
        "firstname_legal": "Cell 1",
        "surname_legal": "Cell 1",
    },
];
datatable.insert(users);`

The second row's user_id value of 221 does not get inserted. The way I got around this is on editing line 1023 in datatable.js:

`if (index > -1) {
     r[index] = cell;
}`

to

`if (index > -1) {
     r[index] = cell + '';
}`

Adding +'' will cast the cell as a string.

**Comment by hb237** [comment]
I am experiencing the same issue.

**Comment by johanneswilm** [comment]
Hey @tony-nz @hb237 ,
in version 6 of simple-datatables, you can actually store other things than strings in the table data. So this should no longer be an issue. Please reopen if it still happens to you.
