### ISSUE TITLE
dynamic serverside support example or really?

### ISSUE THREAD

**Issue by mckaygerhard** [fiduswriter/Simple-DataTables#12]
hi, i try to see if there's some server-side on demmand support just like jquery+datatable does.. but i cannot find any in the wiki! later I see there's no server-side dynamic request . i mean, there's serverside support, but not with "pagination trick on demand" like jquery does on each page request...

i compared datatables+jquery vs vanilla-datatable and due vanilla-datatables need or use the pre-rendered html table tags the performance are a little less rather than datatables+jquery that does not need a complete table body pre-rendered (due are build via javascript), that cos vanilla-datatables way's make two work: build and render the table with all the huge data, and later modify the html tags via javascript, in the first avoiding in jquery flavor to cheap time on page loading

so then, i think serverside with on demand data can be done if we can catch the pagin and the lengh of the vanilla-datatables and sent as parameter in the ajax:url request ... so the only changes related to vanilla-datatables code will be a way to get the "perPage"

**Comment by johanneswilm** [comment]
Again, if you had spent the time to read some basic ES2015 documentation, you would realize that the way to achieve what you want is to combine one library that does the kind of server lookup that you want with another library to do the visual presentation of that data. There is no reason why you would put them into the same library. 

Please stop trolling. Goodbye!

**Comment by mckaygerhard** [comment]
ah this issue seems you dont read carefully jajaja, men i talking about use the server-side on demand but take easy it's clear that Simple-DataTables dont support that!

if you want to really care see: https://datatables.net/examples/server_side/jsonp.html where each page are requested on demand the data, **that are not supported by your simple-datatable due your project was based on vanilla-datatables that never support that feature!**
