### ISSUE TITLE
Agregar a la documentacion .

### ISSUE THREAD

**Issue by diovamny** [fiduswriter/simple-datatables#120]
fetch(("app/month-report"+url).trim())
  .then(response => response.json())
  .then(data => {
   console.log(data);
    if (!data.length) return;
    const table = new simpleDatatables.DataTable(".table", {
      data: {
        headings: Object.keys(data[0]),
        data: data.map(item => Object.values(item)),
        labels: {
              placeholder: "Search data...",
              perPage: "Show {select}",
              noRows: "No data to display",
              info: "Showing {start} to {end} of {rows}",
        },
      },
    })
    table.on("datatable.init", function() {
      this.wrapper.className = this.wrapper.className.replace(" dataTable-loading", "");
    });
  }).catch(error => console.log(error));

**Comment by johanneswilm** [comment]
Hey, sure, we can put something into the documentation. Could you add a bit more explanatory text then?
