### ISSUE TITLE
Wordpress Plugin

### ISSUE THREAD

**Issue by moltra** [fiduswriter/Simple-DataTables#121]
Can this be ported to work with Wordpress as a table plugin?

**Comment by johanneswilm** [comment]
Hey, I'm not sure how Wordpress plugins work, but I'm almost sure that such a plugin would have to import this project and add a lot of integration code on where to get the data, etc. . This is a bit beyond the scope of this project, so I am closing this ticket. But if someone wants to create such a plugin, I'll help them as much as I can.
