### ISSUE TITLE
Show All Option Menu

### ISSUE THREAD

**Issue by ArsalanSiddique** [fiduswriter/simple-datatables#126]
Is there any way to configure menu in datatable

**Comment by ArsalanSiddique** [comment]
I want to show all entries/records so how can I add a 'Show All' option in the pagination menu. There are [5,10, 15,25] option in menu

**Comment by ArsalanSiddique** [comment]
![Uploading Screenshot from 2021-09-03 20-02-40.png…]()

**Comment by johanneswilm** [comment]
I don't think that upload worked @ArsalanSiddique

**Comment by ArsalanSiddique** [comment]
![Uploading Screenshot from 2021-09-03 20-02-40.png…]()

**Comment by ArsalanSiddique** [comment]
https://drive.google.com/file/d/1lxZ4ffTD5Injw5wxHZIz0MwZ07tEVy3g/view?usp=sharing

**Comment by KoalaBear84** [comment]
`perPageSelect: [10, 20, 30, -1]` works, but it also shows "-1" which isn't nice.

![image](https://user-images.githubusercontent.com/5886900/134894852-f2f2ad84-9ba9-4896-8e4b-c3121165122c.png)

**Comment by KoalaBear84** [comment]
Thanks @johanneswilm!
