### ISSUE TITLE
ScrollY issue

### ISSUE THREAD

**Issue by AziiMaymon** [fiduswriter/simple-datatables#128]
Scroll Y is not working properly, if it has more columns, kindly help

**Comment by iantrudell** [comment]
To elaborate, if scrollY is enabled, and if you have hide/unhide columns, the column widths will be all messed up.

I think the issue has to do with a total mismatch between the number of columns in the dataTable-headercontainer table and the dataTable-container table (see attached).

![column-width-mismatch](https://user-images.githubusercontent.com/33202657/170893228-86bd4db7-0019-49b3-a447-e5ec08dc2383.PNG)

**Comment by johanneswilm** [comment]
Hey @AziiMaymon @iantrudell ,
this should be fixed in version 6.0.0-2. Please take a look.
