### ISSUE TITLE
Sort dates by value other than what is displayed

### ISSUE THREAD

**Issue by heidilux** [fiduswriter/Simple-DataTables#129]
Hiya,

I'm migrating off of the jquery datatables library, and so far, the only bit I'm really missing is the ability to sort dates by a value other than what is displayed in the markup.

The other offers the ability to add a `data-sort` property to the `<th>`, and that value will be used as the sort value, rather than the actual content of the `<th>`.

For dates, this is especially useful as you can always drop a unix timestamp in there, allowing whatever human readable format you like for the html content.

Would be awesome if this could be implemented here!

**Comment by heidilux** [comment]
Just noticed this was already mentioned, although using the instance config rather than element properties.

https://github.com/fiduswriter/Simple-DataTables/issues/94#issue-802900213

Feel free to kill this if you wish.

**Comment by johanneswilm** [comment]
Hey @heidilux yeah this would come in handy. If you have the time, please submit a patch.

**Comment by heidilux** [comment]
Actually, @johanneswilm , it looks like you _did_ implement this feature. Both the search() and sort() methods check for the existence of a `data-content` attribute on the element. If it exists, _that's_ the content acted upon.
