### ISSUE TITLE
rendering issues on huge data! get browser crash

### ISSUE THREAD

**Issue by mckaygerhard** [fiduswriter/Simple-DataTables#13]
i compared datatables+jquery vs vanilla-datatable and ..

due vanilla-datatables need or use the pre-rendered html table tags the performance are a little less rather than datatables+jquery that does not need a complete table body pre-rendered (due are build via javascript), that due vanilla-datatables way's make two work: build and render the table with all the huge data, and later modify the html tags via javascript, in the first avoiding in jquery flavor to cheap time on page loading

using 30000 rows with 220 columns the vanilla-datatables crash the browsers, especially due are using the ES2015 especification.. additional needs prerender the html tags and later dinamically modify at client side those tags.. so then this project only work with little amount of data only!

**Comment by johanneswilm** [comment]
> especially due are using the ES2015 especification

Sorry, that cannot be the case as you are not actually running the ES2015 version in your browser. You are running a version that has been transpiled into ES5. 

I am getting the idea you are trolling. Good bye.

**Comment by mckaygerhard** [comment]
same about #12 .. using 2000000 row always cras due all the table must be render.. for those that want  solution see original project where will work in that!

**Comment by johanneswilm** [comment]
If datables.net does what you want - why don't you use that?
