### ISSUE TITLE
Sorting Datetimes

### ISSUE THREAD

**Issue by netjan** [fiduswriter/simple-datatables#132]
In /wiki/datetime it is:
Simple DataTables utilizes the MomentJS library for parsing datatime strings for easier column sorting.
but should be:
Simple DataTables utilizes the Day.js library for parsing datatime strings for easier column sorting.

In file: src/date.js
Could you correct format("YYYYMMDD") to format() to allow sorting by time also?

**Comment by janisdd** [comment]
See https://github.com/fiduswriter/Simple-DataTables/issues/104 for a workaround

**Comment by johanneswilm** [comment]
This is now working in version 6. Please take a look @janisdd @netjan
