### ISSUE TITLE
add OnClick event to events API

### ISSUE THREAD

**Issue by contreraspablo9** [fiduswriter/simple-datatables#133]
i am using this library on ember.js 

i would like to trigger som custom function when user clicks on some row of the table (passing this row as argument of course). 

i tried to add the "onclick" manually with setattribute("onClick","myfunction(this)")
once the table is rendered but i cant attach my controller functions by this way

**Comment by johanneswilm** [comment]
Hey,
you can attach event listeners onto `table.dom` as of version 6 of `simple-datatables`.

**Comment by seikosantana** [comment]
It seems like we have to click twice on a row to trigger the event. The first click focuses on the table but does not fire the event. Is there a way so that we dont have to click twice?
