### ISSUE TITLE
Filter issue if there are no filtered rows

### ISSUE THREAD

**Issue by TwIsL** [fiduswriter/simple-datatables#137]
If we filter some column that does not contain some term, in console we have:
```
Uncaught TypeError: this.data[0] is undefined
    setMessage simple-datatables.js:8
    filter simple-datatables.js:8
    sort simple-datatables.js:8
    bindEvents simple-datatables.js:8
simple-datatables.js:8:25147
```
[filter.zip](https://github.com/fiduswriter/Simple-DataTables/files/7395085/filter.zip)

**Comment by johanneswilm** [comment]
Hey @TwIsL , this should no longer happen in version 6. Please have a look.
