### ISSUE TITLE
Add UMD version to "dist" folder

### ISSUE THREAD

**Issue by dpilafian** [fiduswriter/Simple-DataTables#14]
The `rollup` module bundler has a `--format umd` option to output a [UMD](https://github.com/umdjs/umd) version that would simplify using **Simple-DataTables** in many projects.

**Comment by johanneswilm** [comment]
Ok, added

**Comment by dpilafian** [comment]
Does issue #24 _"Dynamic loading merged"_ preclude issue #15 _"Add UMD version to dist folder"_?

**Comment by johanneswilm** [comment]
@dpilafian: It is a while ago since I worked on the dynamic loading (December) but the way I remember it rollup outputs entirely different outputs once dynamic loading is enabled. One of them (no modules) should cover more or less what used to be UMD.
I can try to investigate that again, but maybe it's easier if you could look at what rollup options tweaks would work with your requirements.

**Comment by johanneswilm** [comment]
@dpilafian Yes, so trying to build a UMD version gives this error:

```
Error: UMD and IIFE output formats are not supported for code-splitting builds.
```

I can see there is a discussion about it here [1], but no solution. It seems like there it should be possible to create UMD outputs which just don't split the code from the same sources. I'm not sure why/if this hasn't been tried. Maybe you can find more about it.


[1] https://github.com/rollup/rollup/issues/2072

**Comment by dpilafian** [comment]
Yep, I encountered the same error.  I have not found a workaround yet.

**Comment by johanneswilm** [comment]
I see someone commented he'd prefer not to go back to webpack. If that means it works if we switch from rollup to webpack, then that would be an option as well.

**Comment by dpilafian** [comment]
BTW, the desire here is for **raw speed** (I don't care about supporting old browsers... the opportunity cost of supporting old browsers is generally more than an order of magnitude greater than anyone expects).  I unify, minify, and revision library files and then upload them to a CDN with 10 year cache expire headers so that there will only be one single HTTP request to get the libraries once every couple months for new versions.  For my use case, I optimize for speed over memory.

**Comment by johanneswilm** [comment]
fixed - again. Thanks!
