### ISSUE TITLE
5-column-manipulation demo broken

### ISSUE THREAD

**Issue by dandrews4** [fiduswriter/simple-datatables#149]
https://fiduswriter.github.io/Simple-DataTables/5-column-manipulation/ only renders one column (See attached images)

On the first pass it loads the Completion column. On the next pass to load the 4th column "3" in the index, it fails as there is no data there.

![simple-datatables-5error](https://user-images.githubusercontent.com/14017600/143971197-bc399948-d4f4-4119-b8ed-3c26e41d26aa.png)

![simple-datatables-5error-2](https://user-images.githubusercontent.com/14017600/143971368-c9c4e6ad-7980-43be-860b-1e8d627922b1.png)

**Comment by johanneswilm** [comment]
Hey @dandrews4 , it is working now.
