### ISSUE TITLE
How to add custom CSS classes to pagination

### ISSUE THREAD

**Issue by coliff** [fiduswriter/simple-datatables#151]
I'd like to use Simple-DataTables with Bootstrap 5 CSS without rewriting any CSS classes. Is it possible to add CSS class names to the existing classes at run-time?

https://getbootstrap.com/docs/5.1/components/pagination/

For Bootstrap's pagination that'd mean adding the class `pagination` to `dataTable-pagination-list` and then `page-item` to each `li` and `page-link` to each `a`.

**Comment by dday9** [comment]
@coliff - your approach looks good to me. If I were implementing something like this then I'd essentially take your code and plug it into a custom plugin.

**Comment by johanneswilm** [comment]
If there is interest in it, we can make the class names configurable. This is already the case for the editing plugin.

**Comment by coliff** [comment]
> If there is interest in it, we can make the class names configurable. This is already the case for the editing plugin.

YES PLEASE! That would be awesome. The 'solution' code I posted above doesn't actually work well at all beacuse the class names are lost when the DOM is reloaded. Using custom class names configured would be very helpful.

**Comment by johanneswilm** [comment]
@coliff ok, this has now been added to simple-datatables@6.0.0-3

**Comment by dday9** [comment]
@johanneswilm  - The classes property does not seem to be overriding properly. For example, I have a Bootstrap 5 integration with this configuration that isn't working:
```
window.tableUsers = new window.simpleDatatables.DataTable(table, {
  data: {
    headings: [ 'Id', 'Email', 'FirstName', 'LastName', 'Telephone' ],
    data: records.map(record => Object.values(record)),
    classes: {
     table: 'table table-striped table-hover',
      selector: 'form-select',
      input: 'form-control'
    }
  }
});
```

Fiddle: https://jsfiddle.net/vc0azdth/
