### ISSUE TITLE
Multi-column ordering

### ISSUE THREAD

**Issue by Michuu93** [fiduswriter/simple-datatables#152]
Is there any chance to implement multi-column sort?
https://datatables.net/examples/basic_init/multi_col_sort.html

**Comment by Errel2022** [comment]
You can do this - more or less - with this dirty trick:
combine the relevant data into 1 column and sort on that column (eg name + number).
By using <span style='display:none'></span> around the portions of the combined data you can decide what to show and what not (eg name<span style='display:none'>number/span>)

**Comment by johanneswilm** [comment]
Hey @Michuu93 ,
sure we can accept a PR for that - or someone can pay me to write the code for that.
