### ISSUE TITLE
I'm not able to refresh the datatable dynamically

### ISSUE THREAD

**Issue by shreyas-ananth** [fiduswriter/simple-datatables#158]
Hi.. I 'm using https://vuero.cssninja.io/ simpledatatables, which uses DataTables in the framework. 
Please help me how to add dynamic data for a table and how to refresh the table once it gets the new data automatically. 

I'm getting below error when I try to use : 
import { DataTable } from 'simple-datatables';
const myTable = document.querySelector('#dataTable');
const dataTable = new DataTable(myTable);

TypeError: Cannot read properties of null (reading 'innerHTML')
    at new DataTable (datatable.js:37)
    at setup (rfqList.vue:108)
    at callWithErrorHandling (runtime-core.esm-bundler.js:154)
    at setupStatefulComponent (runtime-core.esm-bundler.js:6542)
    at setupComponent (runtime-core.esm-bundler.js:6503)
    at mountComponent (runtime-core.esm-bundler.js:4206)
    at processComponent (runtime-core.esm-bundler.js:4182)
    at patch (runtime-core.esm-bundler.js:3791)
    at mountChildren (runtime-core.esm-bundler.js:3975)
    at mountElement (runtime-core.esm-bundler.js:3896)

**Comment by hamiltomamede** [comment]
I having the same issue. The table is build using just the initial state.
`const ref = useRef(null)

    const [columnData, setColumns] = useState(columns)

    useEffect(() => {
        const myTable = ref.current
        setColumns(columns)
        const labelData = {
            placeholder: "Buscar...",
            perPage: "Mostre {select} itens por página",
            noRows: "Sem itens para exibir",
            info: "Mostranto {start} a {end} de {rows} itens (Página {page} de {pages} páginas)"
        }
        const datatable = new DataTable(myTable, {
            data: {
                headings: Object.keys(columnData[0]),
                data: columnData.map(item => Object.values(item))
            },
            labels: labelData
        })
        datatable.refresh()
    }, [columns]);`

**Comment by johanneswilm** [comment]
Version 6.0.0 is almost a complete rewrite. Please take a look @hamiltomamede @shreyas-ananth and reopen this issue if it still is an issue.
