### ISSUE TITLE
'Dynamic' (json) data not dynamic

### ISSUE THREAD

**Issue by dmidthun** [fiduswriter/simple-datatables#160]
Having an issue where data is not being dynamically inserted into the table. Including snippet of where code is not working as expected.

```
$("#datatablesBlog").on("click", "tbody tr", function() {
        var modal = $(this).data("target");
        var table = $(modal).find("#datatablesBlogComments")[0];
        var datatable = new simpleDatatables.DataTable(table, {});



        $.ajax({
            url: "include/blogcomments.php",
            dataType: "json",
            type: 'GET',
            data: "q=" + $(this)[0].children[0].data,

            success: function(data) {
                datatable.insert(data);    // <<< inserts correct data on load, but does not update table rows on subsequent call from above ( though a page refresh will get 'fresh' data  from ajax call )
                datatable.columns().hide([0, 1]);
            },
            error: function(xhr, ajaxOptions, thrownError) {
                alert(xhr.status);
                alert(thrownError);
            }
        });
```

Any help with this would be absolutely appreciated 

Dan

**Comment by johanneswilm** [comment]
Hey @dmidthun ,
first of all, it looks like you are using jQuery and the coding syntax from before ES2015. That should generally be possible, but it will probably make life harder for you. Have you considered using the jQuery-based datatables module instead? Alternatively, switch to the post-2015 syntax?

As for your bug - it looks like you are resetting the datatable every time someone clicks on `#datatablesBlog` in a way that is not supported. Is that what you meant to do?

**Comment by dmidthun** [comment]
Johannes.
  It was not intended - I have edited the post to reflect the current code that I have and still doesnt change the outcome.
  As far as using the jquery-based module, are you referring to datatables.net?

Please advise,
  Thank you

**Comment by johanneswilm** [comment]
@dmidthun Yes, I was thinking of midthun.

It still looks like you are reinitializing the entire table as part of the click event handler. Do you have your full code somewhere to inspect?
