### ISSUE TITLE
column data type

### ISSUE THREAD

**Issue by KovaMWanted** [fiduswriter/simple-datatables#163]
Hello, can sombody tell me how to make my column that shows money values to separate thousands and appear with  a . or , ???
I'm a noob, to this type a stuff.

Thanks

**Comment by jmbodnar** [comment]
You question doesn't seem to be about Simple DataTables but about formatting currency display. You might want to look at the [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat) API for formatting your display values.

**Comment by johanneswilm** [comment]
Hey @KovaMWanted ,
not sure if this helps, but take a look at the `render` method for columns in the wiki.
