### ISSUE TITLE
type and format have no effect

### ISSUE THREAD

**Issue by scudderk** [fiduswriter/simple-datatables#165]
## Issue
Adding `type: 'date', format: 'MMM DD, YY'` or any other date format (`DD/MM/YYYY`, `MM/DD/YYYY` etc) have no effect on the format for date displayed.

### index.js
```
const table = new DataTable('#table', {
  columns: [
	  { select: 0, type: 'date', format: 'MMM DD, YY' },
	  { select: [1, 2, 3, 4, 5, 6, 7, 8], sortable: false }
  ],
  labels: {
	  noRows: 'No data available in table'
  },
  onChange: () => {
	  myFunction()
  }
})
``` 
### index.cshtml
```
<thead>
  <tr>
    <th>
      Date/Time
    </th>
    <th>...
  </tr>
</thead>
<tbody>
  <tr>
    <td>
      12/30/2022
    </td>
    <td>...
  </tr>
</tbody>

```

### Alternatives

I have also tried using the `data-type='date' data-format='MMM DD, YY'` attributes and this also has no effect.

The end result is always printed in the way it is written in the table:

![image](https://user-images.githubusercontent.com/28690606/155524679-78f8aaad-d229-4bfb-8630-6131ff627a95.png)

Any help is appreciated.

**Comment by johanneswilm** [comment]
Hey @scudderk, please confirm whether that still is the case with version 6.0.0-2 and reopen this issue in case it is. I just wrote most fo the code and it seems to be working now.
