### ISSUE TITLE
Multiple keyword search 

### ISSUE THREAD

**Issue by shaunroselt** [fiduswriter/simple-datatables#166]
Is there a way to search for two keywords within a row?

I only want a row to appear when both keywords exist somewhere in the row.

**Comment by shaunroselt** [comment]
Basically, I want to do a search on a search.

First search for "Apple", then search again on the new table that contains "Apple", but search for "Orange".

So two searches on one table.

**Comment by nsheff** [comment]
Doesn't this work if you just type both keywords into the search box, separated by a space?

**Comment by johanneswilm** [comment]
You will like want to copy the code for the search function and then modify it to do what you want.
