### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by Honatas** [fiduswriter/simple-datatables#167]
I've created type definitions for this lib. Just added a PR to DefinitelyTyped:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59094

If you guys have anything to add or could help with testing, it would be nice. Otherwise, you can close this ticket.

Edit: the guys at DefinitelyTyped are quite fast, the PR has been merged already and @types/simple-datatables is live.

**Comment by johanneswilm** [comment]
Hey @Honatas Thanks a lot. 

I just translated the entire library into TS so that I wouldn't have to keep up with maintaining definitions. However - there is still quite a lot that can be done to improve it. Take a look at #212.
