### ISSUE TITLE
Add an option to retain Next and Previous buttons when on first and last pages

### ISSUE THREAD

**Issue by sassquad** [fiduswriter/simple-datatables#168]
The current pagination automatically removes the Next and Previous buttons when you are **on** the first **or** last page. Any pages inbetween will then display the buttons.

From a UX perspective, it may be desirable for the Next and Previous buttons to enter a 'disabled' state, rather than disappear. This doesn't appear to be possible, judging by the conditional applied at lines [439](https://github.com/fiduswriter/Simple-DataTables/blob/main/src/datatable.js#L439) and [469](https://github.com/fiduswriter/Simple-DataTables/blob/main/src/datatable.js#L469) of [src/datatables.js](https://github.com/fiduswriter/Simple-DataTables/blob/main/src/datatable.js).

Can an option be added so you can choose between the current behaviour, and the disabled appearance of these buttons?

Thanks in advance.

**Comment by johanneswilm** [comment]
Yes, please provide a PR to add this behavior as an option!

**Comment by sassquad** [comment]
Sorry to re-open this @johanneswilm - can you confirm as to whether this functionality has been added, or is it awaiting the functionality to added via a PR? I've also realised the links in my original comment are now out of date.

Your comment suggests one thing, but Github's messaging of how it has been closed suggests another, so I'm confused!

**Comment by johanneswilm** [comment]
Hey @sassquad ,
as far as I can see, github only allows me to "close as completed" or "close as not planned". The default is "as completed". So no, the feature is not there, but you are welcome to provide a PR for it and I will merge if I get one.

**Comment by sassquad** [comment]
Many thanks for confirming!

**Comment by johanneswilm** [comment]
@sassquad  In version 7.0.0.rc-0, the next/previous buttons are always there and only hidden using CSS. So with other CSS you can make them show up again.
