### ISSUE TITLE
Restrict search to certain table columns

### ISSUE THREAD

**Issue by nsheff** [fiduswriter/Simple-DataTables#169]
I have a table with a few invariant columns holding action buttons. I'd like the search to ignore these columns, because they don't provide any row specificity. Is it possible to restrict the search to certain columns, or tell it to ignore certain columns?

**Comment by oliphil** [comment]
I also need to apply the search only to specific columns.  I'm very interested to know if you found a solution.

**Comment by stefanwillig** [comment]
is there any update to this yet?
just had the same problem to restrict the search to a certain column and could not find a way to do it.

**Comment by stefanwillig** [comment]
thanks a lot for your quick reply. That helps me, problem just solved ;)
