### ISSUE TITLE
Compatibility with TypeScript

### ISSUE THREAD

**Issue by AlexTeixeira** [fiduswriter/Simple-DataTables#17]
This like vanillajs-datatable is compatible with pure TypeScript ?

Currently when I try to import the plugin : 

`import {DataTable} from 'simple-datatables';`

I get 

> Cannot find module 'simple-datatables'.ts(2307)

**Comment by AlexTeixeira** [comment]
Sorry, All ok. The issue was from my side :'(

**Comment by pholly** [comment]
No typings found for me. I'm working on a vue 3 project.
