### ISSUE TITLE
Specify specific content from json

### ISSUE THREAD

**Issue by PeterPilley** [fiduswriter/Simple-DataTables#171]
Hi firstly just want to say thanks for making this available it has been a difficult search to find a datatables library that doesnt require jquery.

My question is around the data and columns parameters when initializing a table.

I am creating my datatable like this 

`let dataTable = new DataTable(sTable, {
        data: {
          headings: Object.keys(data[0]),
          data: data.map(item => Object.values(item))
        })`

What I am wanting to do is instead of reading the keys directly from the json file to specify headings such as
`headings: ['heading1','heading2','heading3']`

and then in use the columns parameter to render specific data from the json to those headings.

ie render for heading1 => value1[0].subvalue1 
`{
"value1":
        [
            {
                "subvalue1": 0,
                "subvalue2": 1,
                "subvalue3": 2,
                "subvalue4": 3,
                "subvalue5": 4,
                "subvalue6": 5
            }
        ],
"value2": "testing",
"value3": "testingagain
}`

Any advice on if this is possible would be awesome. I was hoping to achieve this in the initialise but I am geussing I need to manually add columns.

**Comment by PeterPilley** [comment]
I ended up just using insert to add the correct rows. Doing this I can see there are some render issues which look like have already been raised.

**Comment by Skyrione** [comment]
how did you do this ? thanks!

**Comment by PeterPilley** [comment]
> how did you do this ? thanks!

Do which, add the data in?
