### ISSUE TITLE
Column Manipulation > Example is giving error on console

### ISSUE THREAD

**Issue by Meerkap** [fiduswriter/simple-datatables#172]
- So I just opened the console and is showing error: [ HERE ](https://fiduswriter.github.io/Simple-DataTables/5-column-manipulation/)

`umd.js:8 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'setAttribute')
    at umd.js:8:16641
    at Array.forEach (<anonymous>)
    at umd.js:8:16593
    at Array.forEach (<anonymous>)
    at o.setColumns (umd.js:8:16342)
    at o.insert (umd.js:8:21834)
    at h.add (umd.js:8:3308)
    at (index):76:31`

**Comment by johanneswilm** [comment]
Hey @Meerkap, please confirm whether that still is the case with version 6.0.0-2 and reopen this issue in case it is.
