### ISSUE TITLE
Render table in webworker or other thread which not blocking UI 

### ISSUE THREAD

**Issue by evanNyew** [fiduswriter/simple-datatables#173]
Hi. Across the internet, we found out simple-DataTables is really powerful and convenient. We are actively using it in public education context. Due to the large amount of date, we are now seeking the way to prerender and cache the HTML table. Is there any way to build the datatable and get back a html string or a data table instances which able to load it in others dom. the point being is run the "new DataTable" outside the live DOM without blocking the UI

**Comment by johanneswilm** [comment]
Hey @evanNyew ,
in version 6.0.0 we are using a dom diffing library so that most of the calculations are happening outside of the DOM. Please take a look at the latest version and let me know if there is anywhere there that you would see webworkers being helpful.
