### ISSUE TITLE
[DOC] Missing doc about column sortable and cell content

### ISSUE THREAD

**Issue by Cartman34** [fiduswriter/simple-datatables#176]
Hello,
I looked in the documentation about disabling sorting for a specific documentation with no success. Same about defining cell content by another way than using the cell inner text.
I finally found it in the code, this is available but no one can know because documentation is not mentioning it.

I don't understand how documentation is organized and I don't know what I could suggest to edit through a pull request.
So, I am suggesting changes here, we need more documentation about column disabling and cell content.

If this is actually in documentation and I didn't see it, sorry, I searched and if I did not find it, many others won't find it too.

So, now, How to...

### Disable sorting for a specific column

It could be used for field that is a non-sense to sort, as action buttons or pictures.
On your column header (`<TH>` tag), add attribute `data-sortable="false"`

### Set content value to use instead of text content

Very useful to use instead of a date or displayed image, while the content is formatted and the parser won't get a useful data from this.
On your cell (`<TD>` tag), add attribute `data-content="VALUE"`

**Comment by johanneswilm** [comment]
Hey @Cartman34 , I have updated a lot of the documentation, and you can now also take a look at the type definitions for version 6.0.0. They should say quite a bit.
