### ISSUE TITLE
Names changed on elements and do not match dataTables.net names

### ISSUE THREAD

**Issue by burdittw** [fiduswriter/simple-datatables#177]
Because all the names of the table styles and id's have been changed it takes a great amount of effort to get things back the way they worked in datatables.net. Would like to see names changed back so that other addons like styles can be used like bootstrap4 and bootstrap4 styling libraries. Even the layout was changed making it even harder to use with old code. 
I like what I saw as a whole but with all the changes I spent about a week trying to figure it all out just to finally give up on it because it is just so much work for just one table to be added. I would love to see this project mature and reach a level of datatables.net which it claims to be a non-jQuery version of, but it is far behind.

**Comment by johanneswilm** [comment]
Hey @burdittw ,
you are welcome to submit a PR.
