### ISSUE TITLE
Provide a way to filter rows on a custom condition

### ISSUE THREAD

**Issue by mrdziuban** [fiduswriter/simple-datatables#18]
Thanks for this library! So far I've found it easy to work with and wire up, but I had one request -- is it possible to filter rows based on custom conditions before rendering? For example, I'd like to provide a dropdown that filters rows based on a single column, and I want to combine that logic with the existing text search logic. So far this is the closest I've gotten:

```js
const origPaginate = DataTable.prototype.paginate;
DataTable.prototype.paginate = function() {
  const allRows = this.data.slice();
  const filterVal = document.querySelector("#my-dropdown").value;
  this.activeRows = allRows.filter(row => row.getAttribute("data-value") === filterVal);
  origPaginate.call(this);
};
```

but it doesn't combine well with the text search. Is this possible as the library currently exists, and if not, is it something you would consider adding?

**Comment by minskmaz** [comment]
crickets...

**Comment by minskmaz** [comment]
This seems like a good place to start. https://github.com/fiduswriter/Simple-DataTables/blob/master/src/rows.js#L20

**Comment by johanneswilm** [comment]
@mrdziuban Yes, please provide a patch. This seems generally useful.

**Comment by vicbiz** [comment]
@mrdziuban Do you know if I can do multiple keyword filter?

**Comment by ghing** [comment]
This is how I approached this problem: https://gist.github.com/ghing/4c005d8588f348e04a8c13ec70f507c3. I decided to use a setter method to set the filtering function so that I wouldn't have to modify the sections of the code that handle wiring up the search input event handlers.

**Comment by johanneswilm** [comment]
Please reopen if anyone wants to write a general plugin for this.
