### ISSUE TITLE
Pass in the render function as string

### ISSUE THREAD

**Issue by Lvc4** [fiduswriter/Simple-DataTables#182]
I need to pass the render function in columns as a string because i send the dictionary from python like:
columns = [
	{
	"select":  0, "type":"date", "format":"DD.MM.YY hh.mm"},
	{"select": 2, "render":"""function(data, cell, row) {
	      console.log("test");
              return data + "<button type='button' data-row='"  + row.dataIndex + "'>Select</button>";}
		"""
	}
]

but it does not get executed.
Is there any way this could work?

**Comment by uaktags** [comment]
Why would you pass the javascript function as a literal string and want it to get executed as a callback?

https://github.com/fiduswriter/Simple-DataTables/wiki/columns

**Comment by Lvc4** [comment]
As i said i have the collumns variable as a Python variable and then dynamically render it into JavaScript as JSON.
And there I can only save the JavaScript function as a string

**Comment by johanneswilm** [comment]
@Lvc4 I don't get it either. If you want to convert it into JavaScript using `eval()`, why don't you just do that in your own JS connector code that is receiving the response from the Python server? Why is there a need to add code to Simple+DataTables?

**Comment by Lvc4** [comment]
The point is that there is not a Python server communicating with some JavaScript via queries to load this.
Do you know flask or Django?
I render the Python dictionary into the html template via jinja2

**Comment by johanneswilm** [comment]
@Lvc4 Just run something like this in JavaScript after receiving the columns value from the sevrer and before feeding it into Simple-DataTables:

```js
columns.forEach(column => {
    if (column.render) {
        column.render = eval(column.render)
    }
})
```

**Comment by Lvc4** [comment]
Thanks a lot

**Comment by johanneswilm** [comment]
@Lvc4 Yes, if you look at the main fiduswriter repo you will discover it is Django. 

No rpoblem!
