### ISSUE TITLE
Angular - *ngFor dont' working

### ISSUE THREAD

**Issue by karendunkl** [fiduswriter/Simple-DataTables#184]
Hello,

I'm using Angular and when I use ngFor from <tr> tag the inputs don't work.
`  <tbody>
                           <tr *ngFor="let item of observacoes">
                              <td scope="row">{{ usuario.nome }}</td>   
                              <td>{{ item.dataObservacao }}</td>
                              <td>{{ item.observacao }}</td>
                           </tr>
                        </tbody>`
But if I put it in the tbody tag, they work normally, but then I can't use the filters.

Can anyone help me with this question?

Thank you in advance.

**Comment by wabudd1** [comment]
I've not tested it in Angular yet (soon), but I've encountered similar issues with jQuery DataTables.  I ended up using this pattern:

```
<tbody>
  <ng-container *ngFor="let item of collection">
    <tr>
      <td>{{ item.property }} </td>
    </tr>
  </ng-container>
</tbody>
```

Give that a try and see what happens.  If that doesn't work, I'd be down to further troubleshoot it.  I'm going to be using this library in my Angular project soon (a few months really) and I'll need the filters to work.  Alternatively, if you're pinch, you could try another project I've used in the past [Angular-Datatables](https://l-lin.github.io/angular-datatables).  It's a bit larger than Simple-DataTables, but I have used it and it works fairly well.

**Comment by karendunkl** [comment]
I managed to find the reason for the problem.
It's page loading. I put the "setTimeout" to delay the loading of the table and it worked.

Thank you very much for your attention.
