### ISSUE TITLE
setMessage() uses wrong colspan

### ISSUE THREAD

**Issue by m-blank** [fiduswriter/Simple-DataTables#185]
Hello!

I've come across a problem in one of my tables where the `setMessage()` function - either used manally or triggered by emptying the table - is creating a message cell with the wrong `colspan` attribute. This is because the code is only counting the number of cells in the first row of the table, without accounting for possible `colspan` attributes of the specific cells.

If a table row contains 3 cells, with one of them having a `colspan` of 2, the resulting message cell created in the `setMessage()` function needs to have a `colspan` value of 4, not 3.

This is the code in question:
https://github.com/fiduswriter/Simple-DataTables/blob/58c3cc290af219e922b3ad47a784814dcdb7052b/src/datatable.js#L1446-L1452

I've created a demonstration of this issue on CodePen:
https://codepen.io/m-blank/pen/XWYpeyd

**Comment by m-blank** [comment]
One way to solve this would be to loop over the relevant cells (either `this.data[0].cells` or `this.activeHeadings`) and calculating the sum of all `colspan` attributes (defaulting to 1 if not present).

```js
let colspan_cells = [];
let colspan = 1;

if (this.hasRows) {
    colspan_cells = this.data[0].cells;
} else if (this.activeHeadings.length) {
    colspan_cells = this.activeHeadings;
}

if (colspan_cells && colspan_cells.length) {
    // add up the number of cells while accounting for colspan
    colspan = [...colspan_cells].reduce(function(sum, cell) {
        sum+= (+cell.getAttribute('colspan') || 1);
        return sum;		
    }, 0));
}
```

**Comment by johanneswilm** [comment]
Hey @m-blank ,
yes, I guess the idea with how that was done is that you are not using colspan in the original table. The original table is just like a simple spreadsheet with one row per data entry and one entry per cell. The styling, etc. is then something that comes later on, once datatable has been applied.

**Comment by m-blank** [comment]
I unterstand what you mean. I'm a big fan of how lightweight and simple this DataTable library is, however I wish the colspan behaviour was handled better. 

Only if you think it doesn't violate the "simplicity mantra", of course, but in my humble opinion this would be fine.

**Comment by johanneswilm** [comment]
@m-blank Yeah, I'm trying to think of how to handle this the best possible way. The problem is also that if you start using colspan on some headers, how should it then use features like column selection? The column selector allows you to hide entire columns of data. If the user hides a column of which the header contains a colspan, should it then remove the colspan-attribute?

**Comment by johanneswilm** [comment]
Please reopen if you can come up with a suggestion.
