### ISSUE TITLE
exports csv with utf8

### ISSUE THREAD

**Issue by dirosv-eden** [fiduswriter/simple-datatables#197]
i try to export to csv follow documentation but i have a problem about the text encodeing like this "เนเธขเธเธฒเธงเธเธฉเน".

this code 
```
datatable.export({
    type: "csv",
    filename: "my-csv-file"
})
```

**Comment by johanneswilm** [comment]
Hey @dirosv-eden, please confirm whether that still is the case with version 6.0.0-2 and reopen this issue in case it is.
