### ISSUE TITLE
Search for specific columns

### ISSUE THREAD

**Issue by rizkibatam** [fiduswriter/simple-datatables#198]
how to integrate select option with input search field, select option contains column integrated with search ? as follows

![image](https://user-images.githubusercontent.com/19259151/206457240-ebe6de5f-f57c-494b-b173-575e8973ad7e.png)

when the select option is selected, the search will only match the data in that column

![image](https://user-images.githubusercontent.com/19259151/206457967-4a82294d-8b8d-492f-88c1-7c3a104519fb.png)

Sorry for bad english, hope you can help

**Comment by rizkibatam** [comment]
@johanneswilm @Mobius1 @deakjahn please help

**Comment by johanneswilm** [comment]
@rizkibatam Take a look at the API documentation and the search functionality there. That should be enough information for a JS developer to get it to work.
