### ISSUE TITLE
Always show "next" and "previous" pagination buttons

### ISSUE THREAD

**Issue by nCrazed** [fiduswriter/simple-datatables#199]
I am in the process of migrating away from the jQuery DataTables plugin and one of the behaviors that I'd like to preserve is that the "next" and "previous" buttons are present even when displaying the first and last pages respectively. This is needed to prevent the navigation from jumping around when the buttons are added and removed.

I think the simplest solution would be to change the `DataTableOptions.nextPrev` type from `boolean` to an enum containing some variation of these 3 options:

1. `Auto`
2. `Always`
3. `No`

If the above solution is acceptable, or anyone makes a better suggestion, I'm happy to work on the PR.

**Comment by supyrow** [comment]
if you want to do it quick and dirty edit `datatables.js`
 
            // prev button
            if (this.options.nextPrev && !this.onFirstPage) {
                frag.appendChild(button(c, prev, this.options.prevText))
            }

change to

            // prev button
            if (this.options.nextPrev) {
                frag.appendChild(button(c, prev, this.options.prevText))
            }

and 

            // next button
            if (this.options.nextPrev && !this.onLastPage) {
                frag.appendChild(button(c, next, this.options.nextText))
            }

change to 
            
           // next button
            if (this.options.nextPrev) {
                frag.appendChild(button(c, next, this.options.nextText))
            }

**Comment by johanneswilm** [comment]
I would not be opposed to options for that. Please submit a PR.

**Comment by johanneswilm** [comment]
@nCrazed In version 7.0.0.rc-0, the next/previous buttons are always there and only hidden using CSS. So with other CSS you can make them show up again.

**Comment by nCrazed** [comment]
> @nCrazed In version 7.0.0.rc-0, the next/previous buttons are always there and only hidden using CSS. So with other CSS you can make them show up again.

Good to know, thanks!

I'm a bit too busy these days, but should have some time in February to throw in a PR. If no one else picks it up before then ofc

**Comment by johanneswilm** [comment]
A PR is no longer needed, @nCrazed
