### ISSUE TITLE
Using Columns.render() method to trigger element's click event in VueJS

### ISSUE THREAD

**Issue by epb984** [fiduswriter/simple-datatables#201]
I'm not sure, result from this method always in string or plaintext form out of the Vue lifecycle flow. 
it doesn't automatically generate event triggers based on @click="" rules

![image](https://user-images.githubusercontent.com/32030718/207845913-cbf4b19b-23ba-414f-b812-269559af6783.png)

code:
![image](https://user-images.githubusercontent.com/32030718/207846161-670716cf-590a-443d-9cc4-f1d92a1593d0.png)

HTML Element Result:
![image](https://user-images.githubusercontent.com/32030718/207846394-321a32d5-e292-4470-a8ec-d93c6dfa0931.png)

**Comment by johanneswilm** [comment]
Hey @epb984 please confirm whether that still is the case with version 6.0.0-2 and reopen this issue in case it is.
