### ISSUE TITLE
columns.render changed parameters from 3.2.2 to 4.0.8 for data, cell and row?

### ISSUE THREAD

**Issue by noehmeier** [fiduswriter/simple-datatables#202]
Hi there,
i am using Smple-DataTables in a project (with TypeScript) with version `3.2.2`, where i use a similar code like in your example https://fiduswriter.github.io/Simple-DataTables/13-hide-column/, to hide the first column with the `id`, which i want to place instead of the `<td>` to the `<tr>`.

So the part in the DataTable options looks like this:

```javascript
[...]
columns: [
    {
        select: 0,
        hidden: true,
        render: (data: any, cell: any, row: { dataset: { id: any; }; }) => {
            row.dataset.id = data; // Will add data to row instead.
            return data; // Will not be shown as column is hidden.
        }
    }
],
[...]
```

That worked fine for me with version `3.2.2`, with `4.0.8` i get the following error:

> TS2322: Type '(data: any, cell: any, row: { dataset: { id: any; };}) => any' is not assignable to type '(callback: render) => any'.  index.d.ts(203, 9): The expected type comes from property 'render' which is declared here on type 'ColumnOption'

I am not an TypeScript professional, but for me it looks like that the three parameters for `data`, `cell` and `row` are now reduced to an single callback-parameter with the type of `ColumnOption`. 

```javascript
[...]
columns: [
    {
        select: 0,
        hidden: true,
        render: (co: ColumnOption) => {
            console.log(co);
            return null;
        },
    },
], 
[...]
```
I have no access to a type called `ColumnOption`, so it also does not work.

If i pass it as wished with one parameter, like:

```javascript
[...]
render: function(data : any) {
    console.log(data);
    return null;
}
[...]
```
i get the value of the `id`, so i guess it is the `data` parameter. The [documentation](https://github.com/fiduswriter/Simple-DataTables/wiki/columns#render) says, there should be also allowed three parameters and not just one. Is that a typescript problem or sth in generel i just do not understand?

Has anyone an idea, what i have to do to get the value of the hidden first row to the table row dataset id like in the first code example analogical to your demo code in the related link above?

Thank you very much in advance!

**Comment by johanneswilm** [comment]
Hey @noehmeier,
the code you see in https://fiduswriter.github.io/Simple-DataTables/13-hide-column/ with the three parameters is running using the current version of Simple-DataTables, so at least there is no change AFAICT. It's possible that there is an issue with the typescript bindings though. I can investigate within the next few days.

**Comment by noehmeier** [comment]
Hi @johanneswilm,
did you already have time to to investigate if it has do with the typescript bindings? :-)

**Comment by johanneswilm** [comment]
@noehmeier I am looking at it now. But I'm not a typescript expert.

**Comment by johanneswilm** [comment]
@noehmeier Would it be possible for you to create a minimal demo in typescript? I think it would be good to have that among our tests anyway.

As for the bindings - I can see that those lines have not been touched since November 21, 2021 [1]. The version at that stage was 3.1.2. So I don't think that could be the cause for your code not working after version 3.2.2.


[1] https://github.com/fiduswriter/Simple-DataTables/blame/82058938c9320e03d628b2ce7b5d25206ad48d77/index.d.ts#L202

**Comment by johanneswilm** [comment]
@noehmeier Please take a look at the current code. I have tried to solve a lot of the problems with previous versions and mostly transformed the code to TypeScript. We should have a version 6.0.0 shortly.
