### ISSUE TITLE
Sorting negative numbers

### ISSUE THREAD

**Issue by uythoang** [fiduswriter/Simple-DataTables#205]
My column is sorting in ascending order and it's putting negative numbers before positive. However, when it's comparing negative numbers it's not doing it correctly.

<img width="141" alt="image" src="https://user-images.githubusercontent.com/16453501/209574035-7cb71df4-59f5-4e2b-9483-07ab9e160fff.png">

**Comment by uythoang** [comment]
I think because I added "days", it turned this column into strings which messed up the sorting of negative numbers.

**Comment by johanneswilm** [comment]
I understand. We probably need to distinguish between data and presentation in a future release.
