### ISSUE TITLE
import is not a function

### ISSUE THREAD

**Issue by marcoas** [fiduswriter/simple-datatables#207]
(Translated by Google)

Hello

Does the IMPORT method no longer exist?
I need to load from a JSON sent by AJAX, the entire table structure, Headers and Rows

**Comment by johanneswilm** [comment]
@marcoas hi,
have you looked at the demos? Several of those import the data via Ajax, etc. in different ways. 

Which version were you using previously?

**Comment by marcoas** [comment]
Loading from CDN

<script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" type="text/javascript"></script>


My JS

>       var dataTable = new simpleDatatables.DataTable("#main TABLE" , {
>                                 fixedHeight: true,
>                                 paging: false,
>                                 searchable: false,
>                             });
>       
>       ...
>       
>       dataTable.import({
>             type: 'json',
>             data: json
>         });
> 

        
The Error
`Uncaught (in promise) TypeError: dataTable.import is not a function`

**Comment by johanneswilm** [comment]
Yes @marcoas Take a look at the upgrade document. It's all documented there: https://github.com/fiduswriter/simple-datatables/wiki/Upgrading

**Comment by johanneswilm** [comment]
btw - not specifying the major version is probably dangerous. There will be more breaking changes in the future in version 6, 7 , etc. .

**Comment by johanneswilm** [comment]
@marcoas Thanks. The documentation has been updated. Take a look at the examples in the docs directory. They are more up to date.

**Comment by johanneswilm** [comment]
The was closed already. Which example are you referring to?

**Comment by marcoas** [comment]
You told me that 

> "not specifying the major version is probably dangerous"

 but from the READ.ME file I took the line: 
`<script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" type="text/javascript"></script>`
