### ISSUE TITLE
Unable to clear table

### ISSUE THREAD

**Issue by jotsys** [fiduswriter/simple-datatables#21]
Hi, I'm trying to refresh datatable with new data, It appends new data to the current data and does not clear before I import.  data_ is an object!
I looked inside the code and could not find any truncate method besides clear()

```
this.datatable.clear();
this.datatable.import({
	headings: true,
	data: data_
});
```

**Comment by jotsys** [comment]
I had to add this line in order for it to clear contents in the data property.
Works fine now!

**this.datatable.data = [];**
```
this.datatable.clear();
this.datatable.data = [];
this.datatable.import({
	headings: true,
	data: data_
});
```

**Comment by mtangoo** [comment]
I think add clear method will make things better. Else that solves it!

**Comment by johanneswilm** [comment]
I didn't write this, but it looks like the clear method is internal and not documented. It's being used by search, etc.. So it's not meant for deleting everything in the table. Do we need a method that does that?

**Comment by jotsys** [comment]
I was able to user this.datatable.clear();
and it did work well

**Comment by mtangoo** [comment]
>Do we need a method that does that?

Definitely! For example I have Vuejs Component that is reactive to data changes. I want to be able to do two things:
1. Clear table and reload with data
2. replace single data when it changes

So since we have method to remove, and then insert, we  need clear kind of method for (1)

**Comment by johanneswilm** [comment]
Hey @jotsys, in version 6 you can simply do:

```js
table.data.data = []
table.renderTable()
```

And that should do it.

**Comment by Gonen09** [comment]
i use this.data.data = []; to clear the data table and here an example how to update 
file: datatable-module.js
import { DataTable } from './module.js'

function crearDataTableControlHorarioConsultaMedica(table, tableData, isSearchable = true, itemsPerPage = 15) {

    const data = {
        headings: ['Cod. Profesional', 'Profesional', 'F. Agenda', 'Hora', 'Categoría', 'Prestación', 'Paciente', 'Rut', 'Fecha Nac.', 'Servicio', 'Subtitulo'],
        data: tableData.map((item, index) => {

            return [
                item.codigoPrimerCirujano,
                item.primerCirujano,
                obtenerFecha(item.fechaIntervencion),
                obtenerHoraMinutos(item.fechaIntervencion),
                item.especialidad,
                item.codIqDescripcion,
                item.nombrePaciente,
                formatearRut(`${item.rut}-${item.dv}`),
                `${obtenerFecha(item.fechaNacimiento)}`,
                item.servicio,
                item.tipoSubtitulo
            ];
        })
    }

    const datatable = new DataTable(table, {
        searchable: isSearchable,
        perPage: itemsPerPage,
        perPageSelect: perPageSelect,
        type: "string",
        classes: classes,
        labels: labels,
        data: data,
        columns: []
    });

    // Método interno para actualizar los datos
    datatable.updateData = function (newData) {
        // Vaciar los datos actuales
        this.data.data = [];

        // Insertar nuevos datos
        let newRows = newData.map((item) => [
            item.codigoPrimerCirujano,
            item.primerCirujano,
            obtenerFecha(item.fechaIntervencion),
            obtenerHoraMinutos(item.fechaIntervencion),
            item.especialidad,
            item.codIqDescripcion,
            item.nombrePaciente,
            `${item.rut}-${item.dv}`,
            `${obtenerFecha(item.fechaNacimiento)}`,
            item.servicio,
            item.tipoSubtitulo
        ]);

        this.insert({ data: newRows });
    };

    return datatable;
}

export {
    crearDataTableControlHorarioConsultaMedica

}

html file

 <script type="module">

     import { crearDataTableControlHorarioConsultaMedica } from '../js/datatables/datatable-module.js';
     
                     if (!window.dt) {
                        window.dt = crearDataTableControlHorarioConsultaMedica("#tblCruceProtocolos", protocolos);
                    } else {
                        window.dt.updateData(protocolos);
                    }
     
 </script>
