### ISSUE TITLE
The latest updates seems to have broken the CSS for me.

### ISSUE THREAD

**Issue by rbulcher** [fiduswriter/simple-datatables#213]
Here is an example site: [Live Demo](https://startbootstrap.com/template/sb-admin)
It shows a screenshot of what should be produced then running the live demo is now what is being produced in the data table. All the formatting seems to be broken.

**Comment by johanneswilm** [comment]
Hey @rbulcher ,
I see that on https://startbootstrap.github.io/startbootstrap-sb-admin/tables.html you are linking to  https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css . That's a bit dangerous as it means you are always automatically upgrading to the latest version - apparently even pre-releases. It would be good if you could lock it down to at least the major version you are using (for example "5.x.x").

On that page I also see that you are linking to the documentation of datatables.net in your disclaimer [1]. Note that datatables.net is not the same as the simple-datables package that you are using. Datatables.net is a jQuery plugin.

[1] "DataTables is a third party plugin that is used to generate the demo table below. For more information about DataTables, please visit the [official DataTables documentation](https://datatables.net/) ."

**Comment by rbulcher** [comment]
Thanks for the quick response. I need to update a few things, get off the latest release like you recommend, but also changing all of my CSS selectors from "dataTable" to "datatable" ... like your upgrade guide suggests fixed all my issues. So I want to thank you for that. Also thanks for all the other information, I appreciate it.

**Comment by johanneswilm** [comment]
@rbulcher 
> but also changing all of my CSS selectors from "dataTable" to "datatable"

Yes, except that you can now also specify your custom CSS classes as of today's latest rc release. So you could just specify the old class names I haven't added that to the guide yet.
