### ISSUE TITLE
Cannot read properties of undefined (reading 'order')

### ISSUE THREAD

**Issue by uythoang** [fiduswriter/simple-datatables#214]
When using 6.0.0, I'm getting this error when loading a datatable:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'order')
    at simple-datatables.js:3:44246
    at Array.sort (<anonymous>)
    at t.sort (simple-datatables.js:3:44215)
    at t.render (simple-datatables.js:3:48918)
    at t.init (simple-datatables.js:3:46662)
    at new t (simple-datatables.js:3:45851)
```

Downgrading to 5.0.3 fixes it

**Comment by johanneswilm** [comment]
Hey @uythoang ,
have you looked at the upgrade guide? https://github.com/fiduswriter/simple-datatables/wiki/Upgrading

Version 6.0.0 will be released shortly. For now it's only a release candidate.

**Comment by uythoang** [comment]
Thanks, I'll read up on that. I was using `https://cdn.jsdelivr.net/npm/simple-datatables@latest`. Does that point to 6.0.0?

**Comment by johanneswilm** [comment]
@uythoang yes, it does. use @5 to use the latest version in the 5.x.x series.
