### ISSUE TITLE
Columns render configuration ignored when using insert() and/or rows.add()

### ISSUE THREAD

**Issue by mariatamayo** [fiduswriter/Simple-DataTables#22]
The column render property seems to be ignored when using insert() and/or rows.add() to update the table data (I don't know if this is a bug or I'm just not using the option correctly). 

I have a column where I am rendering icons and I am trying to filter by column. To do that, I am first removing all rows and then inserting the filtered rows (I've used the insert() and rows.add() methods). When the new rows are inserted on the table, the icons (which are initially rendered) don't render anymore. The same thing happens if I try to insert data or rows without filtering.

**Comment by johanneswilm** [comment]
Could you provide me with a full example  (a demo app that highlights the issue)?

**Comment by maximedelpit** [comment]
@mariatamayo. Did you end up with a solution ? I have a similar issue.

I generate the following JSON data serverside.
```
data = [
 {id: 1, name: 'Edward K.', country: 'UK', city: 'London'},
 {id: 2, name: 'Henri S', country: 'France', city: 'Lyon'},
 {id: 3, name: 'Mike D', country: 'US', city: 'New York City'},
...]
```

In my js I try to :
```
const renderFunction = function(data, cell, row){
    debugger;
    return data + "<button class=\'popo\' type=\'button\' data-row=\'"  + row.dataIndex + "\'>Select</button>";
  }

this.dataTable = new DataTable(this.results_tableTarget, {columns: [  {select: 1, render: this.renderFunction}, {select: 2, hidden: true}]  });

this.dataTable.insert(JSON.parse(this.data.get("results")));
// NB:  I use JSON.parse since data sent from server is JSON

}
```

It result that column 1 is not rendered as expected (only a class `td` tag) and that column 2 is not hidden.

**Comment by maximedelpit** [comment]
Ok, I found the solution. After calling `insert` you should call `render` on dataTable

From @mariatamayo's example : 
https://jsfiddle.net/2xsbeutg/

**Comment by maximedelpit** [comment]
Please also note that the quick fix above breaks pagination

**Comment by maximedelpit** [comment]
Hi all,

After reviewing the source code, I realized  that `insert` / `add` called the `update`  function to regenerate rows. The problem is that this last function doest not call the `setColumns()`  from `datatable.js`. which is in charge of iterating over columnRenderers and format rows.

When I change the  update function as follow the rendering works (not hidden columns)
```
    update() {
        classList.remove(this.wrapper, "dataTable-empty")

        this.paginate(this)
        this.render("page")

        this.links = []

        let i = this.pages.length
        while (i--) {
            const num = i + 1
            this.links[i] = button(i === 0 ? "active" : "", num, num)
        }

        this.sorting = false

        this.render("pager")

        this.rows().update()
        this.setColumns()
        this.emit("datatable.update")
    }
```

In my app I had performance issue so I ended up calling `dataTable.setColumns()` just after `dataTable.insert(table)`

**Comment by maximedelpit** [comment]
@johanneswilm do you recommend to call `this.setColumns()` inside update ?

**Comment by johanneswilm** [comment]
@maximedelpit Thanks for investigating this and the fiddles. In my own test setup this version works: https://github.com/fiduswriter/Simple-DataTables/tree/es2018

Could you check if this works for you? If so, I'll merge it into master and make a release.

**Comment by johanneswilm** [comment]
@maximedelpit ping!

**Comment by maximedelpit** [comment]
Hi @johanneswilm,

Sorry, I have been busy and did not see your message. I'm a bit in a rush but will dive on it as soon as possible

**Comment by johanneswilm** [comment]
@maximedelpit Ok great. Hopefully you have some more time now.

**Comment by johanneswilm** [comment]
@maximedelpit Unfortunately I needed to merge this for some other bug fix but please let me know if it didn't work out and we'll reopen this issue/

**Comment by Konafets** [comment]
A bit late to the party but I have the same issue. I added a delete button on the last column via `columns` render function on creation of the table. However, when I add a new row, the button is not there. You @johanneswilm mentioned a solution, which worked for you, but the link is broken. Can you explain what I can do?
