### ISSUE TITLE
can you check this issue?

### ISSUE THREAD

**Issue by lmh5050** [fiduswriter/simple-datatables#221]
Hi!

i've been usefully use your css

but since yesterday, we can't apply the css, we don't change any other things.. 

here is the issue, can you check it?

just one page , apply the css but just the grid , paginator and search are not.

![css_not_apply](https://user-images.githubusercontent.com/94948047/212207292-b6c95bf3-9dba-4202-89c3-f68d336ec65d.png)
![image](https://user-images.githubusercontent.com/94948047/212207548-a7d7c1b2-7997-478f-9e23-04f60db19e09.png)

**Comment by johanneswilm** [comment]
Hey @lmh5050 ,
depending on whether you are using version 5 or 6, you need to use different CSS.

version 6: https://cdn.jsdelivr.net/npm/simple-datatables/dist/style.css
version 5: https://cdn.jsdelivr.net/npm/simple-datatables@5/dist/style.css

Please reopen if that doesn't help.

**Comment by lmh5050** [comment]
i tried , but still can't solve the problem.

is there any other way?

i use this CDN

![image](https://user-images.githubusercontent.com/94948047/212210017-631bd6f5-6482-41d3-9c76-8a879341b52e.png)

**Comment by lmh5050** [comment]
i changed the cdn that you provided, but still not work. here is my status

**Comment by johanneswilm** [comment]
@lmh5050 With @latest you are using the CSS of version 6. I cannot see which library you are using, but if you are using the JS of 5, then change the link to the CSS to also use the CSS of 5: replace "@latest" with "@5".

If you are also using version 6 of the library, then you need to follow the upgrade guide linked to in the README. Depending on the complexity of your website, the upgrade may take 10 minutes to 3-4 days for a professional web developer.

**Comment by vetrivendhanm96** [comment]
Hi sir, have a one doubt my data-table not proper working. How to proper working table method? please teach me sir.
