### ISSUE TITLE
Uncaught Error: Data heading length mismatch.

### ISSUE THREAD

**Issue by Prabhashasachinthana** [fiduswriter/simple-datatables#224]
simple-datatables.js:3 Uncaught Error: Data heading length mismatch.
    at z (simple-datatables.js:3:40005)
    at t.init (simple-datatables.js:3:47460)
    at new t (simple-datatables.js:3:46819)
    at datatables-simple-demo.js:7:9

**Comment by johanneswilm** [comment]
Hey @Prabhashasachinthana ,
I need more information. Are you currently updating? Are there just as many headers as data  columns? Is this version 5 or 6?

**Comment by Prabhashasachinthana** [comment]
Hello brother,
How to find version.

https://phpgurukul.com/teachers-record-management-system-using-codeigniter/

I used the type of datatable used for this.

**Comment by johanneswilm** [comment]
@Prabhashasachinthana I will need a minimal example showing your issue.

**Comment by Prabhashasachinthana** [comment]
Hello dear,
Please tell me how to fix the issue. Which file edit for this issue

**Comment by johanneswilm** [comment]
It basically says that the number of headings is different from the number
of items in each row of data. They both need to be the same.

**Comment by johanneswilm** [comment]
If you are not able to make a minimal example  and this happened suddenly during the last few days and was working previously, I recommend just running on version5  by updating the url for both CSS and JavaScript from @latest to @5. So instead of:

```
<link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" type="text/css">
<script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" type="text/javascript"></script>
```

Have it say:

```
<link href="https://cdn.jsdelivr.net/npm/simple-datatables@5/dist/style.css" rel="stylesheet" type="text/css">
<script src="https://cdn.jsdelivr.net/npm/simple-datatables@5" type="text/javascript"></script>
```

**Comment by Prabhashasachinthana** [comment]
It worked. Thank you so much dear 😍
