### ISSUE TITLE
Hello, the problem continues to persist.

### ISSUE THREAD

**Issue by sgi1e** [fiduswriter/simple-datatables#227]
Hello, the problem continues to persist. 
I am using the version @6.0.0-14

![2023-01-13-135722_1280x720_scrot](https://user-images.githubusercontent.com/88407620/212397825-fafd8d26-b0e6-4287-ab28-bbe76ee7154e.png)

_Originally posted by @sgi1e in https://github.com/fiduswriter/simple-datatables/issues/216#issuecomment-1382260790_

**Comment by johanneswilm** [comment]
In that case I need more info. Could you make a minimal example showing the issue and post that?

**Comment by sgi1e** [comment]
Yes!

Example code

---
HTML Table
```
<table id="tblUsuarios" class="table table-responsive table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>Acciones</th>
            <th>Id Usuario</th>
            <th>Nombres</th>
            <th>Apellidos</th>
        </tr>
    </thead>
    <tbody>

    </tbody>
</table>
```

---
JS

```
let aux = new simpleDatatables.DataTable("#tblUsuarios");
```

---

Temporarily implement the following code snippet before starting simple-datatables

```
/* Fix temp */
row = SELECTOR(tbl + " tbody").insertRow();
SELECTORES(tbl + " th").forEach(x => {
    row.insertCell().innerText = "🌺 🌹 🌺"; 
});

let aux = new simpleDatatables.DataTable("#tblUsuarios");

try {
  aux.rows.remove(parseInt(row.dataset.index)); //Return error but success remove
} catch (ex) {
   //No action
}

/* Code temp */
```
