### ISSUE TITLE
Regression on sorting between 4.0.8 and 5.0.3 when using render

### ISSUE THREAD

**Issue by Herugrim** [fiduswriter/simple-datatables#228]
After upgrading to 5.0.3 using https://cdn.jsdelivr.net/npm/simple-datatables@5 I noticed a regression on sorting columns that use a `render`. 

You can see this behavior in the following two JSFiddle's. The 'Price' column uses `render` and when you sort any of the columns, the data of the 'Price' column no longer matches the correct row:

Using 4.0.8: https://jsfiddle.net/f1x9njbt/
Using 5.0.3: https://jsfiddle.net/f1x9njbt/1

Would it be possible to fix this in @5 as this is considered stable?

**Comment by johanneswilm** [comment]
Hey,
@6 will be released within a few hours. Sorting and all kinds of other issues were the main reason version 6 was a large rewrite. If you have problems with version 5, I recommend upgrading to 6 now.

**Comment by johanneswilm** [comment]
Hey @Herugrim ,
version 6.0.0 has been released.

**Comment by Herugrim** [comment]
I confirm that this issue no longer exists in 6.0.4.
