### ISSUE TITLE
Styling the layout

### ISSUE THREAD

**Issue by mtangoo** [fiduswriter/Simple-DataTables#23]
Hi,
thank you for a useful library. It works great.
However, I could not find anywhere abou styling the layout. Can you provide a hint?
I would specifically want to style `{info}` `{search}` `{select}` and `{pager}`

Thank you!

**Comment by dpilafian** [comment]
This partial DOM selector structure put together for CSS Less should help you get started:

```less
// Simple-DataTables
.dataTable-wrapper {
   .dataTable-top {
      .dataTable-dropdown {
         }
      .dataTable-search {
         }
      }
   .dataTable-container {
      table.dataTable-table {
         thead {
            tr {
               a.dataTable-sorter {
                  }
               }
            }
         tbody {
            tr {
               td {
                  }
               }
            }
         }
      }
   .dataTable-bottom {
      .dataTable-info {
         }
      .dataTable-pagination {
         li {
            a {
               }
            }
         }
      }
   }
```

Example CSS Less code:
https://github.com/dnajs/data-dashboard/blob/master/src/style/external-libraries.less#L7

See one of the styled tables:
https://data-dashboard.js.org/#network

**Comment by mtangoo** [comment]
@dpilafian ,
Thank you for the help. Let me work on that. I will close this for now. I'll comment if I need further assistance. Again, thank you!

**Comment by jonathands** [comment]
It'd be great if we could provide html templates for the elements around the table, it makes it easier to integrate with common CSS  libraries
