### ISSUE TITLE
Is there a way to retain original tr id values?

### ISSUE THREAD

**Issue by nsheff** [fiduswriter/simple-datatables#231]
I'm creating a table in which I attach `id` attributes to my `<tr>` tags, so I can do things like remove them if the user specifies to delete. For example, I have:

```
<table id='itemTable'>
<tr id="row1"><td>...</td></tr>
<tr id="row2"><td>...</td></tr>
...
</table>
```

When I turn this into a DataTable using `simpleDatatables.DataTable("#itemTable", }...})`, then my table is replaced with:

```
<table id='itemTable' class="datatable-table">
<tr data-index="0"><td>...</td></tr>
<tr data-index="1"><td>...</td></tr>
...
</table>
```

I don't mind the `data-index` getting added, but why does this process need to wipe out my `id` variables? This precludes me from using my original code in which I used `document.getElementByID` to manipulate the rows of the table.

**Comment by johanneswilm** [comment]
Hey @nsheff,
a few points:

1. Before version 6, SDT kept the incoming data in an array of `<tr>`-elements that were not always in the browser. This had many negative effects. For example, data was translated from its original format to strings and couldn't easily be translated back when users wanted to export the data, there were issues with cells where the rendered output and the data differed, and sorting rows with rendered data was problematic as well. Going back and forth between dom nodes and JS code is also really slow. The problem increased in recent years as JS apps were no longer just 5-10 lines of code, but real complex software packages moving data back and forth.

So with version 6, I switched to a different approach: The source of the data is kept in its original format and what you see in the browser is just a rendered version of that. So you want to change the output, you can just either change the data held in the table at `datatable.data` and then call `datatable.update()`, or you change how the render methods work and then call `datatable.update()`.

2. To change how the render methods work, you have two places to do that: the `render()` function as part of the `columns` setting for individual cells, or the `rowRender` setting for entire rows. Please look at the demos for examples.

3. So you can change your `rowRender` method and make it put the ids back in. But - if you then use that to "manipulate the rows of the table" without going through the `rowRender` method, then there is a great chance the datatable will crash.

4. We cannot really leave ids on as the `<tr>`s are not replace when you paginate - just their content changes. Say you have a table with 1000 rows of which only 20 are shown. Previously it would keep 980 `<tr>`s in memory and switch them in as you are paging through. Now it just keeps 20 in the browser and fills those some 20 `<tr>` with different content as you are going through the pages. That makes it much quicker and less error-prone.

I hope that explains it.

**Comment by johanneswilm** [comment]
@nsheff Particularly, check out this demo: https://fiduswriter.github.io/simple-datatables/demos/14-row-navigation/ . Select some rows either by using Space on your keyboard or by clicking on them once the table has focus. Then look at the source code of how that is done.
