### ISSUE TITLE
table_Render ++

### ISSUE THREAD

**Issue by johanneswilm** [fiduswriter/simple-datatables#234]
With version 6, rendering tables with custom properties became more difficult. It is possible to change the class names used as well as add extra classes to cells and rows, but not to any of the other elements. This is how it can be done for rows and cells:

```js
new DataTable("table", {
    rowRender: (_row, tr, _index) => {
        if (!tr.attributes) {
            tr.attributes = {}
        }
        tr.attributes.class = tr.attributes.class ? `${tr.attributes.class} CUSTOM-ROW-CLASS` : 'CUSTOM-ROW-CLASS'
        if (tr.childNodes) {
            tr.childNodes.forEach(td => {
                if (!td.attributes) {
                    td.attributes = {}
                }
                td.attributes.class = td.attributes.class ? `${td.attributes.class} CUSTOM-CELL-CLASS` : 'CUSTOM-CELL-CLASS'
            })
        }
    }
})
```

The question is, should we add an option called something like `tableRender` to allow users to modify the output that comes from the renderer? Or is there another way that would be better? (Going back to how it was in version 5 is off the table as it lead to spaghetti-code nightmare).

@nsheff @tanishqv @notwarp @RauchenwaldC @LebCit  

See also #135 #231 and #232

**Comment by Herugrim** [comment]
+1 for `headerRender` from me as I use bootstrap classes for `thead > tr` and `thead > tr > th`.  I use sass to slightly modify the default bootstrap CSS so I am able to use `@extend` for the datatable headers for now. This is probably not feasible for everyone and it is far from beautiful (or maybe it is) :
```
// Extending thead > tr
.datatable-table > thead > tr {
	@extend .table-dark
}

// Extend thead > tr > th
.datatable-table > thead > tr > th {
	@extend .border-bottom-0
}
```

**Comment by johanneswilm** [comment]
I see some are overriding the classes to achieve this effect adding multiple class names in there that field separated by spaces. That can work for some items, but the class names are also selectors, so it's not a good approach overall.
The easiest would be to add the above mentioned function so that users have full control over their tables.

**Comment by johanneswilm** [comment]
@nsheff @tanishqv @notwarp @RauchenwaldC @LebCit @Herugrim I have made a first attempt at making modifications to allow for bootstrap and similar frameworks. There is currently a PR from the 6.1 branch. It includes a demo for a bootstrap styled table. Please take a look at it and let me know if this would work for you. If this approach is not working at all, I will close the PR without merging it and we'll try to resolve it some other way. This is not something that I need urgently, so I prefer to get it right rather than to get results fast.

**Comment by johanneswilm** [comment]
This is the PR that implements `tableRender` and other changes to make it bootstrap compatible: https://github.com/fiduswriter/simple-datatables/pull/239

**Comment by johanneswilm** [comment]
Ok, those column option also looks reasonable to me. Note that these render calls do not modify the dom, so doing several of them is not as expensive. In the case of bootstrap, some TDs need to turn into THs and making that a specific configuration option seems a bit much and the render call is more flexible.

For the paginator I am thinking it may be better to use the same diffdom render process as for the table with an optional `paginatorRender` call to modify the structure. Paginators can have all kinds of structures and that will allow for any structure.

**Comment by johanneswilm** [comment]
On the other points:

> initComplete (before the table is being drawed)

Ok, what would that be used for?

> drawCallback(after every time the table is being drawed)

There is the `datatable.update` event. How would this be different and what would it be used for?

> provide a callback for each column not only for each row (if we want)

How would we provide a callback for entire columns? The way tables are structured in HTML, with table > rows > cells, means that we can give callbacks at the table, row or cell level, but not at the column level AFAICT.

**Comment by johanneswilm** [comment]
The question is for me how many kinds of tables can be done only with `cellClass` and `headerClass`? Because if it turns out that it's really about making it work with Bootstrap and 3-5 other larger frameworks, each of which needs other changes to the structure so that the `renderTable` or `render` call is needed anyway, then it may not make as much sense to just add those classes.

Maybe we can try to identify all the different modification needs people here have. If we estimate that something like 30-80% of tables only need to add classes on cells or headers, then it probably makes sense to add those options.

**Comment by notwarp** [comment]
the callback i mentioned are secondary we can skip that argument, but i think that will be more clear use the properties in the column definition since you don't want every time create a cycle and iterate over the row for set a background color, or even better can be usefull if you already have a selector to use for make some logic over the data printed in the td, we used to have tons of different tables and we used to export the data visualized in them...
in this image the columns seem unique, but they are drawn as if they were 3, look also the header of the table has been placed in such a way as to align the titles to the underlying data, using the callbacks I was talking about before I managed to create the footer (the blue row below, where the data within the cells is taken based on the data in the aggregated columns)

![Screenshot from 2023-01-19 17-00-37](https://user-images.githubusercontent.com/9681029/213493570-37143785-e66e-475d-b98a-ba343ee4256f.png)

**Comment by johanneswilm** [comment]
Nice table!

Ok, for a lot of this custom stuff, I see there being a point in adding classes like that and it's not a big deal to add them, so let's do that if it's really just those two options `cellClass` and `headerClass. (I'll retract my statement if others here start commenting that they really need to change the nodeType of some TDs, add classes to children of THs, etc. as it makes no sense to try to cover every use case).

However...

>  you don't want every time create a cycle and iterate over the row for set a background color

Be aware that we are iterating over the entire (visible part of) the table every time we make just a tiny change somewhere (like move a cursor). I know that sounds bad, but that's because we are used to DOM changes being expensive and in this case we do it all outside the DOM, so it can be run much faster by the browser's JS engine.

**Comment by johanneswilm** [comment]
@notwarp  @surfmuggle @spimpolari @lucaterribili @DDDesign-dev @nsheff @tanishqv @RauchenwaldC @LebCit  @Herugrim 

There is now a version 7.0.0-rc.0 on npm & co. It includes new configuration options: `tableRender`, `pagerRender`, `cellClass`, `headerClass`, `locale`, `ignorePunctuation`, `sensitivity`, `numerical`, `caseFirst` and it allows to specify the date type of each column in more detail. It's in the [7.0 branch](https://github.com/fiduswriter/simple-datatables/tree/7.0) and it includes documentation. Please check it out so that we can get a 7.0.0 release that is working for everyone ASAP.

**Comment by johanneswilm** [comment]
I just fixed it for all the demos and switched back to making HTML the default column type - that seems to be what most are expecting because previous versions worked that way.

**Comment by johanneswilm** [comment]
I have not heard anything from anyone. So I'll start putting it into my own projects, and if that's working out ok, I'll make a 7.0.0 release. After that, I am not planning on making any further large changes. I don't think there will a version 8 anytime for several years. At least I have no extra major feature I need from this library.

**Comment by johanneswilm** [comment]
Version 7.0.0 has been released and I will go back focusing on other things for a while.

**Comment by nsheff** [comment]
I wasn't able to figure out how to make this work for my use case (#231). What I'm trying to do is just use `id` values for `tr` elements defined in the original table. I was thinking something like this could work:

```
      rowRender: (_row, tr, index) => {
        tr.attributes.id=`${_row.attributes.id}`
      }
```

But the `_row` object doesn't retain the `id` information from the original table. I don't have a way to regenerate that `id` so I am losing the ability to retain original row identifiers.

Would it be possible to make `_row` include not just the content from the table, but also attributes?

**Comment by johanneswilm** [comment]
Unfortunately that is not technically possible. What you can do is create an extra column that only contains the id number. You can hide the column using the columns setting. That way you have access to the number for rowRender without it showing up to the user.

**Comment by johanneswilm** [comment]
yes, it's the same method for all possible cell/row attributes.
Attributes on the table itself should no longer be removed on version 7.

**Comment by johanneswilm** [comment]
version 5 worked fundamentally differently and had turned into spaghetti 🍝 code, which is why version 6+ is more restrictive in some sense.
What is the reason for you needing to specify widths rather than letting SDT calculate them?

**Comment by johanneswilm** [comment]
> It's simply that I have a specific table where the auto-calculated widths are not doing what I want -- it's causing one of the columns to shrink to the point that the content goes onto 2 lines, but I want to keep that particular column displayed in a single line, so it needs to be allocated a bit more of the available width %.

The auto-calculated values are created by laying out the entire table (pagination turned off) and then measuring what percentage each column takes up. You can influence that by applying CSS to the table - for example a `min-width`, a `padding`, etc. . That's the way I would go.

It's also possible that there is a bug in the measurement algorithm. If that is the case, please create an issue with an example.
