### ISSUE TITLE
Possible regression on insert() in 6.0.4 on table with headings

### ISSUE THREAD

**Issue by Herugrim** [fiduswriter/simple-datatables#236]
Not sure if this is an issue with the code or the documentation. After updating from 5.0.3 to 6.0.4 the `insert()` function no longer renders data when you pass an object with headings to a table that already has headings. 

If you omit `headings` from the object, or omit the `<thead>` from the table it does show the data properly. According to the docs @ https://fiduswriter.github.io/simple-datatables/documentation/insert() the expected, and previous, behavior is that the headings are be ignored but the data is inserted.

Example fiddle at https://jsfiddle.net/4mnatkxd/ , comment out `headings` or omit `<thead>` to show the data.

**Comment by johanneswilm** [comment]
Hey @Herugrim ,
ok, yeah I don't see any reason why we should break with what is documented and what used to work on this. I'll look at implementing it tomorrow.
