### ISSUE TITLE
Filter + Sorting problems

### ISSUE THREAD

**Issue by feeltheice77** [fiduswriter/simple-datatables#243]
Hi there

Filter works fine
sorting works fine

if i sort and then use the filter > works fine

**BUT**
if is use the filter and activate then sorting of a column > Results are not correct. 
you can try it at your demos (https://fiduswriter.github.io/simple-datatables/demos/10-filters/)

filter by "assist" and then sort by column like name or company or job.
normal filter shows 5 records.
after filtering and sorting i got 3 or no records. and also records with "manager" as job

Best regards
Torsten

**Comment by johanneswilm** [comment]
hey @feeltheice77 ,
that's not something I can reproduce. Filtering and then sorting works fone for me. Could you give more details? Some specific browser and are you running version 6?

**Comment by johanneswilm** [comment]
Hey again @feeltheice77 ,
when you say "filter" do you mean search? I just found a bug when trying to search for something and then using the sort mechanism to sort the results.

**Comment by feeltheice77** [comment]
hey @johanneswilm 
yes i do mean search. and this is exactly the problem i found.
yes i´m running at version 6. what do you think until when it will be fixed?

**Comment by johanneswilm** [comment]
@feeltheice77 I have a fix here and there will be a pre-release of the next release with the fix included within a day. I would wait for that or, if you can, make a copy of version 6 and try to apply the fix there. 

Fix is here: https://github.com/fiduswriter/simple-datatables/commit/97b0a87e223a390249586fca03e55377a788eb20#diff-9480543ab3342acdb2692cdb022e0486b298a91e1bbdc3617467aecc76f5f401R315

**Comment by feeltheice77** [comment]
thx 4 info @johanneswilm 
means i can dowload the new compiled js with the cdn-link for latest?

**Comment by johanneswilm** [comment]
@feeltheice77 Wait a few hours, there will be a prerelease with CDN link.

**Comment by johanneswilm** [comment]
@feeltheice77 There is a fix in version 6.0.8 that has just been released
