### ISSUE TITLE
Add CDN package

### ISSUE THREAD

**Issue by rigwild** [fiduswriter/Simple-DataTables#25]
It could be useful to have a CDN version of this package. A transpiled version using babel would be nice too. Thanks for your good work!

**Comment by johanneswilm** [comment]
@rigwild The package that is currently provided is transpiled using buble. Is that not good enough?

Do you have any preference for how the CDN version should be packaged? Would https://unpkg.com/ be an acceptable option?

**Comment by rigwild** [comment]
I didn't see that the package was transpiled, sorry.
unpkg is great. You also have https://www.jsdelivr.com/, but both are equally good CDNs.

**Comment by johanneswilm** [comment]
@rigwild Is jsdelivr set up automatically so that https://cdn.jsdelivr.net/npm/simple-datatables works already?

**Comment by rigwild** [comment]
Looks like it! Adding this link to the [README.md](https://github.com/fiduswriter/Simple-DataTables/blob/master/README.md) would be a nice addition.

**Comment by johanneswilm** [comment]
If this is something you are using, it would be good to find out if the dynamic import is working before listing it. Try to check if you can sort anything by date. That should dynamically load an extra file. That seems to be tricky in some setups. See #14 .

**Comment by rigwild** [comment]
I spoke too soon. It does not work.

 `simple-datatables:5 Uncaught ReferenceError: exports is not defined`

see: https://codepen.io/anon/pen/qGawej

There's a workaround making it work (but it's a bit *hacky*) : 
```html
<script>var exports = {}</script>
```

Maybe `format: 'iife'` is what we are looking for ? (I don't know rollup so I can't provide a PR.
see: https://rollupjs.org/guide/en#output-format

**Comment by johanneswilm** [comment]
@rigwild See the discussion in #14 - iife does not work for rollup under the current circumstances. But maybe we an switch to webpack?

**Comment by dpilafian** [comment]
I think PR #29 (Compile to umd with browserify) for Issue #15 may resolve this.

The new file:
```
dist/umd/simple-datatables.js (36k)
```
should show up at:
https://www.jsdelivr.com/package/npm/simple-datatables?path=dist

Then you could hit the CDN with something like:
```html
<link rel=stylesheet href=https://cdn.jsdelivr.net/npm/simple-datatables@2.1/dist/style.css>
<script src=https://cdn.jsdelivr.net/npm/simple-datatables@2.1/dist/umd/simple-datatables.js></script>
```

Because of the UMD _wrapper_, you instantiate like this:
```javascript
const dataTable = new simpleDatatables.DataTable(elem, config);
```

**Comment by johanneswilm** [comment]
@dpilafian I think you may be right. I have added the required extra fields in `package.json` so that it should be served on both unpkg and jsdelivr at https://cdn.jsdelivr.net/npm/simple-datatables and https://unpkg.com/simple-datatables . However I haven't tested this, so please do before we close this ticket. Also, it is still serving me the 2.1.1 version unless I manually specify that I want version 2.1.3. I have tried in several browsers, and from the documentation on those websites I don't really see how to invalidate the CDN's cache. I hope it does so automatically eventually. Else we'll need to change the URLs in the readme.

**Comment by rigwild** [comment]
It actually works!
See: https://codepen.io/anon/pen/vwvWwg

For URLs, the trick seems to be to use the `@latest` tag instead of the version number (or nothing).

Don't forget to add the CSS too.
```html
<link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" type="text/css">
<script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" type="text/javascript"></script>
```

**Comment by johanneswilm** [comment]
@rigwild Thanks, I updated the readme for 2.1.4. So with this I assume this issue has been fixed and I'll close it. Please reopen if this is not the case.
