### ISSUE TITLE
Issues parsing attribute values containing a newline or &#13;

### ISSUE THREAD

**Issue by liffiton** [fiduswriter/simple-datatables#251]
The presence of a newline character or `&#13;` in an attribute inside a table cell can break the datatable in a few ways.

A minimal working example with three variations:
```html
<!DOCTYPE html>
<html lang="en">
<script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.0.2" type="text/javascript"></script>
<body>
  <table id="test">
    <tr>
      <td>First</td>
      <td><span title="[...]">Second</span></td>
    </tr>
  </table>
  <script type="text/javascript">
    table = new simpleDatatables.DataTable("table#test");
  </script>
 </body>
</html>
```

If the `[...]` in the title attribute is `&#13;`, then the title attribute is gone from the table after the datatable is initialized.

If the `[...]` is `x y&#13;`, then the title attribute is gone and replaced by a new attribute `y=""`.

If the `[...]` is `x = y&#13;`, then the title attribute is gone *and* the datatable fails to fully initialize (the "Showing 1 of 1 entries" text is not present, for example).

Using an actual newline character in place of `&#13;` has the same results.

My specific use case is to have a title attribute (in a `<span>`) containing code that contains newlines and `=` signs.

**Comment by johanneswilm** [comment]
Hey @liffiton,
what is the end usecase for this? If this is just an academic exercise in looking at all the things one could theoretically put into an attribute, then I'll mark this as wontfix. 

If you actually need to put this into an attribute for a real world application, then we can explore what options there are.

**Comment by liffiton** [comment]
Heh, I had written my use case originally, then deleted it before submitting to keep it simpler.  :smile: 

I am making a table with code displayed in some columns.  When the code in a cell is longer than a brief snippet, I truncate the code displayed in the cell, then use the title attribute of a `<span>` to let the user quickly see the complete code in a mouseover tooltip.  So I will have lots of title attributes containing newlines and = signs, among other code things.  In my testing, browsers do display the tooltip text correctly (on separate lines) when the title string contains `&#13;`.

It's not critical, and there are other options, but this is the simplest and most convenient way I've found to accomplish what I'd like to do.

**Comment by liffiton** [comment]
It looks like `&#34;` (double quotes) in an attribute value also messes things up.

I'm curious about the reason for the `decode()` function in `readTableData()`.  If I understand correctly, it will change the contents of a table cell, as we're seeing here, in particular decoding HTML entities when they could well be there for a reason (as here).  I'm sure `decode()` is used for a reason, but I wonder if there is another way to accomplish that or if at least the recreated table can use the original contents of each cell rather than the decoded/changed version.

**Comment by johanneswilm** [comment]
There is the he-library (various versions) but it increases the size of this library by 50%.

**Comment by johanneswilm** [comment]
This library is also used by newcomers with just very basic understanding of JS, HTML, etc. . That's the audience that I added this "read table from HTML" for. For devs using really complex and undocumented features of the web, there are more efficient ways to initiate this library without going via reading the DOM. I'm thinking you are such a case. But we should make sure that the library doesn't break entirely when reading DOM objects.

**Comment by liffiton** [comment]
Just curious, what's the "he-library"?

Your intended audience / focus makes sense.  I like using read-from-DOM because then there's the clean fallback of still having a table if JS is disabled or not working.  If I need to go another way, though, that's fine.

Would it be possible to strengthen the code to not break, even if it still mangles some weird inputs like mine, but also pass through the table contents unchanged to the re-rendered table?  It could keep the decoded data internally, I assume for searching and sorting, while not changing cell contents in the rendered table itself.

**Comment by johanneswilm** [comment]
This is the he-library: https://github.com/mathiasbynens/he . It's 4 years old and there are several forks it.
Another approach would be to use diff-dom's nodeToObject function on the dom node instead of looking at the innerHTML. I'll check tomorrow if that works in all situations.

**Comment by johanneswilm** [comment]
@liffiton All these issues should be gone with 7.0.3. We no longer convert to an HTML string first, which should take care of all these encoding issues.

**Comment by liffiton** [comment]
Works great!  Thanks very much.
