### ISSUE TITLE
`columns.visible()` returns single boolean

### ISSUE THREAD

**Issue by leverglowh** [fiduswriter/simple-datatables#256]
using CDN version 7.1 
From the docs, when calling `datatable.columns.visible()` without params it should return a list of booleans, but it actually returns a single `true`.
> If you omit the select parameter, an array of booleans will be returned representing all available columns.

I made a codepen here: https://codepen.io/leverglowh/pen/LYBKeRw?editors=1111

Is it something I'm doing wrong?

Also this page: https://fiduswriter.github.io/simple-datatables/documentation/layout gives a 404 error.

**Comment by johanneswilm** [comment]
Hey @leverglowh ,
I will take a look. as for the layout option - it has been replaced by the template option. I updated the link in the documentation overview just now.
