### ISSUE TITLE
Trying to syle table with feather icons

### ISSUE THREAD

**Issue by adamallmer** [fiduswriter/simple-datatables#258]
I'm trying to style the table with some feather icons but are facing issues jumping between pages.
Bellow are the cdn's I use:

<script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.29.0/feather.min.js" crossorigin="anonymous"></script>

I will try to explain the issue:
The data table showing 10 of 15 entries everything looks good so far. 
Then I go to next page and the table Showing 11 to 15 of 15 entries, and it still looks good.
Then I go back to page 1 and the data table showing 10 of 15 entries but now icons are only displayed on the 5 last entries. So I'm missing icons on the 5 first entries. So it seems like the table doesn't cache or reload the icons correctly. 

I tried to use cache control headers with out success. Any ideas how I can solve this?

**Comment by johanneswilm** [comment]
@adamallmer Can you create a minimal example? Note though that if this feather-library modifies the DOM of things inside the table while it is in operation, then that is almost certainly going to lead to issues.

**Comment by adamallmer** [comment]
![Screenshot 2023-02-14 at 14 13 45](https://user-images.githubusercontent.com/100354278/218755127-0d56cc28-f70a-4b23-bd45-086af3a9a70d.png)
![Screenshot 2023-02-14 at 14 19 44](https://user-images.githubusercontent.com/100354278/218755188-eca1fecf-9d1b-41e6-ac97-7a93131b96c7.png)

Some examples when I switched between pages. 
and an HTML example 

<div class="container-fluid px-4">
    <div class="card">
        <div class="card-body">
            <table id="datatablesSimple" class="table datatable">
                <thead>
                    <tr>
                        <th>Användare</th>
                        <th>Email</th>
                        <th>Status</th>
                        <th>Teams</th>
                        <th>Medlem från</th>
                        <th>Actions</th>
                    </tr>
                </thead>

                <tbody>
                    <tr>
                        <td>
                            <div class="d-flex align-items-center">
                                <div><i data-feather="user"></i></div>
                                Tiger Nixon
                            </div>
                        </td>
                        <td>tiger@email.com</td>
                        <td>Aktiv</td>
                        <td>
                            <span class="badge bg-green-soft text-green">Support</span>
                            <span class="badge bg-blue-soft text-blue">FikaKlubben</span>

                        </td>
                        <td>20 Jun 2021</td>
                        <td>
                            <a class="btn btn-datatable btn-icon btn-transparent-dark me-2" href=""><i data-feather="edit"></i></a>
                            <a class="btn btn-datatable btn-icon btn-transparent-dark" ><i data-feather="trash-2"></i></a>
                        </td>
                    </tr>

**Comment by johanneswilm** [comment]
Yes, but can you make a minimal example that I can try out? That way I can see whether I can fix it for you. 

If you want to try to fix it yourself - try to run it without the feather javascript first on the entire table - then run simple data tables after that. So something like:

```js
feather.replace() // run this first
const table = new DataTable("table") // run this afterward
```

**Comment by adamallmer** [comment]
That did the trick, perfect thank you :)
