### ISSUE TITLE
No export function?

### ISSUE THREAD

**Issue by laurenceanthony** [fiduswriter/simple-datatables#259]
On the homepage of the project, there is mention of export functions. Are these implemented? I don't see any documentation or code for such functions.

**Comment by johanneswilm** [comment]
Yes, @laurenceanthony . Please take a look at the demos where you'll find https://fiduswriter.github.io/simple-datatables/demos/11-export/ as well as https://fiduswriter.github.io/simple-datatables/demos/7-init-destroy-import-export/

**Comment by laurenceanthony** [comment]
Thanks! I see now what to do. Perhaps an explanation of how to add the
extension modules could be added somewhere in the documentation to help
others who get stuck initially.
