### ISSUE TITLE
How to add more query params in ajax option

### ISSUE THREAD

**Issue by neelbhanushali** [fiduswriter/Simple-DataTables#26]
@Mobius1 
Is there a way to add more data to send to api as query params to implement server side pagination or search

Something like this.
`
ajax: {
        url: "/data",
        arguments: {
          page: 1,
          perPage: 15
        },
        load: loadHandler
      }
`

**Comment by johanneswilm** [comment]
Could you not just do:

```
ajax: { url: "/data?page=1&perPage=15", load: loadHandler }
```

Please reopen if there is something I am missing.

**Comment by neelbhanushali** [comment]
I'd like to know how to send ajax as a post request and then attach data.
