### ISSUE TITLE
Losing data attributes on tbody

### ISSUE THREAD

**Issue by floydj** [fiduswriter/simple-datatables#262]
My `tbody` has a data attribute like so:

```html
<tbody data-flex-crud-target="itemList">...</tbody>
```

But after DataTable is initialized on this table, that data attribute is lost:
```html
<tbody>...</tbody>
```

I've looked through the documentation, but I see no way around this, but maybe I'm missing it? Is there a workaround?  Thank you.

**Comment by johanneswilm** [comment]
look at renderTable to add it.

**Comment by floydj** [comment]
I will. But isn't this an issue? Keeping data attributes on the tbody, specified in templates, would seem to be a good feature.

**Comment by floydj** [comment]
And - is there any documentation available on renderTable? I'm not finding anything....

**Comment by johanneswilm** [comment]
Sorry tableRender https://github.com/fiduswriter/simple-datatables/blob/main/docs/documentation/tableRender.md


Sorry, this is not something that will be added as there are ways for you to achieve what you want already.

**Comment by floydj** [comment]
I'm not trying to be difficult, I promise. But is there an example for using this?

**Comment by floydj** [comment]
Ok, here's what I came up with, in case someone else runs across something similar. I couldn't find any documentation on it:

```javascript
new DataTable(this.element, {
  paging: false,
  ordering: false,
  info: false,
  searchable: this.searchableValue,
  tableRender: (_data, table, _type) => {
    table.childNodes[1].attributes = { "data-flex-crud-target": "itemList" }
  }
})

```

**Comment by johanneswilm** [comment]
If you look at the sources of the bootstrap table demo you can see an example of tableRender in action.

https://fiduswriter.github.io/simple-datatables/demos/19-bootstrap-table/

**Comment by seikosantana** [comment]
How do I apply this on rows?

My rows has data-* attributes and i want to preserve it after being initialized as datatables. Is that possible?
