### ISSUE TITLE
The row is not rendered when data return from API call in *ngFor loop

### ISSUE THREAD

**Issue by SuiHuang1211** [fiduswriter/simple-datatables#269]
<tbody *ngIf="dataTable.length > 0">
                <tr *ngFor="let table of dataTable; let i = index">
                    <td>{{ table.txDate | date:'d MMM y' }}</td>
                    <td>{{ table.bankAccountNo }}</td>
                    <td>{{ table.accountHolderName }}</td>
                    <td>{{ table.accountHolderName }}</td>
                    <td>{{ table.accountHolderName }}</td>
                    <td>{{ table.amount }}</td>
                    <td>{{ table.amount }}</td>
                    <td>{{ table.amount }}</td>
                    <td>{{ table.amount }}</td>
                </tr>
</tbody>

**Comment by johanneswilm** [comment]
Sorry, you need to describe what is happening and what you are trying to achieve in more detail. Preferable create a jsfiddle.

**Comment by SuiHuang1211** [comment]
<div class="table-responsive">
        <table class="table table-striped" id="transactionTable">
            <thead>
                <tr>
                    <th class="wd-25p border-bottom-0">Top Up Date</th>
                    <th class="wd-15p border-bottom-0">Account No.</th>
                    <th class="wd-20p border-bottom-0">First Name</th>
                    <th class="wd-15p border-bottom-0">Last Name</th>
                    <th class="wd-10p border-bottom-0">Email Address</th>
                    <th class="wd-10p border-bottom-0">Top Up Amount</th>
                    <th class="wd-25p border-bottom-0">Uploaded Payment Slip</th>
                    <th class="wd-25p border-bottom-0">Verify Status</th>
                    <th class="wd-25p border-bottom-0">Actions</th>
                </tr>
            </thead>
            <tbody *ngIf="dataTable.length > 0">
                <tr *ngFor="let table of dataTable; let i = index">
                    <td>{{ table.txDate | date:'d MMM y' }}</td>
                    <td>{{ table.bankAccountNo }}</td>
                    <td>{{ table.accountHolderName }}</td>
                    <td>{{ table.accountHolderName }}</td>
                    <td>{{ table.accountHolderName }}</td>
                    <td>{{ table.amount }}</td>
                    <td>{{ table.amount }}</td>
                    <td>{{ table.amount }}</td>
                    <td>{{ table.amount }}</td>
                </tr>
            </tbody>
        </table>
    </div>
    
    dataTable is an any[] that will store data returned from API call in ngAfterViewInit() method, however, the row is not showing anything after that

**Comment by SuiHuang1211** [comment]
<table class="table table-striped datatable-table" id="transactionTable">
 
 And if I add datatable-table in <table>, all functions are gone such as searching, sorting and etc. Kindly advise. Thanks a lot

**Comment by johanneswilm** [comment]
Not enough information. Please provide jsfiddle and reopen if this is an actual bug.
