### ISSUE TITLE
Pagination still visible when filtering

### ISSUE THREAD

**Issue by alphonse927** [fiduswriter/Simple-DataTables#27]
There's an issue when filtering the table. I have a table with 15 entries, setted to a 5 entries per page. When I type on the search and the first result have more than 5 entries, and then filter again, the filter shows no results, but the pagination is still visible.

**What to expect**
I don't think that's how it should work, I expect that the pagination and the "Showing #..." won't be visibles, or at least, showing 0 of 0 and the pagination not visible. 
I hope I made it clear, I'm not very good explaining.

![Screen Shot 2019-05-21 at 4 46 30 PM](https://user-images.githubusercontent.com/35039595/58132893-23841a80-7be8-11e9-9580-9aa7b0f25fbc.png)

**Comment by johanneswilm** [comment]
@alphonse927 Agreed. Please submit a PR.

**Comment by alphonse927** [comment]
@johanneswilm I just sent a PR -> #32

**Comment by alphonse927** [comment]
@johanneswilm I know you merged and did a release, I just update the version, but it still happening, the 3 lines doesn't even appears on the file.

**Comment by johanneswilm** [comment]
@alphonse927 Looks like the 2.1.4 version was tagged before your merge: https://github.com/fiduswriter/Simple-DataTables/commits/master . I released a version 2.1.5 right now which does contain your changes.

**Comment by alphonse927** [comment]
Okay... Thank you very much.
