### ISSUE TITLE
Is there a way to integrate buttons in columns with this library

### ISSUE THREAD

**Issue by kanavbhatia** [fiduswriter/simple-datatables#270]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/33593937/226311378-ace36326-df16-493f-b6d3-2fe1bd9e62c8.png">
<img width="573" alt="image" src="https://user-images.githubusercontent.com/33593937/226311540-50ba6524-8b78-4d3a-b4c3-698bbe8ef407.png">
I have used the above approach but it doesn't look the right way to do it

**Comment by johanneswilm** [comment]
Take a look at the demos. You will need to use the render function.

**Comment by johanneswilm** [comment]
For example here: https://fiduswriter.github.io/simple-datatables/demos/4-render-column-cell/
