### ISSUE TITLE
Bug: Existing classes removed from table element if no rows in the tbody

### ISSUE THREAD

**Issue by erobertson42** [fiduswriter/simple-datatables#271]
There appears to be a bug when initializing simple-datatables on an empty table that has no rows in the `<tbody>`, where any existing class names are removed from the `<table>` element.  If the table has rows, then everything works normally as expected.  Example:

```html
<table class="table" id="myTable">
	<thead>
		<tr>
			<th>Column 1</th>
			<th>Column 2</th>
			<th>Column 3</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>test data</td>
			<td>test data</td>
			<td>test data</td>
		</tr>
		<tr>
			<td>test data</td>
			<td>test data</td>
			<td>test data</td>
		</tr>
	</tbody>
</table>
```
```javascript
const myTable = new DataTable('#myTable');
```

In this instance, the resulting table element is correct:  `<table class="table datatable-table" id="myTable">`.  Now remove everything inside the `<tbody>`, which ends up as:  `<table class="datatable-table" id="myTable">`.

The pre-existing class `table` was stripped off, and thus the associated styling is missing.

EDIT:  Apologies, this is with version 7.2.0.

**Comment by moveson** [comment]
I ran into this same problem, and I was able to solve it using the `classes` option:
```javascript
this.dataTable = new DataTable('#js-local-workspace-table', {
  classes: {
    table: "datatable-table table table-striped",
  }
}
```
