### ISSUE TITLE
remove "dataTable-top"

### ISSUE THREAD

**Issue by Elias177Dev** [fiduswriter/simple-datatables#274]
Hey, i use simple-datatables for a project... now i would like to create slim version of a datatable without many informations.
But the plugin creates the "dataTable-top" div... how can i disable this ?

**Comment by johanneswilm** [comment]
If you need a table without the functionality of simple datatables, just create one dynamically in JavaScript using the input data.

Not enough information. Please provide jsfiddle and reopen if this is an actual bug.
