### ISSUE TITLE
How to set a fixed Header

### ISSUE THREAD

**Issue by cfconsultancy** [fiduswriter/simple-datatables#275]
I want to set the header fixed <thead>, I tried fixedHeader: true, but that doesn't work.
Any way how to do that ?

**Comment by cfconsultancy** [comment]
I figured it out :-)

        scrollY: "50vh",
        rowNavigation: true,
        tabIndex: 1,

and works

**Comment by johanneswilm** [comment]
closing as issue has been resolved.
