### ISSUE TITLE
Unable to delete a row from a table

### ISSUE THREAD

**Issue by aguerrerof** [fiduswriter/simple-datatables#28]
Hello,
i'm developing an application with typescript, and when i try to delete a row using 
`let tableElement = (<HTMLTableElement><any>document.getElementById(tableId));
                tableElement.deleteRow(index);`
the row deletes apparently but when i check with the function datatable.columns().dt.data; it stills shows me the row deleted.

**Comment by johanneswilm** [comment]
Hey @aguerrerof, please confirm whether that still is the case with version 6.0.0-2 and reopen this issue in case it is.
