### ISSUE TITLE
Ignore bootstrap classes

### ISSUE THREAD

**Issue by vzlabiom** [fiduswriter/simple-datatables#280]
It seems that simple-table css suppress bootstrap classes.  For example, if we use bootstrap css and assign clasee active-table for th or tr tag it is suppressed by simple-datatable - with or without classes  active: "active" in table options. The only situation when active-table is working - if it is assigned for a whole table. 

Same situation with selection. For example, if in an example https://fiduswriter.github.io/simple-datatables/demos/14-row-navigation/ replace 

tr.attributes.class = "selected"

by 

tr.attributes.class = "active-table"

no selection visible.

In general, it seems that simple-table ignore most of table attributes whihc are assign directly in html code.

**Comment by vzlabiom** [comment]
Ср, 12 апр. 2023 г. в 09:30, Johannes Wilm ***@***.***>:

> What do you mean by "suppress"? There is nothing in there that scans your
> css in order to cancel it out.
>

I mean that when any specific bs class (I.e. active-table)  is assigned to
th/tr attribute in rendering code (for example, in row rendering ) it is
ignored. Tested for your selection / navigation example


In general, it seems that simple-table ignore most of table attributes
> whihc are assign directly in html code.
>
> Yes, that is the case. Did you take any time at all looking at the
> documentation? Look at the three render options to specify rendering.
>
>
I review your documentation and example code.

**Comment by johanneswilm** [comment]
@vzlabiom OK, so you are saying there is something in the code that removes "active-table" as the class name but that permits "selected"?

I have just spent 10 minutes spinning up and editor making those changes only to discover that it works as it should. This is my diff:

```diff
--- a/docs/demos/14-row-navigation/index.html
+++ b/docs/demos/14-row-navigation/index.html
@@ -6,7 +6,7 @@
         <link rel="icon" type="image/png" href="data:image/png;base64,iVBORw0KGgo=">
         <title>Simple</title>
         <style>
-            tr.selected {
+            tr.active-table {
                 background-color: red;
             }
         </style>
@@ -763,9 +763,9 @@
                             tr.attributes = {}
                         }
                         if (!tr.attributes.class) {
-                            tr.attributes.class = "selected"
+                            tr.attributes.class = "active-table"
                         } else {
-                            tr.attributes.class += " selected"
+                            tr.attributes.class += " active-table"
                         }
                         return tr
```

In light of this, @vzlabiom please provide jsfiddle examples of all the issues you have reported. I will close all issues missing a jsfiddle within 24 hours.

**Comment by vzlabiom** [comment]
Here is  my test example (see attached file). It differ from your code only by bootstrap refs (see lines 6, 741) and tr.attridutes  coding(lines 766, 769).

If you comment bootstrap refs then you receive your exaple which works correctly. If you retrun bootstrap refs - nothoing working as needed. 





[test.zip](https://github.com/fiduswriter/simple-datatables/files/11211058/test.zip)

**Comment by johanneswilm** [comment]
Please create a jsfiddle or similar.

**Comment by johanneswilm** [comment]
Not enough information. Please provide jsfiddle and reopen if this is an actual bug.
