### ISSUE TITLE
Checkbox example failor 

### ISSUE THREAD

**Issue by vzlabiom** [fiduswriter/simple-datatables#282]
Example: https://fiduswriter.github.io/simple-datatables/demos/17-checkbox-column/
If check any row and then change the page, the checked box remain on the same visible row, i.e. mark other data.
Same for sorting.

**Comment by m-blank** [comment]
I encountered the same problem. DiffDOM (used for updating the DOM) doesn't seem to recognize that the value of the checkboxes has changed and so does nothing at all with the entire first column when paging.
