### ISSUE TITLE
Search does not work if multiple custom input classes are set

### ISSUE THREAD

**Issue by tspng** [fiduswriter/simple-datatables#284]
Hi

I might stumbled onto a bug concerning search and custom input classes.

## Current behaviour
If I set multiple custom css classes (separated by space) to the input element, they are applied to the element as expected but the search functionality doesn't work anymore. If I type anything into the search input field, nothing happens.

## Expected behaviour
I assumed search would work normally, even when using multiple custom css classes on the input element.
If it's intended this way, a note in the documentation could be added.

## Steps to reproduce
```js
const dt = new DataTable(element, { classes: { input: "form-control form-control-sm" }})
```

## Details
Looks like the value of the classes input option is used as a selector in a match statement. 
This never matches if the value has spaces in it.

https://github.com/fiduswriter/simple-datatables/blob/8311db1d3abac84a958ca0ea045d59953981a992/src/datatable.ts#L478-L480

**Comment by johanneswilm** [comment]
Hey, yes, this does not work. You can create your own layout to add more classes.
