### ISSUE TITLE
Search / multisearch bad result when terms contains special characters 

### ISSUE THREAD

**Issue by Loocos** [fiduswriter/simple-datatables#288]
Hi,

I discovered this problem when doing this fgeature : https://github.com/fiduswriter/simple-datatables/issues/285

I made it by adding a select input just after initialization and using the multisearch function. I just figure out that there's problem with search by specific characters like "Ø 150 mm", the symbol "Ø" broke the search, resulting to bad result.

How can we solve this ? 

I'm using the v7.1.2

**Comment by johanneswilm** [comment]
Hey @Loocos "Ø" is an uppercase oe-letter, used in Norwegian or Danish. It should not be a special character. How is it breaking things for you?

**Comment by johanneswilm** [comment]
Please reopen if misunderstood, but I cannot reproduce this and Ø should not be a special character.

**Comment by Loocos** [comment]
Hi @johanneswilm,

Sorry for the late reply. It's not happening only on that kind of characters, have a look to :
![image](https://github.com/fiduswriter/simple-datatables/assets/26056280/99ab7b5f-d8a2-472c-a885-0ff42e2a04e7)

Maybe it's my way to do the search, but I'm using the multisearch function from the lib : 
`
const filterRows = (table, tableDOM) => {
    tableDOM.querySelectorAll('[data-js-filter]').forEach(select => {
        let columnIndex = select.closest('th').cellIndex
        let uniqueValues = [...new Set(table.data.data.map(tr => tr[columnIndex].text))]

        uniqueValues.forEach((value) => {
            const option = document.createElement("option");
            option.textContent = value;
            option.value = value;
            select.appendChild(option);
        });

        select.addEventListener("change", (event) => {
            const selectedValue = event.target.value;

            if (selectedValue) {
                let params = [{term: selectedValue, columns: [columnIndex]}]
                console.log("Multisearch : ", params);
                table.multiSearch(params);
            } else {
                table.search("", undefined)
            }
        });
    })
}
`

**Comment by johanneswilm** [comment]
@Loocos Can you pleae create a minimal test case on jsfiddle for this. Else I'll have to spend a lot of time trying to recreate your issue here.

**Comment by Loocos** [comment]
As I can see in your datatable.ts, in the multisearch function, that you make a search on each word divided by a space. 
We can control the sensivity and ignore punctuations through global configuration or column definition but that's not enough to make it works in all case. 

So if I'm wrong correct me, but I want to be able to make a search that only return the rows which match exactly my terms.
In your demos example, your search is quite easy on simple word/name, no special characters, ... so no problem will occur.

```typescript
....
        this.data.data.forEach((row: cellType[], idx: number) => {
            const searchRow = row.map((cell, i) => {
                let content = (cell.text || String(cell.data)).trim()
                if (content.length) {
                    const column = this.columns.settings[i]
                    const sensitivity = column.sensitivity || this.options.sensitivity
                    if (["base", "accent"].includes(sensitivity)) {
                        content = content.toLowerCase()
                    }
                    if (["base", "case"].includes(sensitivity)) {
                        content = content.normalize("NFD").replace(/\p{Diacritic}/gu, "")
                    }
                    const ignorePunctuation = column.ignorePunctuation || this.options.ignorePunctuation
                    if (ignorePunctuation) {
                        content = content.replace(/[.,/#!$%^&*;:{}=-_`~()]/g, "")
                    }
                }
                return content
            })
            if (
                queryWords.every(
                    queries => queries.find(
                        (query, index) => query ?
                            query.split(" ").find(queryWord => searchRow[index].includes(queryWord)) :
                            false
                    )
                )
            ) {
                this._searchData.push(idx)
            }

        })
....
```

I'm going to try using the datatable.multisearch event, see if I'm able to override the result.

**Comment by johanneswilm** [comment]
@Loocos So you are not searching, you are filtering? Click on te "Job" column in https://fiduswriter.github.io/simple-datatables/demos/10-filters/ . Is that what you are trying to do?

**Comment by Loocos** [comment]
@johanneswilm Not exactly, I want to let the user choose the value to filter on. Sometime I've more than hundred of values. If the user need to click 100 times, it's quite useless and not UX optimized. 

Another thing, would be to combine filters of multiple column, is that possible ?

**Comment by johanneswilm** [comment]
Hey @Loocos ,
in case of very custom search variants, you can always override the render functions.

If the space is the issue - have you seen hat you can customize the character that is used to divide queries up? Take a look at `searchQuerySeparator`.

**Comment by johanneswilm** [comment]
I am counting on this having resolved the issue.
