### ISSUE TITLE
datatable.update() doesn't work

### ISSUE THREAD

**Issue by salvymc** [fiduswriter/simple-datatables#290]
I have a function that manually updates the data in datatable.data.data
after that I start the update function datatable.update()
but if I then use the search field, the displayed data is the starting one, therefore the datatable.update() function does not re-render the table

**Comment by johanneswilm** [comment]
Hey @salvymc my time to work on this without recompensation is extremely limited. I first need to understand whether you found an actual bug or whether you just didn't take the time to look at the documentation and examples. Could you please clarify? The initial post makes it sound as if there is a bug. The comment thereafter makes it sound as if you just hadn't understood how to format the data.

**Comment by johanneswilm** [comment]
@salvymc Looking at this demo: https://fiduswriter.github.io/simple-datatables/demos/15-editing/ I tried the following:

1. double click on a name
2. change the name to another name
3. hit enter
4. search for the new name in the search box. 

Result: The correct row is shown.

So my initial suspicion is that you did not take a look at documentation and demos. Please reopen this issue if I am mistaken and there is an actual bug.

**Comment by salvymc** [comment]
Hi thanks for the answer, I read the documentation and at the beginning I was trying to modify the table by editing the data in dataTable.data and then I gave dataTable.update() to try to update the data I had modified as described in the documentation. but doing so I didn't get a good result, as the search always gave me the old value.

![1](https://github.com/fiduswriter/simple-datatables/assets/10051897/8d1836ca-07a5-4b2a-af21-2130556204ce)

for this then I asked if there was a method dedicated to changing the value of a cell.

for this then I asked if there was a method dedicated to changing the value of a cell that would also render the table correctly

now i'll take a look at the demo, although i edit the data using a bootstrap modal.

p.s thanks for all the support

**Comment by johanneswilm** [comment]
>  i edit the data using a bootstrap modal.

The kind of UI for getting input from the user should have no influence on how SDT operates.

Yes, you can for example update the data inside of `datatable.data`. You have to do that following the format used by the data that is in there already. Your comment above ( https://github.com/fiduswriter/simple-datatables/issues/290#issuecomment-1556756864 ) makes me think you possibly were not aware of that. You cannot just put data in any kind of format in there and expect it to render correctly. 

Have you taken a look at https://fiduswriter.github.io/simple-datatables/documentation/columns-API ?
