### ISSUE TITLE
Setting scope-attribute for th

### ISSUE THREAD

**Issue by YellowPhoenix18** [fiduswriter/simple-datatables#292]
Hey,
may I missed something, but it seems, that there is no option anymore to add attributes to th/tr items.

This was possible before the break from v5 to v6 due to just adding the attributes to the table itself.
Is there maybe a option to add this again?

A simple feature similar to the classes would be nice (Having a option named attributes with given entries (All table-items) and containing a key-value array with attribute-name and its content).

**Comment by johanneswilm** [comment]
Hey @YellowPhoenix18 ,
you can make the table render however you want to by using the three render-methods. I would not recommend going back to the spaghetti code aka v 5.
