### ISSUE TITLE
Sorting for file size 

### ISSUE THREAD

**Issue by socialmusemedia** [fiduswriter/simple-datatables#293]
I'm trying to implement sorting by filesize where the innerText of the td is a human readable filesize e.g. 2 GB and the data-content attribute has the size value in bytes. However, it seems that on page load the data-content attribute is being removed and the value of it is being written into the innerText of the td element.

**index.php**
`<td data-content="<?= $item['size'] ?>"><?= $item['nicesize'] ?></td>`

**Dev tools output**
<td>4326084659</td>

**Comment by johanneswilm** [comment]
Hey,
your example includes PHP code which will not look like that in the rendered HTML version. Please create a jsfiddle or similar.

**Comment by socialmusemedia** [comment]
@johanneswilm This is what the rendered table should look like.

<td data-content="4326084659">4.03&nbsp;GB</td>

**Comment by johanneswilm** [comment]
@socialmusemedia That is just tiny little bit of a table. Can you please post a full example? If you don't, it's basically like asking me to work for free spending a few hours trying to guess what your code could look like in order to either find a bug in the library or possibly just a bug in your code.

**Comment by socialmusemedia** [comment]
Sure thing sorry about that. I'm using the latest version [v7.2.0]
I included example data into the td elements, just what my php variables would output. If that example below is not enough I'll put together jsfiddle later tonight.

**index.php**

```
<table id="content_table">
    <thead>
        <tr>
            <th scope="col">UUID</th>
            <th scope="col">Path</th>
            <th scope="col">Size</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($items as $item): ?>
            <tr>
                <td>6a54a1c4-65c4-467b-9ad8-cc5422452bfb</td>
                <td>/path/to/file</td>
                <td data-content="4326084659">4.03&nbsp;GB</td>
            </tr>
         <?php endforeach ?>
    </tbody>
</table>
```

```
import { DataTable } from "simple-datatables";

const contentDataTable = new DataTable("#content_table", {
    perPageSelect: [["All", -1], 15, 25, 50],
    perpage: -1,
    sortable: true,
    columns: [
        {
            select: 3,
            type: "number"
        },
    ],
}
```

**Comment by socialmusemedia** [comment]
@johanneswilm here's a jsfiddle [https://jsfiddle.net/fjp68a3o/1/](https://jsfiddle.net/fjp68a3o/1/)

**Comment by socialmusemedia** [comment]
@johanneswilm just wanted to check in if you had a chance to look at the jsfiddle? Is the example enough?

**Comment by johanneswilm** [comment]
Please reopen if I misunderstood some part.

**Comment by socialmusemedia** [comment]
@johanneswilm Thanks for getting back on this. Essentially, I want to be able to sort the file size column by size. However, for users the file size is displayed in "human readable" format such as 2.04 GB or 150.00 MB. Unless I'm missing something, this doesn't work by default since the default sorting doesn't know how to handle the suffix. 

I came across this older issue [here ](https://github.com/fiduswriter/simple-datatables/issues/54) which mentions there's a way to add the file size in bytes as a data attribute which is then used for sorting. That does seem to be the way, but as you saw in the jsfiddle it's also replacing the server rendered part.

**Comment by johanneswilm** [comment]
@socialmusemedia Yes, please don't look at issues for before version 6 as version 6 has been almost a complete rewrite.

The library will take one input value per field - not one input value + one rendered version.

This is one possible way to solve what you are trying to do:

https://jsfiddle.net/johanneswilm/1r9vkq8y/

In this example, you don't really need the server side rendering of the values, unless you also want it to work when JavaScript has been turned of.

I hope that helps.
