### ISSUE TITLE
Freeze First Column when sorting

### ISSUE THREAD

**Issue by kaseymac78** [fiduswriter/simple-datatables#297]
Is it possible to freeze a column so its order does not change when all the other columns change when sorting? For example, I have a "Rank" column that is the first column in the table (from 1 to n), and when sorting other columns, I want the first column (Rank) to remain in the order of 1 to n and not change. I have disabled sorting on the first column by using the code data-sortable="false" in the TH tag, but I want to freeze that column completely while the others can be sorted.
<img width="1753" alt="Screenshot 2023-06-09 at 10 31 49 AM" src="https://github.com/fiduswriter/simple-datatables/assets/81869856/fe88150d-3d43-4a3b-bbf1-41237fc420a4">

**Comment by johanneswilm** [comment]
Yes, there are multiple ways to do it. For example, use the `tableRender` option to add an extra header cell and the `rowRender` option to add an extra cell to each row.

**Comment by kaseymac78** [comment]
Thank you johanneswilm. I'm looking for some examples of using tableRender and rowRender in the documentation but can't seem to find any. Do you know of any examples of these being used that I can reference? Thanks again!

**Comment by johanneswilm** [comment]
Yes, have you looked at the demos and their source codes?
