### ISSUE TITLE
Cell editing with hidden column

### ISSUE THREAD

**Issue by miketsts** [fiduswriter/simple-datatables#299]
If there is a hidden column, the editing widget is created in a wrong place.
I see there is a calculation for `visibleToColumnIndex()` but at the text edit widget should be created according to `visibleIndex` and not the calculated `columnIndex`. Eventually the modified value goes to the correct cell, but the visual presentation is very confusing.
Unfortunately I was unable to create a simple demo reproducing the issue or further debug the problem. I hope you can easily reproduce - just create a table with one hidden column (say, #2), and double click on a cell past this column.

**Comment by johanneswilm** [comment]
Hey @miketsts Please create a PR or a JSFiddle demo. Else I won't have the time to fix this. I don't use the editing feature for anything in my own projects.

**Comment by miketsts** [comment]
@johanneswilm Can you advice about a simple setup in order for me to debug the library?
My application has a complicated setup including Flask/Python backend, and I usually copy/paste one of your demos into my client side JS, while using `docs/demos/dist` combined JS files

**Comment by johanneswilm** [comment]
@miketsts Take a look at the jsfiddle that was posted as part of this issue: https://github.com/fiduswriter/simple-datatables/issues/293

You should be able to just modify the code, save it and it will generate a new jsfiddle.

Sorry for asking so directly, but I receive a lot of requests for this library, and it's taking quite a bit of time to help. It's not generating any income. So, therefore, cutting down the time I spend on these requests is greatly appreciated. Otherwise, I just cannot do it, even though I'd want to.

**Comment by miketsts** [comment]
@johanneswilm 
Here is the JSFiddle: https://jsfiddle.net/7beac3w8/1/
Here, column 1 is hidden.
Double click/Edit Cell creates the edit field in the next column
I think I have it fixed (both #298 and #299), will push a PR soon.

**Comment by johanneswilm** [comment]
What does Github not allow you to do? Have you tried to fork the repository into your own account and then created a PR from there?

If you are not too familiar with Github/Git and the changes are just in one or two files, just paste the contents of those files into a comment here and I will try to take them from there. Alternatively, email those files to me.

Thanks for your work on this!

**Comment by miketsts** [comment]
Attached are the modified files.

**Comment by johanneswilm** [comment]
Thanks @miketsts I've added your changes into a single (linted) commit.
