### ISSUE TITLE
Demos

### ISSUE THREAD

**Issue by runnerer** [fiduswriter/Simple-DataTables#30]
Hi,

It will be very helpful if demos are listed in the description.

Best Regards

**Comment by johanneswilm** [comment]
Would you want to contribute other demos for this purpose?

**Comment by dpilafian** [comment]
Feel free to copy or reference these demo tables using open data from **The Star Wars API**:
https://data-dashboard.js.org/#starships

**Comment by oneezy** [comment]
I'd like to see more demos too.

**Comment by oneezy** [comment]
I went ahead and created a few demos based off of `Mobius1`'s original demos. Maybe you'd like to add these in the `readme` or `wiki` @johanneswilm ?


### Vanilla Simple-DataTables Demos [(codepen collection)](https://codepen.io/collection/XdLVxV)

- [Vanilla Simple DataTables Demo](https://codepen.io/oneezy/pen/ZEpXLNQ)
- [Vanilla Simple DataTables — Filters](https://codepen.io/oneezy/pen/eYdGvRv)
- [Vanilla Simple DataTables — AJAX Example](https://codepen.io/oneezy/pen/BaLwpbv)
- [Vanilla Simple DataTables — Column Manipulation](https://codepen.io/oneezy/pen/oNzGBGZ)
- [Vanilla Simple DataTables — Datetime Sorting](https://codepen.io/oneezy/pen/BaLwWjE)
- [Vanilla Simple DataTables — init/ destroy/ import/ export/ hidden columns](https://codepen.io/oneezy/pen/WNGZpbV)
- [Vanilla Simple DataTables — Add 1000 Rows](https://codepen.io/oneezy/pen/RwGLKMx)

**Comment by johanneswilm** [comment]
@oneezy Nice! Would it be possible to add these to the demo folder in this repository or is there something they need from codepen? Webpages like that come and go and so preferably I'd like to have everything in just this one repository. That makes it also clear that the same license applies to all of it. But if it's not possible, I can add a link to this collection.

**Comment by oneezy** [comment]
@johanneswilm sure thing! i'll try and have something put together soon

**Comment by johanneswilm** [comment]
demos have been added
