### ISSUE TITLE
Cannot get fixedColumns to go false

### ISSUE THREAD

**Issue by jcoonrod** [fiduswriter/simple-datatables#300]
Perhaps my issue is with the documentation of the options . It would be great if each .md page would actually explain how and where that option should be included. I've tried to add the option fixedColumns:false in the basic object and in a columns: section but cannot get it to work. Please help!

**Comment by johanneswilm** [comment]
It is an option in the main configuration. See here: https://fiduswriter.github.io/simple-datatables/documentation/Options

Please also take a look at the demos. Come back if it doesn't work for you.
