### ISSUE TITLE
Cannot use most HTML entities in datatable.insert() data

### ISSUE THREAD

**Issue by liffiton** [fiduswriter/simple-datatables#305]
Inserting data containing HTML entities (e.g. `&rarr;` or `&#39;`) into an HTML column results in most entities being reproduced literally (i.e., the table ends up displaying `&rarr;` rather than &rarr;).

`&lt;`, `&gt;`, and `&amp;` *do* work correctly.

For a simple demonstration, go to https://fiduswriter.github.io/simple-datatables/demos/8-add-1000-rows/ and run in the browser console:

    datatable.insert({data: [['&lt; &gt; &amp; &rarr; &#39;','a','b','c','d']]})

Then go to the last page of the table to view the new row.  The first three entities will be displayed correctly, while the last two show up as the raw HTML entity string.

My guess is that this is connected to [`unescape()`](https://github.com/fiduswriter/diffDOM/blob/main/src/diffDOM/virtual/fromString.ts#L10]) in diffDOM.

**Comment by johanneswilm** [comment]
Hey,
yes, don't use HTML entitties. Use the regular UTF-8 characters.

**Comment by liffiton** [comment]
Thanks for the suggestion.

There is at least one place where the regular character won't work: including a quote character in an HTML attribute, e.g. in a title attribute.  I understand that's a very niche case that you may not care to support, but I'm pointing it out for completeness.

**Comment by johanneswilm** [comment]
Hey,
no, inserting HTML is not a good idea - will likely not work at all. Any
HTML you insert into sdt will be parsed in JavaScript and converted to the
structure of objects and arrays used internally before being diffed and
rendered into the table.

**Comment by johanneswilm** [comment]
So in the hypothetical case of wanting to add some very complex structure -
just hand it in in the format that SDT will convert it to otherwise. That
will mean less time spent on parsing HTML and no limitations on characters,
etc. .

**Comment by liffiton** [comment]
Yup, that's definitely the way to go.  Thanks!
