### ISSUE TITLE
How to fix the header while also scrolling horizontally

### ISSUE THREAD

**Issue by yuu-senoo** [fiduswriter/simple-datatables#307]
Sorry for my poor English.
I was able to fix the header with `scrollY`.
However, if the table is scrollable horizontally, the header rows and data rows do not scroll in tandem.
Is there any way to resolve this?

**Comment by johanneswilm** [comment]
MAybe if you create an element around the table and make that element scroll horizontally?

**Comment by lsissoko** [comment]
> MAybe if you create an element around the table and make that element scroll horizontally?

The wrapper element has a scrollbar that moves the header, but the body with no longer matches the header.

#### Screenshots:

<img width="312" alt="chrome_1LNM933sCo" src="https://github.com/fiduswriter/simple-datatables/assets/1082131/ee683111-10d7-4bc8-b572-879fa6d2cdfc">

<img width="311" alt="chrome_E0YiXdeLI2" src="https://github.com/fiduswriter/simple-datatables/assets/1082131/53af54ac-b718-49e5-a778-8a305409f635">

#### Source:

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/simple-datatables@9.0.0/dist/style.css">
<script src="https://cdn.jsdelivr.net/npm/simple-datatables@9.0.0"></script>

<style>
  #t1 {
    overflow-x: scroll;
  }
</style>

<div id="t1">
  <div id="t2"></div>
</div>

<script>
  var data = {
    "headings": [ "Column 1", "Column 2", "Column 3", "Column 4", "Column 5"],
    "data": [
      [ "a", 1.45033960644444444444444444444444444, 0.45033960644444444444444444444444444, 5.45033960644444444444444444444444444, 0.45033960644444444444444444444444444],
      [ "b", 1.45033960644444444444444444444444444, 0.45033960644444444444444444444444444, 5.45033960644444444444444444444444444, 4.45033960644444444444444444444444444],
      [ "c", 17.45033960644444444444444444444444444, 0.45033960644444444444444444444444444, 11.45033960644444444444444444444444444, 0.45033960644444444444444444444444444],
      [ "d", 34.20520364640522, 0.305362525263, null, null],
      [ "e", 22.505361595915, 1, null, null]
    ]
  };

  new simpleDatatables.DataTable("#t2", {
    data: data,
    scrollY: "100px",
  });
</script>
```
