### ISSUE TITLE
Adding <Link> component inside tablecell causes page refresh when clicked.

### ISSUE THREAD

**Issue by ActionCoding** [fiduswriter/simple-datatables#315]
Hi All,

I have a datatable setup with a link to view a detail page using the <Link> component. I use this on all other parts of my SPA and it routes the user to the correct path without page refresh but when I use it inside a dataTable it causes page refresh. Any idea why this is happening only inside the dataTable?

**Comment by johanneswilm** [comment]
Can you create a demo as a jsfiddle?

**Comment by ActionCoding** [comment]
Basically, datatable is converting jsx into a string so adding a Link component from react-router-dom is changed into a standard <a tag which react reloads the page when clicked as opposed to looking for a page component.

**Comment by johanneswilm** [comment]
ok, but that is not a demo. Please provide one and reopen this issue.
