### ISSUE TITLE
Export CSV

### ISSUE THREAD

**Issue by DigitalAndSEO** [fiduswriter/simple-datatables#318]
In the GITHUB description you put the comment that it can be exported to CSV (among others) "Export to common formats like csv, txt json, and sql"
I don't see this feature in the internal documentation and I don't know if this option is available but the documentation needs to be updated or it cannot be done and the description is misspelled.

**Comment by johanneswilm** [comment]
Sure it can be done. Take a look at the demos (before filing an issue). I
see there is a comma missing between txt and json. Anything else that os
misspelled?

**Comment by DigitalAndSEO** [comment]
Before being so rude, look at the description that you have written yourself: you already wrote it without a comma (incredible that someone would answer like that on GitHub).

[IMAGE OF DESCRIPTION WITHOUT COMMA](https://jmp.sh/unGwjLmc)
(this is how it is reflected after you realize that you have made a mistake and correct it to leave me wrong).

**Comment by johanneswilm** [comment]
Buddy, you are contributing zero on Github and asking for someone else's product for free and don't even bother with checking the demos before filing an issue. So there is a comma missing. That's what I found. But nothing misspelled, is there?
