### ISSUE TITLE
[BUG] Runner issue

### ISSUE THREAD

**Issue by johanneswilm** [fiduswriter/simple-datatables#327]
All github actions are failing due to this issue:

https://github.com/SeleniumHQ/selenium/pull/12413

It appears to be beyond our control.

**Comment by titusfortner** [comment]
You aren't letting Selenium Manager handle your driver or browser.

You're using another driver manager in the step before running your tests (https://github.com/fiduswriter/simple-datatables/actions/runs/5754180038/workflow#L19), so Selenium is just locating what you've installed elsewhere.
Then you specify what browser to use — https://github.com/fiduswriter/simple-datatables/blob/main/test/test.mjs#L20 so Selenium Manager is just checking the version (it would throw a warning message if the version didn't match)

This is a chromedriver v115 error when trying to use the browser you specified. You can raise the issue with Google, or you can remove the driver manager and see if Selenium resolves the symlink for you.

**Comment by johanneswilm** [comment]
@titusfortner Thanks

> You're using another driver manager in the step before running your tests (https://github.com/fiduswriter/simple-datatables/actions/runs/5754180038/workflow#L19),

That line I actually just added now, hoping it would make a difference. It does help to install the right driver if the browser version is incorrect, but, unfortunately, it didn't help in this situation. So the line makes no difference.

> Then you specify what browser to use — https://github.com/fiduswriter/simple-datatables/blob/main/test/test.mjs#L20 so Selenium Manager is just checking the version (it would throw a warning message if the version didn't match)

I had forgotten about that line. And that did it!
