### ISSUE TITLE
Sorting not working for columns with only Font Awesome Icons in headers

### ISSUE THREAD

**Issue by CatfoodCZ** [fiduswriter/simple-datatables#33]
I have an issue with sorting of table when there is only Font Awesome icon in the column header.

```
<table id="ranking-archive">
<thead>
    <tr>
        <th>Order</th>
        <th>Name</th>
        <th>Rank</th>
        <th><i class="fa fa-fw fa-bolt"></i></th>
        <th><i class="fa fa-fw fa-star-half-alt"></i></th>
        <th><i class="fa fa-fw fa-skull-crossbones"></i></th>
        <th><i class="fa fa-fw fa-crosshairs"></i></th>
        <th><i class="fa fa-fw fa-fire"></i></th>
        <th>Overall</th>
    </tr>
</thead>
</table>
```
When I add any character in-front of `<i>` tag, the sorting starts to work. But only when you click on that character. When you are clicking on the icon nothing happens.

**Comment by johanneswilm** [comment]
Hey @CatfoodCZ , please confirm whether that still is the case with version 6.0.0-2 and reopen this issue in case it is.
