### ISSUE TITLE
Rows-API not displaying multiple rows

### ISSUE THREAD

**Issue by jayrudd02** [fiduswriter/simple-datatables#333]
### Rows-API

I have looked through the [documentation](https://fiduswriter.github.io/simple-datatables/documentation/) to try to see if this behavior is documented.
I have looked at the [demos](https://fiduswriter.github.io/simple-datatables/demos/) to see if one of them handles this, but none of them did.

BUG:
I have implemeted the package in my own project and in one of my html files i have inserted this into the script:

```
    const dataTable = new simpleDatatables.DataTable("#data-table", {
      searchable: false,
      fixedHeight: true,
      data: {
        headings: ["h1", "h2", "h3", "h4", "h5", "h6"],
      },
    })
    let dynamicRows = [
      ["col1", "col2", "col3", "col4", "col5", "col6"],
      ["col1", "col2", "col3", "col4", "col5", "col6"],
      ["col1", "col2", "col3", "col4", "col5", "col6"],
      ["col1", "col2", "col3", "col4", "col5", "col6"],
      ["col1", "col2", "col3", "col4", "col5", "col6"],
      ["col1", "col2", "col3", "col4", "col5", "col6"]
    ]
    dataTable.rows.add(dynamicRows)
```
    
now I know the datatable works perfectly because my headers are displaying perfectly but the multiple rows won't show.
It gives me no entries found on my page?

any suggestions?

**Comment by jayrudd02** [comment]
a Possible solution could be to for loop it but that's not how the documentation says

**Comment by johanneswilm** [comment]
Is there one bracket too much in the add() call? I cannot easily check, as
you haven't included a jsfiddle .

**Comment by jayrudd02** [comment]
So i have tried it without those extra brackets and nothing.

Could you maybe guide me into how i can add a jsfiddle for you?

**Comment by johanneswilm** [comment]
@jayrudd02 The documentation was not updated correctly. I have fixed that now. 

Instead of:

```js
dataTable.rows.add(dynamicRows)
```

Do:
```js
dataTable.insert({data: dynamicRows})
```

**Comment by jayrudd02** [comment]
i still have the same issue?

html:
```
    <div class="container">
      <h1>Data table</h1>
      <table id="data-table"></table>
    </div>
```

Script:
```
  <script>
    const dataTable = new simpleDatatables.DataTable("#data-table", {
      searchable: false,
      fixedHeight: true,
      data: {
        headings: ["h1", "h2", "h3", "h4", "h5", "h6"],
      },
    });
    let rows = dataTable.rows;
    let dynamicRows = 
    [
      ["col1", "col2", "col3", "col4", "col5", "col6"],
      ["col1", "col2", "col3", "col4", "col5", "col6"],
      ["col1", "col2", "col3", "col4", "col5", "col6"],
      ["col1", "col2", "col3", "col4", "col5", "col6"],
      ["col1", "col2", "col3", "col4", "col5", "col6"],
      ["col1", "col2", "col3", "col4", "col5", "col6"],
    ];

    rows.add(dynamicRows);
  </script>
```

**Comment by jayrudd02** [comment]
ahhhh thank you very much!

**Comment by jayrudd02** [comment]
> @jayrudd02 The documentation was not updated correctly. I have fixed that now.
> 
> Instead of:
> 
> ```js
> dataTable.rows.add(dynamicRows)
> ```
> 
> Do:
> 
> ```js
> dataTable.insert({data: dynamicRows})
> ```

the problem i have now is that my page is not displaying those rows.

i can see the rows that have been added?

**Comment by johanneswilm** [comment]
Look at the dataTable.insert line again. Does it look exactly as I suggested? :)

**Comment by jayrudd02** [comment]
ohhh my, please excuse my foolishness
