### ISSUE TITLE
Swapping columns doesn't change the index of the columns.

### ISSUE THREAD

**Issue by maxembregts** [fiduswriter/simple-datatables#334]
Hi,

I tried using the swap function on columns. The problem is that the index of the columns don't change.

Example:

Before swap:
Column 1 = ID, index 0
Column 2 = Name, index 1

After swap:
Column 1 = Name, index 1
Column 2 = ID, index 0

The index of name should be 0 and the index of ID should be 1, but it isn't.

**Comment by johanneswilm** [comment]
This issue will be closed again as you have not provided a live example as
required by the template.
