### ISSUE TITLE
Preserve custom tr classes

### ISSUE THREAD

**Issue by tacman** [fiduswriter/simple-datatables#336]
- [X ] I have looked through the [documentation](https://fiduswriter.github.io/simple-datatables/documentation/) to try to see if this feature already exists.
- [X ] I have looked at the [demos](https://fiduswriter.github.io/simple-datatables/demos/) to see if one of them does what I want, but none of them did.

I have a custom class on the TR's in my table, but that class is lost when I apply DataTables.

![image](https://github.com/fiduswriter/simple-datatables/assets/619585/06c7c0da-6529-4f81-940b-5ad31702cff9)

without Datatables:

![image](https://github.com/fiduswriter/simple-datatables/assets/619585/db1f621f-6745-441d-b92a-44dda81d7ce4)

The code is trivial:

    <tr class="{{ info.public ? 'table-primary': 'table-warning' }}">

Is there another way to add a class to specific rows?

**Comment by johanneswilm** [comment]
Yes, you apparently were not telling the truth when you said you had looked through the demos. Please look again.

**Comment by tacman** [comment]
I see rendering a cell, but I don't see row classes.

Demos
[Simple](https://fiduswriter.github.io/simple-datatables/demos/1-simple/)
[Dynamic import](https://fiduswriter.github.io/simple-datatables/demos/2-dynamic-import/)
[CDN](https://fiduswriter.github.io/simple-datatables/demos/3-cdn/)
[Render column cell](https://fiduswriter.github.io/simple-datatables/demos/4-render-column-cell/)
[Column manipulation](https://fiduswriter.github.io/simple-datatables/demos/5-column-manipulation/)
[Datetime sorting](https://fiduswriter.github.io/simple-datatables/demos/6-datetime-sorting/)
[Init-destroy-import-export](https://fiduswriter.github.io/simple-datatables/demos/7-init-destroy-import-export/)
[Add 1000 rows](https://fiduswriter.github.io/simple-datatables/demos/8-add-1000-rows/)
[Add-1000-rows-without-conversion (faster)](https://fiduswriter.github.io/simple-datatables/demos/9-add-1000-rows-without-conversion/)
[Filters](https://fiduswriter.github.io/simple-datatables/demos/10-filters/)
[Export](https://fiduswriter.github.io/simple-datatables/demos/11-export/)
[Updating](https://fiduswriter.github.io/simple-datatables/demos/12-updating/)
[Hide column](https://fiduswriter.github.io/simple-datatables/demos/13-hide-column/)
[Row navigation](https://fiduswriter.github.io/simple-datatables/demos/14-row-navigation/)
[Editing](https://fiduswriter.github.io/simple-datatables/demos/15-editing/)
[Scroll Y](https://fiduswriter.github.io/simple-datatables/demos/16-scroll-y/)
[Checkbox column](https://fiduswriter.github.io/simple-datatables/demos/17-checkbox-column/)
[Fetch API](https://fiduswriter.github.io/simple-datatables/demos/18-fetch-api/)
[Bootstrap table](https://fiduswriter.github.io/simple-datatables/demos/19-bootstrap-table/)
[Column filters](https://fiduswriter.github.io/simple-datatables/demos/20-column-filters/)
[SVGs](https://fiduswriter.github.io/simple-datatables/demos/21-svg/)
[AND Search](https://fiduswriter.github.io/simple-datatables/demos/22-and-search/)
[Column filter button](https://fiduswriter.github.io/simple-datatables/demos/23-column-filter-button/)

**Comment by tacman** [comment]
And specifically, I'd like to add the class in HTML, not in javascript.  Can you give me a hint as to where to look, or what to search for to find it?

**Comment by johanneswilm** [comment]
> I'd like to add the class in HTML, not in javascript.

Not possible. Only using JavaScript. You must take the time yourself to look through the demos.

**Comment by tacman** [comment]
I have yet to find a demo that shows a custom row color, nor any demo name
that implies I'd be able to do so.

**Comment by johanneswilm** [comment]
@tacman "Row navigation" demo (the headline gives it away as well). And for the future, please invest some of your own time into finding a solution before filing issues. That means not just looking at headlines for 5 seconds, but spending one day looking through the source code of everything and trying it out yourself.

**Comment by tacman** [comment]
Oh, I have -- I'm sorry to get off on the wrong foot this way.

I've been working on a Symfony bundle that wraps your awesome library in a
Twig Component with a Stimulus controller, that allows people to integrate
simple-datatables without writing a single line of javascript.

So I've been going over the options, but one thing that's natural for twig
developers is to add the class to the TR, which I couldn't find anywhere,
thus the feature request.

I had looked at the row navigation, and I understand how to add the
selected class to the TR.  I guess the feature I'm requesting is the
ability to apply a class based on a data value within the row.  In my case,
I want to change the color based on public and private.  And while I could
do that in the row render, as described in the demo, my feature request was
to preserve the tr classes from the HTML.

I did look through the demos, a lot.  And I couldn't find a way to preserve
the tr classes, so I created a feature request.  I did not create a feature
request asking to add classes to the TR, but rather to preserve the custom
classes as written.

I don't think my feature request is unreasonable, nor reflects laziness on
my part.  I certainly did not lie about not looking at the demos.

**Comment by tacman** [comment]
So my idea for a solution was to add a custom data attribute to the TR, and then add the classes in javascript.  

But it appears that the custom data attributes are not preserved either, and instead replaced by a data-index attribute.  

Would you consider re-opening my feature request to preserve both attributes and classes from the HTML on the TR elements?

**Comment by johanneswilm** [comment]
Hey.,
this has been discussed a million times before and the answer continues to
be no. There is a very clear and simple way of achieving what you want:
make the information another column and then turn that column into a data
attribute using the provided API.

**Comment by johanneswilm** [comment]
See for example demo "4-render-column-cell" on how to turn a column into a data attribute on the row. If you don't want to show the column as a column at all, you can additionally make it disappear doing `{ select: COLUMN_INDEX, hidden: true }`. See https://fiduswriter.github.io/simple-datatables/documentation/columns

**Comment by tacman** [comment]
Since I'm trying to integrate this with a  stimulus controller, the data attributes are critical.  I can work with datatables.net, I just wanted to offer your library as a light-weight, jQuery-less alternative.  

If you have PHP and the Symfony CLI installed, you can create a demo and see it action following the instructions here:

https://github.com/survos/SurvosSimpleDatatablesBundle

The CSS isn't loading automatically, I'm working on that.  But as a Symfony developer, I'm happy if I can add make my tables searchable and paged by simply requiring a bundle and adding a single tag to the table element.

**Comment by johanneswilm** [comment]
Hey @tacman ,
I have not used PHP for many years. jQuery is from another era, around 10-15-20 years ago, when JavaScript and HTML dom objects were mixed together in another way than what is more seldom the case today. If that is what works best for you, then I think you should stick to that and I don't see why you would want to use SDT instead.

In the post ES2015-world, where it is easy to combine different packages together, it doesn't make as much sense to have one package to try to solve every usecase by itself. SDT works by having separate stages of reading a table from DOM (or importing it directly as an object in JavaScript) and then an entirely different stage to render it back to a DOM object. The DOM-reading stage is relying on every data point being a cell in a table. The writing stage is also writing one data point to one cell by default, but can be configured to do something else. The reading and writing stages are decoupled. 

If you have a specific use case where a specific data point is represented by a specific data attribute on a row rather than a table cell, then it is also possible for you to write a custom reading stage to read this table into the format required by SDT. If you do that and you can write code that is sufficiently generic, I can merge your code into this repository to be used when enabling a specific configuration option. I would like to know how you would want to calculate the column order of these data points added as data attributes though.

Alternatively, if in your application you have a handful of specific data attributes that are application specific that you need to process, you may want to keep the reading stage code in your own repository and only rely on SDT for the processing and writing stages.

In all the other cases I have seen of this though, unfortunately all coming from people coding PHP, is that they added attributes to the row rather than an additional column because that's how they did it back in the good old days of jQuery and not because there was any technically reason to do so.

**Comment by johanneswilm** [comment]
@tacman I haven't used PHP for any kind of development since at least 2011-12 or there around. So I would probably spend a day or two getting your example to work here. Please provide a frontend-only demo (JavaScript, CSS, HTML) if you want me to look at it.

**Comment by tacman** [comment]
The example only requires cutting and pasting, after installing the Symfony
CLI and PHP.  And sed, which I used to save me from opening a file to
change the route.  Installing PHP is the hardest part if you're on Windows.

Eventually I'll have this on a website and then it will just be HTML with
links to javascript.  PHP, of course, is only used for generating the HTML.

It's very generic.  But since Bootstrap puts classes on the tr to style
them, that's what I do.  I want to take a bootstrap table, do "new
DataTable(tableElement)", and boom, it's my bootstrap table with your
goodies.

I don't use jQuery.  I hate it, in fact. But if an internal library uses it
for something, I'm not going to reject it.  I'm just trying to make my
tables look good and be functional.

I don't understand why the library needs to remove the existing classes.
Adding the data-index -- sure, that makes sense.  But removing all data
attributes and classes seems unnecessary, but of course, I don't know
anything about the internals of the library.

**Comment by johanneswilm** [comment]
Hey,
as I said, table read and write are two distinct phases. We use a dom
diffing library that removes any residues in the dom from the original
table. The output table may for example be paged, while the input table was
10000 rows long. So it's not possible to just not touch certain parts of
the table.

Good luck making your code working with this library or switching to
datatables.net.
