### ISSUE TITLE
Include style.css in npm/jsdelivr "Default"

### ISSUE THREAD

**Issue by tacman** [fiduswriter/simple-datatables#337]
**Is your feature request related to a problem? Please describe.**

I'd like to install the style.css from npm/jsdelivr, but I don't see it in the default, only the column filter css.   I fully admit that I don't know much about how javascript libraries are packaged, so I may be using the wrong terminology.

**Describe the solution you'd like**

I _think_ there is some configuration that determines what files are included in in the Default, but I really don't know.  In short, if style.css were listed here under the Default tab then the tool I use to install simple-datatables would also download it without any additional steps.  It downloads the column_filter css, but of course what I'd really like is the default style.css.

![image](https://github.com/fiduswriter/simple-datatables/assets/619585/50a72924-e47e-4849-a739-dedfd7542f16)

Thank you for your consideration.

**Comment by tacman** [comment]
Of course, this isn't urgent, as style.css can be downloaded with importmapper by explicitly calling it.  It just seems that style.css is more important than column_filter.

```bash
bin/console importmap:require simple-datatables/dist/style.css -vvv
10:50:36 INFO      [http_client] Request: "GET https://data.jsdelivr.com/v1/packages/npm/simple-datatables/resolved?specifier=%2A"
10:50:36 INFO      [http_client] Response: "200 https://data.jsdelivr.com/v1/packages/npm/simple-datatables/resolved?specifier=%2A"
10:50:36 INFO      [http_client] Request: "GET https://cdn.jsdelivr.net/npm/simple-datatables@8.0.0/dist/style.css"
10:50:37 INFO      [http_client] Response: "200 https://cdn.jsdelivr.net/npm/simple-datatables@8.0.0/dist/style.css"

                                                                                                                        
 [OK] Package "simple-datatables/dist/style.css" added to importmap.php.                                                
                                                                                                                        
      Use the new package normally by importing "simple-datatables/dist/style.css".      
```

**Comment by johanneswilm** [comment]
Hey @tacman ,
which tool is this? It says there that the URL is guessed. I wonder if it just picks the first CSS file it finds.

**Comment by johanneswilm** [comment]
Browsing through different packages at https://www.jsdelivr.com/package/npm/ I could not find a single one that has more than a single style file and one that contains a style file and jsdelivr doesn't say it guessed the file name. I also couldn't find anything in the jsdelivr documentation on npm about this.

@tacman If you can find a package where that is the case, please comment here so that I can try to figure out what is different about said package.

**Comment by tacman** [comment]
I think this is an example.  The importmap:require is a new Symfony component (AssetMapper) that is still in beta, downloading CSS is a very new feature.  

https://www.jsdelivr.com/package/npm/jstree

```bash
bin/console importmap:require jstree -vvv
09:43:25 INFO      [http_client] Request: "GET https://data.jsdelivr.com/v1/packages/npm/jstree/resolved"
09:43:25 INFO      [http_client] Response: "200 https://data.jsdelivr.com/v1/packages/npm/jstree/resolved"
09:43:25 INFO      [http_client] Request: "GET https://cdn.jsdelivr.net/npm/jstree@3.3.16/+esm"
09:43:25 INFO      [http_client] Request: "GET https://data.jsdelivr.com/v1/packages/npm/jstree@3.3.16/entrypoints"
09:43:25 INFO      [http_client] Response: "200 https://cdn.jsdelivr.net/npm/jstree@3.3.16/+esm"
09:43:25 INFO      [http_client] Response: "200 https://data.jsdelivr.com/v1/packages/npm/jstree@3.3.16/entrypoints"
09:43:25 INFO      [http_client] Request: "GET https://data.jsdelivr.com/v1/packages/npm/jquery/resolved?specifier=3.7.1"
09:43:25 INFO      [http_client] Request: "GET https://data.jsdelivr.com/v1/packages/npm/jstree/resolved?specifier=3.3.16"
09:43:25 INFO      [http_client] Response: "200 https://data.jsdelivr.com/v1/packages/npm/jquery/resolved?specifier=3.7.1"
09:43:25 INFO      [http_client] Request: "GET https://cdn.jsdelivr.net/npm/jquery@3.7.1/+esm"
09:43:25 INFO      [http_client] Request: "GET https://data.jsdelivr.com/v1/packages/npm/jquery@3.7.1/entrypoints"
09:43:26 INFO      [http_client] Response: "200 https://data.jsdelivr.com/v1/packages/npm/jstree/resolved?specifier=3.3.16"
09:43:26 INFO      [http_client] Request: "GET https://cdn.jsdelivr.net/npm/jstree@3.3.16/dist/themes/default/style.min.css"
09:43:26 INFO      [http_client] Response: "200 https://cdn.jsdelivr.net/npm/jquery@3.7.1/+esm"
09:43:26 INFO      [http_client] Response: "200 https://cdn.jsdelivr.net/npm/jstree@3.3.16/dist/themes/default/style.min.css"
09:43:26 INFO      [http_client] Response: "200 https://data.jsdelivr.com/v1/packages/npm/jquery@3.7.1/entrypoints"
09:43:26 INFO      [http_client] Request: "GET https://cdn.jsdelivr.net/npm/jstree@3.3.16/+esm"
09:43:26 INFO      [http_client] Request: "GET https://cdn.jsdelivr.net/npm/jquery@3.7.1/+esm"
09:43:26 INFO      [http_client] Request: "GET https://cdn.jsdelivr.net/npm/jstree@3.3.16/dist/themes/default/style.min.css"
09:43:26 INFO      [http_client] Response: "200 https://cdn.jsdelivr.net/npm/jstree@3.3.16/+esm"
09:43:26 INFO      [http_client] Response: "200 https://cdn.jsdelivr.net/npm/jquery@3.7.1/+esm"
09:43:26 INFO      [http_client] Response: "200 https://cdn.jsdelivr.net/npm/jstree@3.3.16/dist/themes/default/style.min.css"
```
                                                                                                                        
 [OK] 3 new items (jstree, jquery, jstree/dist/themes/default/style.min.css) added to the importmap.php!

**Comment by tacman** [comment]
Hmm, maybe that's not the example you're looking for, but rather an example of what you've already found.  

I've already submitted a request to give the option of downloading more related files, but in some packages there's so many that it'd be unwieldly.

**Comment by johanneswilm** [comment]
@tacman But also that one only contains one CSS file and the description also there says "The URL is guessed and might not be correct. You can always browse all package files to find the correct one."

**Comment by johanneswilm** [comment]
I am guessing that if it should be specified anywhere, it would be the package.json file. But as far as I can tell so far, jsdelivr doesn't read anything in the package.json file. It just "guesses".  At least that what it looks like thus far.

**Comment by tacman** [comment]
What do you think about adding an issue here? https://github.com/DataTables/DataTablesSrc/issues  and seeing if jsdelivr can provide some documentation or insights?

**Comment by johanneswilm** [comment]
sure, I think adding an issue to jsdelivr would be the most appropriate. jsdelivr displays that information about which CSS file to use. I don't think npm does that on its website.

**Comment by tacman** [comment]
Could it be that jsdelivr simply gets the first css file it finds?  

https://cdn.jsdelivr.net/npm/simple-datatables@8.0.0/dist/

That seems kinda bizarre, but I can't find any other pattern either.

**Comment by johanneswilm** [comment]
Yes, that is also my guess.

**Comment by tacman** [comment]
I've opened an issue at https://github.com/jsdelivr/jsdelivr/issues/18539

**Comment by tacman** [comment]
From that issue:

You can use style field in package.json, e.g. : https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/package.json
