### ISSUE TITLE
Refresh table after ajax function success

### ISSUE THREAD

**Issue by ricksG12** [fiduswriter/simple-datatables#338]
How to implement table refresh after my ajax function success? Thanks.

**Comment by johanneswilm** [comment]
It is unclear what is asked for here. See demo 5 showing loading data dynamically through a fetch call and then updating the table with them. It is adding a column, but you could also be using any other API call of datatables.

**Comment by ricksG12** [comment]
I want a function like this $('#example').DataTable().ajax.reload(); on simple-datatables.

**Comment by johanneswilm** [comment]
Hey, it sounds like you want a jQuery function. Go to datatables.net for that. 
That's not the normal structure of ES2015+ JS. You cannot go from the DOM to get the functions from the datatable. You need to keep your own reference to the datatable in JS in order to continue executing methods on it.
