### ISSUE TITLE
Add support to save state in localStorage

### ISSUE THREAD

**Issue by trenyture** [fiduswriter/simple-datatables#34]
I like your plugin, but for the moment the is so much things I can't reproduce from the jQuery version to yours that it's hard to me to change...

The first thing it could be awesome to add is to saving a state in localStorage, on the normal DataTable the configuration point is `stateSave: true,`, with this option enabled it will save / load automatically the table keeping datas in localStorage of the browser.

If it could be done here too, it would be a great advance!

**Comment by johanneswilm** [comment]
@trenyture You are welcome to add that by means of a PR.

**Comment by johanneswilm** [comment]
@trenyture Please reopen if you want to write such a plugin.
