### ISSUE TITLE
Uncaught DOMException: String contains an invalid character

### ISSUE THREAD

**Issue by klinux** [fiduswriter/simple-datatables#344]
- [X] I have looked through the [documentation](https://fiduswriter.github.io/simple-datatables/documentation/) to try to see if this behavior is documented.
- [X] I have looked at the [demos](https://fiduswriter.github.io/simple-datatables/demos/) to see if one of them handles this, but none of them did.

**Describe the bug**
We have in our table the follow code:

 `<a href="#" @click.prevent="openDropDown = !openDropDown"`

And we receive this error in web console:

```
Uncaught DOMException: String contains an invalid character
    r webpack://tailadmin-pro/./node_modules/simple-datatables/dist/module.js?:15
```
If we remove the `@click.prevent="openDropDown = !openDropDown"` for testing, the error is gone and table works.

**Comment by johanneswilm** [comment]
Can you explaina  bit more? When I try to create such an attribute in the JavaScript console, I also get an error:

```js
const el = document.createElement('div')
el.setAttribute('@click-prevent', 'openDropDown = !openDropDown')
```

That throws an

> VM386:1 Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': '@click.prevent' is not a valid attribute name.

**Comment by klinux** [comment]
No is very simple in my case here:

It is a little demo, we have the script:

```js
import { DataTable } from 'simple-datatables'

document.addEventListener('DOMContentLoaded', function () {

  const dataTablesCiCd = document.querySelectorAll('#dataTableCiCd')

  if(dataTablesCiCd.length) {
    const dataTableCiCd = new DataTable('#dataTableCiCd', {
      perPageSelect: false,
      perPage: 20,
      labels: {
        placeholder: "Filter pipelines...",
        info: "Pipelines {start} to {end} of {rows}",
      }
    })
  }
})
```
And a html static example:
```html
...
            <div class="rounded-sm border border-stroke bg-white shadow-default dark:border-strokedark dark:bg-boxdark">
              <div class="data-table-common data-table-search max-w-full overflow-x-auto">
                <table class="table w-full table-auto" id="dataTableCiCd">
...
<tr>
<td>

                        <span class="inline-flex gap-1">
    
                          <!-- Pipeline 1 -->
                          <div x-data="{openDropDown: false}" class="relative inline-block pipeline-min-graph-stage" style="margin-right: 0.3rem;">
                            <a href="#" @click.prevent="openDropDown = !openDropDown" class="inline-flex items-center gap-2 rounded-full pipeline-bg-success pipeline-border">
                              <span class="group">
                                <svg xmlns="http://www.w3.org/2000/svg" class="w-7 h-7" width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="white" stroke-linecap="round" stroke-linejoin="round">
                                  <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                  <rect class="w-3 h-3" x="5" y="5"  stroke="none" fill="white"/>
                                  <path d="M17 3.34a10 10 0 1 1 -14.995 8.984l-.005 -.324l.005 -.324a10 10 0 0 1 14.995 -8.336zm-1.293 5.953a1 1 0 0 0 -1.32 -.083l-.094 .083l-3.293 3.292l-1.293 -1.292l-.094 -.083a1 1 0 0 0 -1.403 1.403l.083 .094l2 2l.094 .083a1 1 0 0 0 1.226 0l.094 -.083l4 -4l.083 -.094a1 1 0 0 0 -.083 -1.32z" stroke-width="0" fill="currentColor"></path>
                                </svg>
                                <div class="absolute bottom-full left-1/2 z-20 mb-3 -translate-x-1/2 whitespace-nowrap rounded-md bg-white py-1.5 px-4.5 text-sm font-medium opacity-0 drop-shadow-4 group-hover:opacity-100 dark:bg-meta-4">
                                  <span class="absolute -bottom-1 left-1/2 -z-10 h-2 w-2 -translate-x-1/2 rotate-45 rounded-l-sm bg-white dark:bg-meta-4"></span>
                                  test: passed
                                </div>
                              </span>
                            </a>
</td>
</tr>
...
```

And the script get that error with: **Uncaught DOMException: String contains an invalid character**

**Comment by johanneswilm** [comment]
Yes, I hear you. But that `@` is still an illegal character in an attribute according to the browser. So how do you suppose I go around that? I know this is used in Vue, but as far as I can tell, I cannot assign such an attribute to a node. The browser stops me from doing that. Maybe the Vue-people who made the decision to use this have an idea of what to do?

**Comment by klinux** [comment]
The demo here we are using TailAdmin (based on Tailwind) with https://alpinejs.dev/

**Comment by johanneswilm** [comment]
Right. But unless there is some way one can escape the attribute name that contains an `@` in order for it to become a valid attribute name, I don't see a way of doing this. Whether or not `@` characters should be allowed in attribute names is something for the browser makers (Google, Mozilla, Apple) and the makers of those libraries using those to figure out. We don't have any share in that fight. You file an issue with them instead.
