### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by phpcodingmaster** [fiduswriter/simple-datatables#359]
Hi, 

If I add a <Button> component to the data array it shows [object Object] in the table.
![image](https://github.com/fiduswriter/simple-datatables/assets/79761312/d731114c-c61e-42ca-ba8e-13337acbdece)

How can I show buttons in the table? 

Thank you :)

**Comment by johanneswilm** [comment]
Hey @phpcodingmaster ,
it looks like you ignored the bug report template. I cannot tell what you are trying to do based on a screenshot. Could you please follow the template, including making sure you looked through each and every example and the entire documentation and only when that did not give you a result, you created an example showcasing the issue on jsfiddle or similar?

**Comment by johanneswilm** [comment]
@phpcodingmaster Please ask to reopen if you want to continue with this report.
