### ISSUE TITLE
Types package?

### ISSUE THREAD

**Issue by Joel-Intact** [fiduswriter/simple-datatables#360]
- [x ] I have looked through the [documentation](https://fiduswriter.github.io/simple-datatables/documentation/) to try to see if this feature already exists.
- [x ] I have looked at the [demos](https://fiduswriter.github.io/simple-datatables/demos/) to see if one of them does what I want, but none of them did.

**Is your feature request related to a problem? Please describe.**
In a TSX file, the event method's params always give error  

**Describe the solution you'd like**
Is there a Types npm package?

**Describe alternatives you've considered**
Still looking 

**Additional context**
React TS project, using simple-datatables v9

**Comment by johanneswilm** [comment]
I doubt it will ever work with react as react has its own dom diffing system that apparently needs full control of everything. This is a library for vanilla JavaScript library. That means it should work with vanilla Javascript. I have no idea what is going on in TSX. 

As for the second question - sdt itself is written in Typescript and therefore contains type definitions itself. There is therefore no other alternative package with type definitions.

**Comment by Joel-Intact** [comment]
Thank you, I appreciate the quick response!
