### ISSUE TITLE
[BUG] Strange filtering problem

### ISSUE THREAD

**Issue by KHReinhardt** [fiduswriter/simple-datatables#361]
- [x] I have looked through the [documentation](https://fiduswriter.github.io/simple-datatables/documentation/) to try to see if this behavior is documented.
- [x] I have looked at the [demos](https://fiduswriter.github.io/simple-datatables/demos/) to see if one of them handles this, but none of them did.

We are encountering an unusual problem. In Chrome, on some computers, we are not getting any results when filtering with a full string, although the expected results appear when filtering for a substring. For instance, when filtering for 'musterm' we get 'Mustermann, Firstname' but as soon as we type 'mustermann' we get no results. Strangely, this issue occurs only with very few names. We have checked the versions of the operating system and the browser, but the problem does not consistently appear with the same versions. Unfortunately, the developer tools are deactivated on most of our computers due to organizational policy, preventing us from debugging.

I searched the internet for related chrome bugs to no avail. Perhaps you have an idea or a hint.

**Comment by johanneswilm** [comment]
That sounds weird. I do however need a demo showing this behavior in order to work on it.

**Comment by johanneswilm** [comment]
@KHReinhardt Please reopen if you can reproduce this with the latest version and can provide a demo.
