### ISSUE TITLE
multiSearch not working for me

### ISSUE THREAD

**Issue by Moris1** [fiduswriter/simple-datatables#364]
Hi,

I would like to use multiSearch but I get these errors
jQuery.Deferred exception: t.map is not a function TypeError: t.map is not a function
    at s.DataTable.multiSearch (https://cdn.jsdelivr.net/npm/simple-datatables@latest:7:86019)
    at HTMLDocument.<anonymous> (https://dev.jazykyprobohemy.cz/js/scripts.js?1705676003:157:14)
    at l (https://dev.jazykyprobohemy.cz/vendor/jquery/jquery.min.js:2:29375)
    at c (https://dev.jazykyprobohemy.cz/vendor/jquery/jquery.min.js:2:29677)

This is my code
`let dataTable = new simpleDatatables.DataTable("#materialsTable", {
                                searchable: false,
				perPage: 100,
			});
var queries = {
				terms: ['Gra'],
				columns: [3, 4]
			};
			dataTable.multiSearch(queries);
`
I use latest simple data table library from CDN
https://cdn.jsdelivr.net/npm/simple-datatables@latest
I also used newest jquery, but no help.

Any example on this page would help
https://fiduswriter.github.io/simple-datatables/documentation/multiSearch()

I can use search() method on that table without any issue.

Could you help?
Thanks

**Comment by johanneswilm** [comment]
There us no jQuery in the library, so that error must come from your other code.

**Comment by Moris1** [comment]
Hi Johannes,

I have found the issue.
the parameter accepted by multiSearch method is array of objects. Not just object. Correct?
```
//works
var queries = [
				{
				terms: ['Slov'],
				columns: [3]
				},
				{
				terms: ['Gra'],
				columns: [4]
				}
			];
			 //makes errors
			var queries = {
				terms: ['Slov'],
				columns: [3, 4]
			};
			
			dataTable.multiSearch(queries);
```

**Comment by johanneswilm** [comment]
yes, that looks right. So it's not an issue after all then?

**Comment by Moris1** [comment]
Hi Johanneswilm,

no its not bug. Your multisearch works fine.
Can i have question? I will close this case after.
Is it possible somehow change the language of "Showing 1 to xx of xx entries" ?

Thanks
Jan

**Comment by johanneswilm** [comment]
Hey @Moris1 ,
yes, all the strings can be changed through the `labels` configuration option. See the manual page on that here: https://fiduswriter.github.io/simple-datatables/documentation/labels
