### ISSUE TITLE
[BUG] searchQuerySeparator not working via CDN

### ISSUE THREAD

**Issue by arcangelochine** [fiduswriter/simple-datatables#377]
- [x] I have looked through the [documentation](https://fiduswriter.github.io/simple-datatables/documentation/) to try to see if this behavior is documented.
- [x] I have looked at the [demos](https://fiduswriter.github.io/simple-datatables/demos/) to see if one of them handles this, but none of them did.

When setting the ```searchQuerySeparator``` in the options of ```DataTable``` it does not behave like it supposed to be. 

Here https://jsfiddle.net/mx10gnfe/ if you input "QWE ASD" in the search bar, you get the first 2 rows while you should only get the first one. Also, I think that inputing "QWE, ASD" should output the first 2 rows, since I set the ```searchQuerySeparator``` to be ```","```.

**Comment by johanneswilm** [comment]
@arcangelochine You are using version 6.0.8. That version has been out of date for a long time. We are currently at version 9. Please update to the current version and file a new bug if this issue persists.

**Comment by johanneswilm** [comment]
It works perfectly if you use a current version (https://cdn.jsdelivr.net/npm/simple-datatables@9)
