### ISSUE TITLE
[BUG] columns property not properly generated

### ISSUE THREAD

**Issue by arcangelochine** [fiduswriter/simple-datatables#378]
It appears that, given a filled table with an id, the ```simpleDatatables.DataTable``` constructor fails to properly initialize the columns property. In the following photos, it is evident that only the column with ```data-type="date"``` was properly translated. This leads to several problems because numbers get sorted alphabetically. 

<img width="1085" alt="Screenshot 2024-04-12 alle 02 59 05" src="https://github.com/fiduswriter/simple-datatables/assets/89729247/b7dc0766-04a5-49fa-b213-a7e78ae52705">

Given this table with ```id="prenotazioni"```, I executed from the console ```const dataTable = new simpleDatatables.DataTable("#prenotazioni");```. This led to the following:

<img width="1085" alt="Screenshot 2024-04-12 alle 02 59 33" src="https://github.com/fiduswriter/simple-datatables/assets/89729247/b736d72f-535f-4b30-b11f-f188b4c7d1a0">

Then I checked dataTable in the console and observed that the columns array contains only the infos regarding the date column of the table.

<img width="1085" alt="Screenshot 2024-04-12 alle 03 00 10" src="https://github.com/fiduswriter/simple-datatables/assets/89729247/1e4f971b-16df-445c-b416-fee70852caec">

**Comment by johanneswilm** [comment]
@arcangelochine You need to provide a full minimal example on jsfiddle or similar for me to be able to do anything about this.

**Comment by johanneswilm** [comment]
@arcangelochine Based on your screenshot, I believe you are using version 6.0.8 or even earlier. There have been three major versions released since then. I am working on this on a voluntary basis. Please make sure not to waste my time and update to the latest version before filing bugs.
