### ISSUE TITLE
[BUG] attribute data-sort not working in <th>

### ISSUE THREAD

**Issue by Cisar1235** [fiduswriter/simple-datatables#381]
version 9.0.3 (cdn)

attribute **data-sort** in <th> does not work as suggested. init options works fine.
attribute data-sortable works though.

**Comment by johanneswilm** [comment]
I will reopen if I get a reference.

**Comment by ste101** [comment]
I can see `data-sort `with date and an image:
![Image](https://github.com/user-attachments/assets/edd64073-2a73-4019-a413-0b8c5654c7a8)
It seams that `data-sort` is extracted from `<img title='DE'>` but sorting is not working.

Would it be possible to use `data-sort` as sorting factor?
It would be great also if I could generate `data-sort` server side.

**Comment by johanneswilm** [comment]
> This is working in original datatables.

@ste101 Are you talking about the jQuery Datatables.net package? Is that where the above example comes from? We have nothing to do with them. No code overlap at all and everything works very differently. If you have problems running dataTables.net, I suggest you contact their customer service support.

**Comment by ste101** [comment]
Sorry my fault. This was in my HTML code and I overlook this.
Would it be possible to add `data-sort` for sorting?

**Comment by johanneswilm** [comment]
@ste101 There are already ways to sort fields differently from the html/text contents of that field. But I am not a librarian and I need you to spend the time and look at the examples and the documentation yourself first. Only if you at the end determine that none of these ways of sorting work for you for some reason, you can file a new issue, create a minimal example on jsfiddle and then I will take a look at it.

**Comment by johanneswilm** [comment]
@ste101 Take a look here: https://fiduswriter.github.io/simple-datatables/demos/28-sort-order-attribute/ . And next time try to look yourself before filing requests.

**Comment by ste101** [comment]
Thank you very much for your hin.
I seached for this but didn't find it but I was blind.
