### ISSUE TITLE
Sorting with empty cells doesn't work correctly.[BUG]

### ISSUE THREAD

**Issue by mawsbu** [fiduswriter/simple-datatables#382]
We've been using tables inside "form" elements and have recently observed a strange side effect. Some tables, after sorting them, were submitting the whole form and reloading the page. So, for some reason, it breaks the sorting process, shows an error in the console, and then makes a default submission. It turns out that there are two conditions for this error: the table needs to be initialized with the number of entries per page larger than the table itself, and there have to be a few cells with no content inside. Then, if you try to sort the columns, sometimes it works fine for the first one or two clicks, but ultimately it breaks. Since, in our case, the tables are mostly generated dynamically and we cannot predict the content or number of rows, it is an issue.

[Here are examples of static tables where you can see this issue.](https://jsfiddle.net/mawsbu/axd06hu8/16/).

**Comment by johanneswilm** [comment]
@mawsbu @benwhalley  I am trying to investigate and fix this now. But I'm not seeing the error on that jsfiddle page. What I am supposed to do to trigger the bug? I am clicking on the headings "Report" "Gruppe and "Beschreibung" on both tables, but it works as expected and nothing is failing. I tried both Firefox and Chromium.

**Comment by johanneswilm** [comment]
At the time this bug was filed, version 9.0.3 was current. So I updated your jsfiddle to point to the 9.0.3 release [1], and it indeed showed the behavior that you mention. Luckily, the bug seems to be gone from the current version.

[1] https://jsfiddle.net/johanneswilm/L0uay4wv/1/
