### ISSUE TITLE
[BUG] Latest release (9.0.4) is not open source and changes are not visible in GitHub

### ISSUE THREAD

**Issue by pereorga** [fiduswriter/simple-datatables#385]
Latest release available in NPM is 9.0.4, updated 2 days ago: https://www.npmjs.com/package/simple-datatables

Latest release in GitHub is 9.0.3, code was updated last time 2 months ago: https://github.com/fiduswriter/simple-datatables

**Comment by cyn8** [comment]
Doing a `diff` between 9.0.3 and 9.0.4 shows a tiny, yet legitimate update. Looks like an additional check was added to verify if `this.wrapperDOM` is defined before attempting to access `this.wrapperDOM.parentElement`. Not sure why this is not reflected on GitHub.

**Comment by johanneswilm** [comment]
sorry about that. I just forgot to git push. Now back from holidays and I updated github.
