### ISSUE TITLE
[BUG] Always return true after use destroy() function

### ISSUE THREAD

**Issue by Juju86** [fiduswriter/simple-datatables#391]
https://github.com/fiduswriter/simple-datatables/blob/fd8986fbae0dd5b69a22df9dfab1e28779fc3e31/src/datatable.ts#L166

**Comment by thienvc** [comment]
Confirmed this bug, can't re-init after destroy

![image](https://github.com/user-attachments/assets/22cd80b5-10f1-4005-8d15-d6316c7fae5b)

**Comment by johanneswilm** [comment]
@Juju86 @thienvc Could you explaina  bit more abotu what the error is. I am a little confused as to why `true` should be returned.
