### ISSUE TITLE
Feature Request: Add Exact Matching Option to Search Methods

### ISSUE THREAD

**Issue by AndreasNorgaard** [fiduswriter/simple-datatables#395]
- [x] I have looked through the [documentation](https://fiduswriter.github.io/simple-datatables/documentation/) to try to see if this feature already exists.
- [x] I have looked at the [demos](https://fiduswriter.github.io/simple-datatables/demos/) to see if one of them does what I want, but none of them did.

**Is your feature request related to a problem? Please describe.**
Currently, the `search` and `multisearch` methods in our data table library return results that contain the search term, which can lead to unintended matches. For example, when searching in a column with "Active" and "Inactive" values, a search for "Active" also returns "Inactive" entries. This behavior can be problematic in scenarios where precise filtering is required.

**Describe the solution you'd like**
- Add an `exactMatch` parameter to search and multisearch methods
- When `exactMatch` is true, only return rows where the column value exactly matches the search term

Usage with this feature might belike this:
```
/**
 * @example
 * datatable.multiSearch([
 *   { terms: ["John", "Doe"], columns: [0, 1], exactMatch: true },
 *   { terms: ["Engineer"], columns: [2] }
 * ]);
 */
datatable.multiSearch(queries);
```

**Describe alternatives you've considered**
1. Implementing a separate method for exact matching (e.g., searchExact and multiSearchExact).
2. Using regular expressions for more flexible matching options.

**Comment by AndreasNorgaard** [comment]
Hi @johanneswilm,

You have a very good point to make that exactMatch might not be the best user experience when searching. However, I might not have been precise in my use case, as I am actually using the multiSearch for filters. Therefore, I am very interested in the filter feature. I havn't found anything about it in the documentation - where can I read more about it?

**Comment by johanneswilm** [comment]
@AndreasNorgaard Well, you stated above that you had looked at the demos. :) There is also something about it here:

https://fiduswriter.github.io/simple-datatables/documentation/columns#filter 

We probably need to add something to [the documentation](https://fiduswriter.github.io/simple-datatables/documentation/columns-API) about invoking the filter with `dt.columns.filter(columnNumber)`. A PR is welcome.

**Comment by AndreasNorgaard** [comment]
@johanneswilm I see now. This is somewhat the functionality I am looking for. However, do you know if it is possible to use the filter functionality togheter with a dropdown menu?
