### ISSUE TITLE
Set search term inside search box when using `search()`

### ISSUE THREAD

**Issue by Stoakes** [fiduswriter/simple-datatables#398]
Hello,

- [x] I have looked through the [documentation](https://fiduswriter.github.io/simple-datatables/documentation/) to try to see if this feature already exists.
- [x] I have looked at the [demos](https://fiduswriter.github.io/simple-datatables/demos/) to see if one of them does what I want, but none of them did.

**Is your feature request related to a problem? Please describe.**
When using [search](https://fiduswriter.github.io/simple-datatables/documentation/search()), 

Example:
The user browses to a page displaying a list of enterprise and their category (health, building, tech ...).
This page always returns the entire list, but by adding ?category in the url, js uses `search()` to filter out on client side the enterprises which don't belong to matching category.
But there's no easy way, to remove this filter, if eventually user wants to display the entire list of entreprises.

**Describe the solution you'd like**

It would be awesome if the search term was directly added inside the search box, so that user can remove the predefined search.

Another solution coulkd be something like https://datatables.net/reference/option/search.search, where we can set the initial term in search options.

**Describe alternatives you've considered**
I looked through the demo for `filter` and it seems to me, that it can't be tuned to match expected behaviour.

Thanks

**Comment by johanneswilm** [comment]
@rlafuente That looks like a godo solution to a particular problem. we cannot make this a universal solution as there may be multiple different searches happening simultaneously.
