### ISSUE TITLE
Provide Search By Column

### ISSUE THREAD

**Issue by trenyture** [fiduswriter/Simple-DataTables#40]
Could it be possible to search by column, I mean it's a little bit tricky with jQuery Datatable (see : https://datatables.net/examples/api/multi_filter.html ) but I am trying to do the same with your plugin and I can't find a way to search by column...

Is there any way or any patch in way?

Thanks you.

**Comment by vicbiz** [comment]
Any updates?

**Comment by trenyture** [comment]
@vicbiz sorry, i'm not using the plugin and i'm not getting looking for this anymore ... :(
