### ISSUE TITLE
[BUG] ignorePunctuation doesn't work with dot character when sorting

### ISSUE THREAD

**Issue by pereorga** [fiduswriter/simple-datatables#400]
- [x] I have looked through the [documentation](https://fiduswriter.github.io/simple-datatables/documentation/) to try to see if this behavior is documented.
- [x] I have looked at the [demos](https://fiduswriter.github.io/simple-datatables/demos/) to see if one of them handles this, but none of them did.

**Describe the bug**
As far I can see in the code, the dot should be removed with the other punctuation when sorting:

```
if (ignorePunctuation) {
    content = content.replace(/[.,/#!$%^&*;:{}=-_`~()]/g, "")
}
```

But the sorting doesn't work properly:

<img width="421" alt="SCR-20240926-tqnw" src="https://github.com/user-attachments/assets/4f2d38ec-22a9-4280-a15b-f8d426ad98a5">

(`1.000` should go after `100`in Catalan, as `.` is the thousand separator)

Search works fine, the dot is correctly ignored.

**To Reproduce**

Go to https://pccd.dites.cat/fonts

Code is:
```
new simpleDatatables.DataTable("#fonts", {
        locale: "ca",
        paging: false,
        columns: [
            {
                select: 2,
                sort: "asc",
            },
        ],
       ...
```

(`ignorePunctuation` is set to `true` by default, as per the documentation)

**Expected behavior**
The numbers should be ordered correctly.

**Additional context**
Interestingly, the `«`is ignored correctly, although it seems to not be part of the regex above (?):

<img width="250" alt="SCR-20240926-tqed" src="https://github.com/user-attachments/assets/3ac28b08-db05-4c54-aed6-17f5ca9bdd00">

**Comment by johanneswilm** [comment]
@pereorga You need to give me a full example that I can play with on jsfiddle or similar. Else I won't be able to help you.

**Comment by johanneswilm** [comment]
@pereorga The "ignorePunctuation" option for sorting is using a browser-internal function. The regex you found is used for searching. So this is a browser-internal issue. I get this order:

```js
console.log(
    [
        '1.000 people', 
        '2 men on Mars', 
        '100 planets', 
        '1 sun'
    ].sort(
        new Intl.Collator('ca', {usage: 'sort', ignorePunctuation: true}).compare
    )
)

> ['1.000 people', '100 planets', '1 sun', '2 men on Mars']
```

**Comment by pereorga** [comment]
Interesting, I'll see what I find...

Thanks for the information!

**Comment by pereorga** [comment]
FWIW, issue in Chromium is https://issues.chromium.org/issues/372390042

It happens on any thousands separator (comma or dot) on any locale (including English). I imagine this could be by design, as the issue seems to be consistent across browsers, although the spec is not clear (and I fail to see why nobody has the need to sort strings that include the thousands separator numerically).

At the same time, I believe simple-datatables doesn't allow providing a sort function, or way to use a data attribute value for sorting. That would allow workarounds.
