### ISSUE TITLE
More about window resize performance

### ISSUE THREAD

**Issue by pereorga** [fiduswriter/simple-datatables#401]
- [x] I have looked through the [documentation](https://fiduswriter.github.io/simple-datatables/documentation/) to try to see if this feature already exists.
- [x] I have looked at the [demos](https://fiduswriter.github.io/simple-datatables/demos/) to see if one of them does what I want, but none of them did.

**Is your feature request related to a problem? Please describe.**
After 9.2.0 release and the changes introduced in https://github.com/fiduswriter/simple-datatables/pull/397, window resizing performance has improved significantly. However, due to the resize event firing up to 10 times per second, there can still be noticeable slowdowns, especially when working with large tables.

**Describe the solution you'd like**
I propose increasing the interval between resize events to 250 milliseconds (or even 500 milliseconds), up from the current 100 milliseconds. There is likely no practical scenario where resizing the table more than twice per second is necessary.

**Describe alternatives you've considered**
An alternative solution would be to make the resize interval configurable, though I'm not sure this flexibility is truly needed in most cases (as long as resizing the window is not slow).

**Comment by johanneswilm** [comment]
ok, send in a PR about that. As long as no one else here says they have different preferences for resize interval, I think it's ok not to make it configurable. We can add configuration once there are different preferences among users.
