### ISSUE TITLE
[BUG] First column ignores the data attributes

### ISSUE THREAD

**Issue by Soetens** [fiduswriter/simple-datatables#403]
When the first column contains data attributes like `data-sortable="false"` or `data-sortSequence='["desc", "asc"]'` this seems to be ignored.

And the problem with data `data-sortable` beging ignored with dates can be that it also sorts the wrong way.

**Comment by johanneswilm** [comment]
Please provide a minimal example on jsfiddle. Else I won't be able to help you.

**Comment by Soetens** [comment]
I started with 
https://fiduswriter.github.io/simple-datatables/

And then I had some issues.
But then I moved to the CDN and now it seems to work perfectly.

**Comment by johanneswilm** [comment]
@Soetens Ok, was there a particular demo in which you noticed this problem?
