### ISSUE TITLE
[BUG] Sorting columns or executing search results in scrambled rows which alters the modal behaviour

### ISSUE THREAD

**Issue by gcem-ph** [fiduswriter/simple-datatables#404]
- [x ] I have looked through the [documentation](https://fiduswriter.github.io/simple-datatables/documentation/) to try to see if this behavior is documented.
- [x ] I have looked at the [demos](https://fiduswriter.github.io/simple-datatables/demos/) to see if one of them handles this, but none of them did.

**Describe the bug**
When a table is either searched or sorted by column, the new table does not allow the showing of the modal. For example, if a table with 3 rows is loaded with column id 1 -> 3, then by clicking on the any row allows to show the modal which in turn load a GET request. When the table is sorted 3 -> 1 by selecting the last row (column id 1) breakes the modal behaviour and attempt a get request to /test/3/ instead of /test/1/ url.  

**To Reproduce**

I am using Django framework. Each row is a link to the database entry. By clicking on each row, a modal is shows. The modal will show data retrieved by get-htmx ({% url 'test' column_id %}).  If table is displayed and not altered by search or sorting operations the link point to the right place. 

The DOM shows that htmx has swapped correctly the target element. However somehow the link still points to the wrong url.

**Expected behavior**
Modal should be displayed and url not change when table is sorted or searched

**Comment by johanneswilm** [comment]
@gcem-ph You left out the required link on jsfiddle (or similar) to an example showcasing the issue. I will close the issue until such a link is provided.

**Comment by johanneswilm** [comment]
As for htmx - it is not clear how and where you use it. Don't expect to be able to switch out parts of the table with some other JavaScript software and for simple-datatables to continue working. You need to go through the functions provided by simple-datatables to edit and update the table.

**Comment by gcem-ph** [comment]
@johanneswilm here is the jsfiddle: https://jsfiddle.net/y8ve4gqw/

**Comment by johanneswilm** [comment]
@Thanks for the demo. However, as I said before, you cannot just mess with the HTML of the table with other software and expect it to work the same. simple-datatables is a highly complex system for data tables and it has an internal storage that is apart from the HTML that is used for display. So just changing  the DOM structure is asking for trouble. This will not ever work.

As a Django user myself, my suggestion is to drop HTMX and potentially other JavaScript libraries that are making changes to the dom of the table. You can still use those in other parts of the page - just not within the dom of the table.
