### ISSUE TITLE
No API to update rows

### ISSUE THREAD

**Issue by playerla** [fiduswriter/simple-datatables#43]
Hello,
I would like to have a way to update my data efficiently. Actually I have tested this:
```js
// Update the row index by deleting it and adding again at the end
// Limitation: datatable require fixed rows orders, like a primary key column
dataTable.rows().remove(index);
dataTable.insert([one_row_data]);
dataTable.columns().sort(0, 'asc');
```

I don't know the internal data structure, I suppose there is no relation between data and rows since rows are juste the rendered order of data. It would be nice having a **rows.update(index) method**.

Any ideas ? 

Thank you

**Comment by johanneswilm** [comment]
Hey @playerla in version 6 there is method for that as part of the Rows API.

**Comment by playerla** [comment]
Thank you !
Found it https://github.com/fiduswriter/simple-datatables/blob/f1152085e4a99b4474da7e6120185d7788506436/src/rows.ts#L111
