### ISSUE TITLE
Sorting by datetime doesn't work

### ISSUE THREAD

**Issue by davidbrooksio** [fiduswriter/Simple-DataTables#48]
I have followed the documentation and added `data-type="date"` and `data-format="DD-MM-YYYY h:mm"` to the header of my date column. However, the sort seems to ignore this and simply sort via the numbers rather than the actual date. 

Do I need to include the moment.js library separately or does Simple-DataTables already include it?

![image](https://user-images.githubusercontent.com/22169477/69256491-73e92e80-0bb1-11ea-82f4-be9e0cc314bf.png)

![image](https://user-images.githubusercontent.com/22169477/69256539-8499a480-0bb1-11ea-967d-27a43ff4af11.png)

**Comment by Konafets** [comment]
Sorting of dates seems not to work at all. It doesn’t matter which date string I put into cell and which format I set. The table is sorted _somehow_.

**Comment by Khazl** [comment]
Same here with `YYYY-MM-DD` format

**Comment by johanneswilm** [comment]
It does work. Take a look at the demo. You likely need to adjust to the dynamic imports in your packing mechanisms.
