### ISSUE TITLE
Identify clicked button in event datatable.page

### ISSUE THREAD

**Issue by HugoMuller** [fiduswriter/simple-datatables#50]
Could it be possible to identify next/previous/first/last buttons in the event **datatable.page**?

I would like to achieve something like this:
```js
dataTable.on('datatable.page', function(page, button) {
  if(button === 'first'){
    console.log('go to first page');
  }else if(button === 'last'){
    console.log('go to last page');
  }else if(button === 'previous'){
    console.log('go to previous page');
  }else if(button === 'next'){
    console.log('go to next page');
  }else{
    console.log('go to page', page);
  }
});
```

I could bind some event listeners directly to the `li.pager` elements to handle this, but I think it defeats the point of firing datatable.page.

Thanks.

**Comment by johanneswilm** [comment]
Sure, please just make a PR with the desired modification. @HugoMuller
