### ISSUE TITLE
Sorting for file size with KB, MB...?

### ISSUE THREAD

**Issue by weilinzung** [fiduswriter/Simple-DataTables#54]
Sorting for file size with KB, MB...?

**Comment by johanneswilm** [comment]
Is this a feature you would like to program @weilinzung ? If so, we could add it.

**Comment by Stoakes** [comment]
Hello,

I've been dealing with similar issue for an hour before eventually finding this thread, which greatly helped me. Thanks to you all.

So commenting here for search engines: data-content in Simple-Datatables is equivalent to DataTables data-sort or data-order

**Comment by teemue** [comment]
How do you actually set the data-content-value? I tried to set it after datatable.rows().add() but it gets cleared after sorting the column.

**Comment by Stoakes** [comment]
My HTML is generated server side, so data-content come from there.
