### ISSUE TITLE
DataTable is not defined

### ISSUE THREAD

**Issue by MartijnHarmenzon** [fiduswriter/Simple-DataTables#55]
The below code results in the following error:
**DataTable is not defined**

How to resolve this?

```
<link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet">
<div id="dt1"></div>
script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest"></script>
let myTable = document.querySelector("#dt1");
let dataTable = new DataTable(myTable);
```

**Comment by dpilafian** [comment]
1. Add a leading `<` to the `script` tag
2. Replace:
```javascript
let dataTable = new DataTable(myTable);
```
with:
```javascript
const dataTable = new window.simpleDataTables.DataTable(myTable);
```

**Comment by MartijnHarmenzon** [comment]
@dpilafian Thanks for the response. Unfortunately, it does not resolve the error. I created a codepen.
https://codepen.io/martijnharmenzon-the-looper/pen/eYNrRjL?editors=1111

**Comment by dpilafian** [comment]
Oops, `simpleDataTables` should be `simpleDatatables` (without the `t` capitalized).

**Comment by johanneswilm** [comment]
Yes, take a look here: https://github.com/fiduswriter/Simple-DataTables/blob/master/docs/index.js
