### ISSUE TITLE
Omitting options parameter causes undefined is not an object error

### ISSUE THREAD

**Issue by dpilafian** [fiduswriter/Simple-DataTables#56]
When no `options` are provided:
```javascript
const elem = document.body.appendChild(document.createElement('table'));
new simpleDatatables.DataTable(elem);  //without options
```
`TypeError: undefined is not an object (evaluating 'e.layout')`
<br>

When `options` are provided:
```javascript
const elem = document.body.appendChild(document.createElement('table'));
new simpleDatatables.DataTable(elem, {});  //empty options
```
No error is encountered.

It looks like this started in **v2.1.9**: https://github.com/fiduswriter/Simple-DataTables/commit/b83f38e

**Comment by johanneswilm** [comment]
@dpilafian Should be fixed in the latest patch release
