### ISSUE TITLE
Bug with render function

### ISSUE THREAD

**Issue by leodreco** [fiduswriter/simple-datatables#57]
When I use the render function on a column it is repeated twice.
I don't know if I'm doing something wrong or if it's a bug.

```
<script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" type="text/javascript"></script>
<script>
const dt_Games = new simpleDatatables.DataTable(document.querySelector('#games'),{
    columns: [
        {
            select: 2,
            render: function(data, cell, row){
                let id = row.querySelector('td').innerText;
                if(id == 253230){
                    console.log(data);
                }
                data = `<img src="${data}">`;
                return data;
            }
    }
    ],
    ajax: '/games.json'
});
</script>
```

Result:
![screen](https://user-images.githubusercontent.com/62256627/77073832-e0d4cf80-69bd-11ea-9580-3b5e559c7351.png)

[Example.zip](https://github.com/fiduswriter/Simple-DataTables/files/4354654/Example.zip)

**Comment by johanneswilm** [comment]
Hey @leodreco @ebrensi ,
please try out version 6.0.0-2. It is almost a complete rewrite and handles the render function completely differently.
