### ISSUE TITLE
row-selection plugin

### ISSUE THREAD

**Issue by ebrensi** [fiduswriter/simple-datatables#58]
Hello Simple-Datatablers!  Like many of you I came here looking for a lightweight alternative to the excellent but over-featured jQuery DataTables library.

Simple-DataTables is fantastic except for that I would like to be able to select rows and have a selection event.  I can do that by adding an event listener to the HTML table node myself, but a plugin would be nice and I will write one if there is not one already out there.

So
(1) is there a listing of Simple-DataTables plugins somewhere? If not, can you add one here on the wiki?
(2) has someone already written a row-selection plugin?

Thanks!!

**Comment by DNWEIJ** [comment]
and did you write one? :-)

**Comment by MarquesCoding** [comment]
DId this ever get implemented?

Thanks

**Comment by ebrensi** [comment]
@MarquesCoding I ended up just coding my Table in JavaScript and writing my own selection handler.  SimpleDatatables turned out to be more than I needed.

**Comment by johanneswilm** [comment]
@ebrensi @MarquesCoding @DNWEIJ 

Row selection is now part of the main library. There is also a demo for it here: https://fiduswriter.github.io/simple-datatables/14-row-navigation/ . Hope that works for you!
