### ISSUE TITLE
Extend Filter functionallity from #53 

### ISSUE THREAD

**Issue by Sysix** [fiduswriter/Simple-DataTables#59]
Thanks @hydrocat for your PR #53
that PR is what I (almost) needed.

Can we make maybe some improvments?

## Make Filter as a Callback function

Sometimes you need extra functionallity checks like Date-Range, Validation, etc.
With the current setup we can only define Strings which will be checked with `String.includes()`.

Old:

```js
const config = {
    data,
    filters: {"Job": ["Assistant", "Manager"]},
};
```

New:

```js
const config = {
    data,
    filters: {"Job": (colValue, colElement) => ["Assistant", "Manager"].indexOf(colValue) >= -1},
};
```

## Make Public Method for Easy use on fly

Personally I want to create a Button, which will show me only entries which are in a Date-Range. This Button should toggle the filter on and off ever time.

I would prefer a Syntax like this:

```js
// example like config filter callback
let filterId;

if(!filterId) {
    filterId = dt.applyFilter(colIndexOrName, (colValue, colElement) => {});
} else {
    dt.removeFilter(filterId);
    filterId = null;
}
```

**Comment by hydrocat** [comment]
Hey @Sysix 
So, you have an interesting point. I believe that filtering by callback sounds like someone would expect from a filter. 

With this in mind, I am thinking about a few points:
1. A filter is a Boolean function
2. The filter is hooked to column ( just like it is now )
3. The argument for the filter is the value in a cell.
    In the example, it would be either ```'Assistant'``` or ```'Manager'```
4. The new set of rows is given by applying the filter to all the original initial rows, keeping those which the filter returns true.

And I have some remarks on that:
* Point 1 is the whole idea of function filters but I wonder how that would apply for the simple case, that is, how would the old example be implemented.

    Currently, once the row with a filter is clicked, we select only the rows whose cell value is the same as the filtered term. On the second click, we use the next term and finally, show all rows.

    In the example, it goes like this: 

    _All rows whose Job is_ ```Assistant``` → _All rows whose Job is_ ```Manager``` → all_items → ```Assitant``` ...

    My question is, How do we handle functions as filters ? I have a few Ideas
    * Apply it on click, reset on next click.
    * Have a list of functions to be applied, similar to what we have now.
    * Apply it every time the user clicks the row
        On a side-note, This one seems to be the most straight-forward way but I feel that it puts more strain on the person that is using this library so that the provided function is able to change it's behaviour on every call and also be able to 'reset' and show all values again.

* Point 3 might be more useful if the callback had access to the entire row. This would enable us to write more interesting filters, for example, Administrator with .org emails.

Also, I see that on your example, you refer to the functions's arguments as ```colValue``` and ```colElement```. What is the latter meant to represent ?

Hmm.. Looks like I wrote quite a bit.
I like the idea and I'd like your feed back on this feature.

**Comment by Sysix** [comment]
Thanks for your Feedback.

I agree to all points with you.

> Also, I see that on your example, you refer to the functions's arguments as colValue and colElement. What is the latter meant to represent ?

`colValue` should be the `innerText` from the td-`HtmlElement`. The `colElement` should be the
td-`HtmlElement` itself.

To your question how we should handle the filters:

I would let the developer use it how he likes it. The filters and the config are filters which are applied at the start and can be removed via the method.  
_we should discuss how we get the filterId, maybe easy about a filterList property_

The filters should be stackable. The developer need remove active filters manuelly.

Maybe as a Plugin we can create a Layout-Extension with predefined Buttons

**Comment by hydrocat** [comment]
What do you mean by stackable filters ? 
The result of one filter is applied to the input of the other ?

**Comment by Sysix** [comment]
In the basic version no events should be set for  the header or columns. Let the developer choice how he want to implement it

**Comment by hydrocat** [comment]
For the events, you may hook something into https://github.com/fiduswriter/Simple-DataTables/wiki/Events#datatablesort
By default, this event is fired whenever you click the column.

**Comment by hydrocat** [comment]
@johanneswilm Maybe you could close this ?

**Comment by johanneswilm** [comment]
ok
