### ISSUE TITLE
Initializing DataTable erases events within table

### ISSUE THREAD

**Issue by Bumppoman** [fiduswriter/Simple-DataTables#60]
Please see https://jsfiddle.net/968qevnk/2/

Adding an event listener to an element within the table removes the event.  I have only tried this with click events but I would imagine it extends to others as well.

**Comment by johanneswilm** [comment]
Right, but we cannot really help that if we are to do anything with it. Why don't you listen on the body and then check whether the target is what you wanted?

**Comment by suhailkc** [comment]
@johanneswilm Could you please explain how to do that?
A reply would be greatly appreciated.
