### ISSUE TITLE
Issue with sorting by dates

### ISSUE THREAD

**Issue by Bumppoman** [fiduswriter/Simple-DataTables#62]
Given a date in the format "May 14, 2020," and using the the DayJS parsing data-format "MMMM D, YYYY," dates will not be sorted correctly.

This appears to be due to the following line:
`const num = parseFunction(typeof content==="string" ? content.replace(/(\$|,|\s|%)/g, "") : content)` which appears in columns.js.  The replace is removing the commas and the space leading to the date being "May142020" before being parsed.  For whatever reason, if the DayJS format is changed to "MMMMDYYYY" it ignores the day and interprets the year as "142020."

It appears that this could be resolved by creating a flag if the content is a date and testing against this before removing commas and spaces.

**Comment by johanneswilm** [comment]
This
