### ISSUE TITLE
Breaks css

### ISSUE THREAD

**Issue by daniellord32** [fiduswriter/Simple-DataTables#67]
using Laravel mix
Importing the following
`import {DataTable} from "simple-datatables";

const appealTable = document.querySelector("#appeals_datatable");
const dataTable = new DataTable(appealTable, {`

Along with the correct ajax configuration options. 
When I `run npm run dev` the pluglin runs as expected but it is clearing my own css.
This is in my scss file that includes my imports for JS
`import '../bootstrap';
import 'admin-lte/build/js/AdminLTE';
import './appealDataTable';`

this is my imports for the CSS also via SCSS
`@import "~@fortawesome/fontawesome-free/scss/fontawesome";
@import "~@fortawesome/fontawesome-free/scss/solid";
@import "~@fortawesome/fontawesome-free/scss/regular";
@import "~@fortawesome/fontawesome-free/scss/brands";
@import "~admin-lte/build/scss/AdminLTE";
@import "customAdmin";
@import "~simple-datatables/dist/style.css";`

Any help would be appreciated.

**Comment by johanneswilm** [comment]
Hey @daniellord32 , unfortunately I don't know what "laravel mix" is and the code snippets don't tell me enough about what is going on. Could you post a more complex example somewhere?

**Comment by daniellord32** [comment]
Yeah I’m on leave at the minute I’ll get you more details when I get back


Sent from Yahoo Mail for iPhone


On Wednesday, June 17, 2020, 2:29 pm, Johannes Wilm <notifications@github.com> wrote:




Hey @daniellord32 , unfortunately I don't know what "laravel mix" is and the code snippets don't tell me enough about what is going on. Could you post a more complex example somewhere?
