### ISSUE TITLE
Sorting by Job in Demo actually do filtering by first row value in that column

### ISSUE THREAD

**Issue by Mingun** [fiduswriter/Simple-DataTables#72]
Clicking by **Job** column in [Demo](https://fiduswriter.github.io/Simple-DataTables/) filters table (I think, that only values that correspond to first row value stay visible). Because clicking on other columns has no such effect, I assume that this is a bug

**Comment by StanMenten99** [comment]
This is a custom filter.

`    filters: {"Job": ["Assistant", "Manager"]},
    columns: [
        {
            select: 4,
            type: "date",
            format: "MM/DD/YYYY"
        }
    ]`

**Comment by Mingun** [comment]
@johanneswilm could you add a link to the fix commit here?
