### ISSUE TITLE
Importing package as described creates and extra null chunk when using webpack and splitChunks

### ISSUE THREAD

**Issue by andrei-dracea** [fiduswriter/Simple-DataTables#77]
I've been using the plugin and for some reason this import renders a null chunk. 
`import {DataTable} from "simple-datatables"`

I don't have time to investigate further, however I fixed it by doing it like this
`import { DataTable } from 'simple-datatables/dist/index.js'`

¯\\_(ツ)_/¯

**Comment by johanneswilm** [comment]
This is interesting, however, as far as I can tell, this is a bug in webpack.
