### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by MartijnHarmenzon** [fiduswriter/Simple-DataTables#8]
Is it possible to make a table responsive? Something that removes the columns from the display. Like the datatables.net responsive extension? 
[https://datatables.net/extensions/responsive/](https://datatables.net/extensions/responsive/)

**Comment by johanneswilm** [comment]
I don't think there is any comparable function so far. However, you are welcome to write it. I'm trying to make the options available resemble datatables.net as much as possible, if there is someone willing to volunteer write the code.

**Comment by oneezy** [comment]
is this available yet???

**Comment by johanneswilm** [comment]
@oneezy You are welcome to reopen this issue and program it.
