### ISSUE TITLE
Problem with filling the table from a fetch function

### ISSUE THREAD

**Issue by fernaoguerra** [fiduswriter/Simple-DataTables#84]
Hi! First of all thanks for sharing this.

I am not the bet JS developer, so, sorry if it's a stupid question.

I am fetching a api and getting the data, converting into an array and loading into the table. But it looks like(at least is what i think) that the table loads first with o data, and than it does not fill it out.

```
const myArray = generateTableData().then((value) => {
    return value;
});

const data = {
    "headings": [
        "id",
        "date",
        "country",
        "city",
        "name",
        "comment",
        "address",
        "lat",
        "long",
        "cost",
        "days",
        "category",
        "media",
    ],
    "data" : myArray.then((value) => {
        console.log(value)
        return value;})
}
```

I get the headers and in the bottom a message: "No entries found""

anyone?

Thanks!

**Comment by johanneswilm** [comment]
Yeah, so the last part there ("data") is returning a promise. You'll need something like:

```js
generateTableData().then(tableData => {
  const data = {
    "headings": [
        "id",
        "date",
        "country",
        "city",
        "name",
        "comment",
        "address",
        "lat",
        "long",
        "cost",
        "days",
        "category",
        "media",
    ],
    "data" : tableData
  }
  
  //... create table here ...
})
```

Something like that can work. You need the promises resolved before using the data. But I don't really know how your generateTableData() function works, so I cannot tell exactly whether this is the code you need. Try to google for "JavaScript promises".

**Comment by oneezy** [comment]
Just adding these demos here for anyone else that might need them,

**Fetch API with .then** [(codepen example)](https://codepen.io/oneezy/pen/JjRMZyZ)
```
fetch('https://cdn.jsdelivr.net/gh/oneezy/data/cafe.json')
	.then(response => response.json())
	.then(data => {
    if (!data.length) {
		  return
    }
	
 	  let table = new simpleDatatables.DataTable(".table", {
	    data: {
			  headings: Object.keys(data[0]),
			  data: data.map(item => Object.values(item))
      },
    })
  })
```

**Fetch API with async/await** [(codepen example)](https://codepen.io/oneezy/pen/poEpMKz)
```
async function getData() {
	let url = 'https://cdn.jsdelivr.net/gh/oneezy/data/cafe.json';
	try {
		let res = await fetch(url);
		return await res.json();
	} 
	catch (error) {
		console.log(error);
	}
}

async function makeTable() {
	let data = await getData();
	
	let table = new simpleDatatables.DataTable(".table", {
		data: {
			headings: Object.keys(data[0]), 
			data: data.map(item => Object.values(item))
		}
	})
}

makeTable();
```
