### ISSUE TITLE
🐛 BUG: Duplicate <button> Render w/ AJAX

### ISSUE THREAD

**Issue by oneezy** [fiduswriter/Simple-DataTables#85]
I'm trying to add a button to each cell in a column but it's duplicating the button when using an `AJAX` call.
**Example 1:** https://codepen.io/oneezy/pen/XWjeewQ

If using `data` directly (no ajax) then it works as expected.
**Example 2:** https://codepen.io/oneezy/pen/wvzrPay

Is there a proper way to handle this?

**EDIT:**
I noticed this pull request https://github.com/fiduswriter/Simple-DataTables/pull/79 related to the issue. Still curious on the best way to fix this until it's merged.

![image](https://user-images.githubusercontent.com/7369575/102982573-6008ae00-44d0-11eb-80f4-070d59b4d72f.png)

**Comment by johanneswilm** [comment]
Hey @oneezy ,
before trying to fix this, I was wondering what the advantage for you is to use the built-in ajax method? My assumption is that the ajax code was in the original code from before the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch), when it was still hard to write such code in JavaScript. So I was actually thinking we should remove this in the next major version and just let people plug in their own method to fetch data. But you are using it. So my question: Why does it make sense to use this for you?

**Comment by oneezy** [comment]
Ahh I see. It definitely makes sense to upgrade to the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch). I didn't realize it was using the old [XHR](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) method. Would it make sense to update the `ajax` option to use `fetch` under the hood so not to introduce breaking changes in the new version? I personally like the simplicity of adding the `ajax: "some-url.json"` and it just work out of the box.

I should preface this by saying I'm more of a junior level dev and my skills lie more in the UI/UX area..so I'm not 100% keen on how to implement fetch into the current `simple datatables` version. I stumbled across issue #84 which you shined a little light on the topic but I'm still unsure on the best way to do so. I started a few pens if you or anyone else **`@here`** could demonstrate the proper way to use fetch w/ simple datatables. 

**DataTables w/ Fetch API (.then):** https://codepen.io/oneezy/pen/JjRMZyZ?editors=1011
**DataTables w/ Fetch API (async/await):** https://codepen.io/oneezy/pen/WNGdaXw?editors=0011

Once these demos are looking good I'll add them to the demos folder in the repo .

**Comment by johanneswilm** [comment]
Ok, yeah if there is use for it, I won't remove it. It's just that it can be easy to do if it's just publicly available data, but as soon as you have to do authentication against the server, that will work differently depending on how you have set it up and so if the datatable is just one of several things that you need to get via authentication within a specific web app, you'll probably have some common functions on how to get data from the server and you'll want to use that common function also for the data for the datatable.

For the one using fetch, remember that the fetch only returns a promise. So you need to create the table after the promise has resolved. For example like this: https://codepen.io/johanneswilm/pen/VwKyERO?editors=1011

**Comment by oneezy** [comment]
Nicely done! made it look to easy 😄

And yeah, that makes sense.

**Comment by johanneswilm** [comment]
Ok, I merged the example. I think that also shows some other advantages with using fetch directly - you can change the structure of the data before creating the table so that it fits (in the example finding the headings and changing dicts to arrays for each row). And you can decide what to do if the response is an empty array or you receive some other error value. For that reason, I would generally suggest to use your own fetch logic. If you and others still they we should have the internal ajax-code, I think what I will do for the next release is use the Fecth API for it, removing it from the "avertisement" part of the readme, and in the document where it's referenced point to this fetch demo and write "for anything more advanced than just simple get requests of data that is already structured in the way that Simple-DataTables expects, you are likely better of creating your own data request method." 

How does that sound?

**Comment by oneezy** [comment]
Definitely tons of advantages with using Fetch! I still need to figure out how to structure the data before passing it to the datatable but I've noticed by using `fetch` instead of the `ajax` method it fixed the duplicate `<button>` issue I was having. 

Here's that in action using fetch `async/await` plus a lot of other custom renders: 
https://codepen.io/oneezy/full/bGwLqZZ

> If you and others still they we should have the internal ajax-code, I think what I will do for the next release is use the Fecth API for it

yeah, I think that sounds like a solid plan.
