### ISSUE TITLE
Using POST in ajax data loading

### ISSUE THREAD

**Issue by evogli777** [fiduswriter/Simple-DataTables#87]
Hello,

Is there a way to use AJAX with POST for fetching data from the server? The ajax examples and wiki I saw, all use GET by default.

Also, is there a way to intercept the request and build the payload object with additional parameters? Let's say I have other filters on the page that the user can select and I want to send all of that to the server?

Thanks in advance

**Comment by johanneswilm** [comment]
Hey @evogli777,
if you want to load data in more complex ways, would it not be easier to just write the method for fetching the data and the interaction with simple data tables yourself in your own code? Or what advantage would you see in us adding this functionality to Simple-DataTables>

**Comment by evogli777** [comment]
Hello! 

Thank you for the quick reply. I have been using datatables.net but since I'm dropping jQuery from my pages, I was looking for an alternative. 

I wouldn't consider support for POST as an advanced feature, that's why I thought I'd ask. I don't know the goals and scope of this project, and you certainly don't have to match other products out there.

**Comment by johanneswilm** [comment]
Hey @evogli777 I just released a version 3.0.0 with the ajax stuff removed entirely. There is a Simple-DataTables-classic for older browsers and there is also a demo on how to use the fetch API in combination with SDT 3.0. The availability of the fetch API really changes a lot and there is much of a point to have this kind of feature inside a table library in 2021. I hope that helps.
