### ISSUE TITLE
ES2018

### ISSUE THREAD

**Issue by alpha-and-omega** [fiduswriter/Simple-DataTables#9]
ES2018 is not supported by 1-2% of internet browsers and for a project used mostly in serious production (DataTables is not some javascript toy) this is a serious disadvantage.
ES2018 is for node and server side where you can guarantee technology support, not for browsers.

**Comment by johanneswilm** [comment]
Not really. ES2015+ projects can in most cases be compiled into ES5 type code. Browser support is not much worse than nodejs support - in fact module loading is somewhat better.
This has been situation for a couple of years now. Browserify/webpack with babel or buble are used to compile it into something else. If you are still writing pre-ES2015 type code on a larger project, you should probably look at upgrading in the near future.

In fact, as you will see in the rollup config file, the distributed version of this library is compiled to pre-ES2015 code using buble: https://buble.surge.sh/guide/

**Comment by alpha-and-omega** [comment]
Thank you for explanation. Minified ES5 shims are 25k but I can live with that.
I see you decided to include Moment too, is that neccessary ?
Any plans to include minified version which can be used immidiately without webpack ?

**Comment by johanneswilm** [comment]
> Any plans to include minified version which can be used immidiately without webpack ?

You can see rollup makes it go through several steps [1], the last of which is `uglify` - a minification process. Rollup removes that code that isn't used, so it should not add 25K or any other other amount of code not used. You can get this version directly out of npm.

As for moments - I did what was the simplest there to just include it like a normal dependency. It is probably possible to instead make it be a plugin so that one can decide whether or not to load it. You are welcome to send in a patch about that, if that is important to you.


I am also open to include other improvements. But in 2018, it makes no technical sense to go back to 2014 JS. There are no advantages and most modern software is written in ES2015+ code. Old browsers are not an issue.

[1] https://github.com/fiduswriter/Simple-DataTables/blob/master/rollup.config.js

**Comment by alpha-and-omega** [comment]
So it already minified, hmm, I see now:
sourcemap: 'inline'
this adds source map and makes index.js 500k size, almost equal to original DataTable project size ;)

**Comment by johanneswilm** [comment]
True. So yes, playing around with the settings, it should not be too hard to get it to get the filesize to be significantly smaller.

**Comment by johanneswilm** [comment]
Just removing the line gives an 80k file. I think having the source map is important for debugging mostly. We could set it up to create two versions: one with sourcemap and one without.

**Comment by alpha-and-omega** [comment]
Yes, and without Moment size is 25k = to Vanilla-Datatables size.
I think it is better to ship 4 versions: original, original without Moment, and 2 minified. Moment = 50k, 2 times of DataTables code and I personaly don't use it, since 'data-content' attribute solves all date sorting problems.

**Comment by johanneswilm** [comment]
I have created a version now that doesn't put the sourcemap inline.

I also created a new branch for a version with dynamic loading: https://github.com/fiduswriter/Simple-DataTables/tree/dynamic-loading 

This basically means that moment is only loaded if the user actually tries to sort a column that is specified with a moment date format. However, this introduces a number of different new things which you probably don't want. It does work on pre-ES2015 browsers though, as you can see in the demo. This is likely going to be the future -- version 2.0.0 of the library.

**Comment by alpha-and-omega** [comment]
Interesting, I'll take a look, I think I will sit with Vanilla-Datatables until that release.

**Comment by johanneswilm** [comment]
Until what release? 2.0.0? Ibrelease 1.7.x last night which is significantly smaller, but does hardlink moment.

**Comment by alpha-and-omega** [comment]
Taka a look at Vanilla-Datatables description:

> A lightweight, extendable, dependency-free javascript HTML table plugin. Similar to jQuery DataTables, but without the dependencies.

I have replaced DataTables with Vanilla-Datatables because vanilla is 25k vs 500k of code, well, now you propose me to replace Vanilla with 106k of code just for ES2018 and new module management.

Now Simple-Datatables:
106k is not so lightweight
it has a dependency - module bundler

May be its just me and probably I am too picky, but I have my reasoning.

**Comment by alpha-and-omega** [comment]
Okay okay, go your way, I am out.
Happy new year!
