### ISSUE TITLE
Split into old and new package?

### ISSUE THREAD

**Issue by johanneswilm** [fiduswriter/Simple-DataTables#90]
Hey,
the requests that reach me about this package are on the one hand to make it more modern and on the other hand to fix things to make them work in Internet Explorer (6?). I understand that there are parts of the world where those browsers are still in use and so this being one of few libraries generally working with such old code, there is an interest on the part of some to keep it working with those browsers.

However, this is also holding us back. Adding checks and additions that only work on IE6 and slow everything else down is not ideal. And things like our Ajax code should either be removed or seriously updated.

So I am wondering if we should split this package into a Simple-DataTables-classic and this package. We would then have a new major version of this package and send anyone interested in IE6 to the classic package. The classic package could continue to work on IE6 for as long as that browser still exists somewhere.

Any opinions?

**Comment by oneezy** [comment]
I feel that if anyone needs to support older browsers that aren't _evergreen_, they should probably just use something like [datatables.net](https://datatables.net/). The major selling point for me to switch from **datatables.net** to **Simple-DataTables** is that it's written with the latest and greatest that `js` has to offer which means less code (no jquery!) and better performance. 

My vote is to keep development going strong in the es6 direction and never look back Lol..

**Comment by johanneswilm** [comment]
Ok, yeah that was also the reason I started working on this. I just notice that there have been PRs to keep the old stuff - which surprised me initially. Such a secondary package would not require to be updated very much, I would think. And eventually it would just die. But having it would also mean fewer protests if we remove something IE-relevant in this package. See for example these:

https://github.com/fiduswriter/Simple-DataTables/pull/82

https://github.com/fiduswriter/Simple-DataTables/issues/11

https://github.com/fiduswriter/Simple-DataTables/issues/12

https://github.com/fiduswriter/Simple-DataTables/issues/13

https://github.com/fiduswriter/Simple-DataTables/issues/9

Some of those are just trolls, others are probably real users. Just being able to forward all of them to another package should be enough. I agree that probably datatablet.net would make more sense for them in most situations, but for some reason they decided they needed something else anyway. What I can do is link to the datatables.net package on the Simple-DataTables-classic page just in case someone somehow missed the existence of it.

**Comment by johanneswilm** [comment]
https://github.com/fiduswriter/Simple-DataTables-classic has been created. I will now proceed here and remove code that is only there for old browsers.
