### ISSUE TITLE
How to get existing table? 

### ISSUE THREAD

**Issue by onychomys** [fiduswriter/Simple-DataTables#91]
I'm displaying data coming up from the back end as json, like this (this function is called as a part of a .then() statement after a fetch call): 

```
function addDataToTable(jsonResponse){   
	
    let datatable = new simpleDatatables.DataTable("#myTable", {
        paging: true,
        sortable: true,
        header: true
    });
    
    if (valueEntered(jsonResponse)){ 
    	jr2 = JSON.stringify(jsonResponse);
    		
    	datatable.import({
    	    type: "json",
    	    data: jr2
    	}) 
    }
    else{
    	console.log("there was no data passed in!");
    }        
    datatable.refresh();
}
```
The first time I hit my button, this works perfectly. The problem is that if I hit my button again (which fetches new data from the back), this error appears in the console: 
```
Uncaught (in promise) TypeError: this.head is undefined
    insert simple-datatables.js:8
    import simple-datatables.js:8
    addDataToTable main.js:345
    response1 main.js:304
    promise callback*xifinMultisearch main.js:304
    onclick (index):1
```
The data is showing up properly. I'm assuming that the problem is either that a) I'm initializing another version of the same table with the same name in the "let" statment, or b) you can only import into a table once via the import() function. What I'd really like to do is something like this: 
```
if (getDataTableInstance() == null) {
 let datatable = new simpleDatatables.DataTable("#myTable", { etc }
datatable.import(data)
}
else {
let ourtable = getDataTableInstance();
ourtable.clear();
ourtable.insert(data); }
```

If I have an existing table, how can I add new data to it? Am I just being an idiot here?

**Comment by johanneswilm** [comment]
@onychomys Hey, could you please post a full example on something like jsfiddle? I am not being paid to work on this and recreating your test case without a full and running example will take a lot more of my time.

**Comment by onychomys** [comment]
Sure thing:

https://jsfiddle.net/xbgjmed1/4/

That's basically how I have things set up now. Each time the button is pressed, I'm reading in some search params, asking the db aobut them, and then needing to display the new results. Right now, I have the fiddle just replacing the inner HMTL of the table's div to blow it up each time and remake it. But that seems like a pretty hacky sort of thing to do, I'm assuming there's some better way. 

And if you comment out that line in the fiddle, like if I was trying to append new results to the bottom of the table, you'll see the error. That error persists whether you use import or insert as your method for putting the data in there.  

Or you can imagine a case where I want to have another button press to remove all rows with a counter over 0.5. I've mocked that up with the half data button in the fiddle, but I'd have to go in and work with the rows (as in the rows() example in the wiki). But I have no way to actually get the table as a DataTable object. 

I'm assuming I'm setting it all up wrong somehow, but all of the examples in the documentation deal with new tables, not existing ones, so  ¯\_(ツ)_/¯

**Comment by johanneswilm** [comment]
Hey @onychomys, I am not sure what you mean by "last line", but I assume what you are failing at doing is reinitiating the datatable a second time on top of the already existing instance. That's a bad idea, yes. But what you can do is initiate the table once and then add more data to it later on. See here: https://jsfiddle.net/johanneswilm/stb97x5q/ . Is there any reason why you didn't do that? 

Alternatively, if you want to destroy the instance and load a new instance with new data, you could have destroyed the instance first, like this: https://jsfiddle.net/johanneswilm/stb97x5q/4/ 

Please reopen if I didn't get your point.

**Comment by jonnsn** [comment]
@johanneswilm I think what he meant (and what I am looking for) is a way to retrieve the already initialized DataTable Instance e.g. from the table dom element without destroying it.

In my case I want to add a listener to the Datatable using its on() method, but I need to do this from somewhere different where the return value of the initial new DataTable() is not accessible.
I could store the reference somewhere in window of course, but would prefer a cleaner solution.

jQuery Datatable has something like this with its API:
https://datatables.net/reference/api/

> The API can be accessed through the following methods:
>    $( selector ).DataTable();
>    $( selector ).dataTable().api();
>    new $.fn.dataTable.Api( selector );
>
>The result from each is an instance of the DataTables API object which has the tables found by the selector in its context. It is important to note the difference between $( selector ).DataTable() and $( selector ).dataTable(). The former returns a DataTables API instance, while the latter returns a jQuery object.

something like:
```javascript
const myDomTable = document.getElementById('myTable')
// mind that I don't save the reference for whatever reason
new DataTable(myDomTable);
```
and somwhere else
```javascript
const myDomTable = document.getElementById('myTable')
myDomTable.DataTable().on('datatable.page',...)
```

**Comment by johanneswilm** [comment]
@jonnsn In my understanding, what you are asking for is the old way of writing JavaScript applications. Back in the time before ES2015, most websites would use jQuery and it would effectively keep track of such things for you. So with jQuery you can ask for "give me that jquery-something-something instance that is connected to dom-element Y".

To you as the one writing the application it looks like magic - somehow jQuery is able to attach all kinds of other data to the dom element, but really the secret is that jQuery itself keeps a register with all that.

In the new world since 2015, in vanilla JavaScript, you don't have that register anymore. Of course you can create your own register (attach it to the global window object), but it's not there out of the box. That's why I cannot just give it to you either. 

The advantage then is that you keep an exact overview of what is there and what is not in your own code. There should be no magic and no surprises about data being stored somewhere.

If you really want to have things the way they were in the old world prior to 2015, you can either A) continue to use jQuery (it's not forbidden), or B) write your own magical object registry mechanism. Something like this:

```js
window.DATATABLES = []

window.getDataTable = function(dom) {
  const dataTableEntry = DATATABLES.find(entry => entry[0] === dom)
  if (dataTableEntry) {
    return dataTableEntry[1]
  }
  const dataTable = new DataTable(dom)
  DATATABLES.push([dom, dataTable])
  return dataTable
}
```

**Comment by jonnsn** [comment]
@johanneswilm thanks a lot for your explanation which I understand and fully agree with :-) I'll go with something like b then and feel more comfortable with that now. I just felt dirty with that - thanks again for demystifying jquery here 👍

Kind regards

**Comment by jonnsn** [comment]
another note for anyone else who is not that familiar with ES:
If I got @johanneswilm right and my (yet) limited ES-Knowledge is not fooling me I am now doing it a more modern way.
In the script where the DataTables are initialized I save them to a local variable and made this available via export.
So in any other script I can simply import this variable and reuse the Datatable instances.

I guess this comes closer to
> There should be no magic and no surprises about data being stored somewhere.

Thanks again for pushing into the right direction!

**Comment by shaunroselt** [comment]
> for pushing into the right direction!

Would you mind sharing some of the code you wrote to achieve this? 

like just show some code examples for future references here.

**Comment by jonnsn** [comment]
quite some time ago, but I think it was this here:
`export let dataTables = {}
//...
document.querySelectorAll('.my-datatable').forEach((element) => {
  const dataTable = new DataTable(element,options);
  dataTables[element.id] = dataTable;
});`

Then one could use something like this elsewhere
`import {dataTables} from "./xyz"
if (typeof dataTables[someElement.id] !== 'undefined') {
  const myDataTable = dataTables[someElement.id]
}`

There still might be better ways though :)

Hth
