### ISSUE TITLE
Fetch from MongoDB

### ISSUE THREAD

**Issue by AverTry** [fiduswriter/Simple-DataTables#92]
No problem with this data in other fetch calls to frontends, that I have. 
As you can see I'm pulling from data.results, everything looks fine in the console, compared to your demo.json which works fine, so it must be the return Mongo format. I put all the output data into an online Json checker without issue. So I'm a bit stumped as to the problem?

In the sample data below, it could be the MongoDB "_id" or the html content in "comments" that could be the cause?

ANSWERED MY OWN QUESTION! I fetched a page without any comments content and it loaded. So it's the html for the ckeditor control (RichText formatting module) Not sure if that's fixable, I might have to exclude it in the data pull somehow. Anyway I will send this to you, at least so that you are aware of it. 
Thanks for all your work on this project.

```
      let table = new simpleDatatables.DataTable(".table", {
        data: {
          headings: Object.keys(data.results[0]),
          data: data.results.map(item => Object.values(item))
        }, 

{
  "next": {
    "page": 2
  },
  "results": [
    {
      "Status": "Inactive",
      "Prefix": "Miss",
      "FirstName": "K",
      "LastName": "Q",
      "HouseNo": "543",
      "Street": "Here n here",
      "City": "Homie",
      "County": "Looking Around",
      "PostCode": "rdtrd65",
      "Country": "this one to you",
      "Comments": "<h2 style=\"text-align:center;\"><span style=\"color:hsl(30,75%,60%);\">Hey</span>, <span style=\"color:hsl(210,75%,60%);\"><strong>how</strong></span> <u>are you</u> <span style=\"background-color:hsl(150,75%,60%);color:hsl(0,0%,30%);\"><i><strong>Today?</strong></i></span></h2>",
      "LastMeeting": "2020-04-28T12:13:00.000Z",
      "NextMeeting": "2020-08-31T22:29:00.000Z",
      "BusinessLine": "447432434432",
      "HomePhone": "45678976765876540",
      "MobilePhone": "23454764766765430",
      "Email": "87587@fuf.net",
      "WebSite": "https://www.kufuf.net",
      "FaceBook": "",
      "_id": "5fa5a424bacb7177bab4adc6",
      "RecordNo": 2,
      "LastUpdated": "2020-08-31T22:29:06.000Z",
      "AccountCreated": "2020-04-30T16:39:00.000Z",
      "Facebook": "www.facebook/kq"
    }
  ]
}

simple-datatables.js:8 Uncaught (in promise) Error: The number of rows do not match the number of headings.
    at simple-datatables.js:8
    at Array.forEach (<anonymous>)
    at u.d (simple-datatables.js:8)
    at u.render (simple-datatables.js:8)
    at u.init (simple-datatables.js:8)
    at new u (simple-datatables.js:8)
    at DS-Paginate.js:69
```

**Comment by johanneswilm** [comment]
Hey @AverTry , I think this error comes from the responses being dicts with a varying number of entries. Is that correct?

Yes, like if that is your case, then you need to write some code to handle that. The example code assumes that all dicts are the same and that there is at least one entry.

It sounded like you found a fix for it yourself already, right? So I can close this issue? Please reopen if I misunderstood.
