### ISSUE TITLE
Row filtering

### ISSUE THREAD

**Issue by leesherwood** [fiduswriter/simple-datatables#93]
Is there a way to filter rows of the table using a callback? Something like:

```
var tableOptions = {

    filter: function(row) {
        // Show only users that are older than 50
        return parseInt(row.columns('Age').text) >= 50;
    }

};

```

From what I can tell, the current implementation of filtering hijacks the sort function, so if I wanted my table to sort by name, but filter by age, that's not possible unless I initially sort by name, then tell it to re-sort straight after by age, which would then filter rather than sort? 

_I could change my data source from HTML to JSON, filter the source JSON array and swap out the table data. But then I wouldn't be able to do things like custom cell rendering like adding dynamic cell classes?_

I guess I could look at creating a plugin for this, but I wanted to make sure I wasn't misinterpreting how the code works before I start on that?

**Comment by johanneswilm** [comment]
Yes, filtering using a clabback is supported in version6. See wiki.
