### ISSUE TITLE
Ordering by different value than visible (time amount)

### ISSUE THREAD

**Issue by AuroraLS3** [fiduswriter/simple-datatables#94]
## Problem

I am attempting to migrate from [DataTables](https://datatables.net/) as this library seems to offer very similar functionality.

There is however a feature that allows sorting rows by a different value than what is visible on the table. This is useful when displaying amount of time that is not a date eg. "1 months, 3 days, 15 hours". In DataTables I can sort by the amount of milliseconds this formatted time represents.

In DataTables this is achieved by using different properties in the `column` definiton
```js
{
    data: 'start_date',
    render: {
        _: 'display',
        sort: 'timestamp'
    }
}
```
data
```js
{
    "name":       "Tiger Nixon",
    "position":   "System Architect",
    "start_date": {
        "display": "Mon 25th Apr 11",
        "timestamp": "1303682400"
    },
    "office":     "Edinburgh"
}
```
Displays `Mon 25th Apr 11` but sorts by `1303682400`

## How to do it?

I am unsure if this library currently supports something like this, but the wiki doesn't seem to have that kind of behavior explained, so I think this might be a feature request.

I thought this could be implemented as a plugin, but it seems that the sort event or sort method doesn't really allow specifying the order at which the items are sorted.

**Comment by johanneswilm** [comment]
@AuroraLS3 Have you figured out how to do it? In that case, please post the answer. Otherwise, I'd suggest to keep this ticket open until either you or someone else programs the solution. It's not a problem for my projects as in Sweden we use the default ISO date format which also orders well. It sounds like this is an issue mainly for US Americans.

**Comment by AuroraLS3** [comment]
I decided to keep using jQuery DataTables for now and closed the issue since I no longer need the feature. I guess that someone else might need it in the future.

**Comment by AuroraLS3** [comment]
Thanks for letting me know :)

We switched to React so this might come handy to get rid of jQuery
