### ISSUE TITLE
onClick event is not working on <tr> (Table Row)  or <td> (Table Data) tags

### ISSUE THREAD

**Issue by mdnmnahmed** [fiduswriter/simple-datatables#95]

**Comment by rhoit** [comment]
I tried as original datatable [event](https://datatables.net/examples/advanced_init/events_live.html) using querySelectorAll
works but when there is the pagination all the event binding is lost.

```js
document.querySelectorAll("#mytable tbody tr").forEach(
    function (e) {
        e.addEventListener("click", function () {
            alert('hello')
        })
    }
)
```

**Comment by rhoit** [comment]
I came up with the hack

```js
function onRowClick() {
    alert('hello')
}

new simpleDatatables.DataTable("#mytable", {
    'columns' : [{
        'select' : 0,
        'render' : function(data, cell, row) {
            row.setAttribute('onclick', 'onRowClick()')
            return data
        }
    }]
})
```

**Comment by rhoit** [comment]
this was the jquery equivalent

```js
document.addEventListener('click', function (e) {
    for (let t = e.target; t && t != this; t = t.parentNode) {
        if (t.matches("#mytable tbody tr")) {
            alert("hello")
            break
        }
    }
}, false)
```

**Comment by johanneswilm** [comment]
Hey @D3vmotiv  @rhoit @mdnmnahmed you will need to put the event listener on `table.dom`. Anything below that level may disappear or change while the table is in operation. When the event is triggered, you can inspect the `event.target` to see whether it is the element you were expecting. I hope that helps.
