### ISSUE TITLE
add option for other languages

### ISSUE THREAD

**Issue by presercomp** [fiduswriter/Simple-DataTables#96]
Is it possible to add the option to change the language of the user interface, by means of a .json or .lang file?
I've been reading the documentation and this option apparently doesn't exist. It would be ideal for those of us who present interfaces other than English.

**Comment by johanneswilm** [comment]
Hey @presercomp ,
yes that is already available. We don't maintain translations in the sources here as there may be many subvariants of Spanish, English, German, etc. that you might want to use. But you can define all the strings [1]  and then translate them as part of the translation of your main software. See for example how we did it in Fidus Writer where we just need to translate one string [2].

[1] https://github.com/fiduswriter/Simple-DataTables/blob/master/src/config.js#L35-L40
[2] https://github.com/fiduswriter/fiduswriter/blob/master/fiduswriter/document/static/js/modules/documents/overview/index.js#L256

**Comment by ZhangChengLin** [comment]
https://github.com/fiduswriter/simple-datatables/blob/00bd599c468a1a8e2c982a3d049b3396ab1fc5cb/src/config.ts#L57-L64
